#!/usr/bin/env python3
"""BM653: build every medium the row boots, and predict each one's wire BEFORE
any qemu runs.

Four loader/image pairings come out of one source tree:

  px         the forked stage2 + BM651's green image          (legs 1, 2, 4, 5)
  beeoff     the same leg with pass 1 NOPed, same image       (leg 3, control)
  halt       forked stage2 + the image that never returns     (leg 6)
  scribbler  forked stage2 + the image that keeps the contract
             and poisons the kernel header band anyway         (leg 7)

Each pairing gets its OWN `.inc`, so its own EXPECTED_CRC and EXPECTED_EXEC_NID
-- `bm653_pxcodec.build_all()` emits both constants for one image, which is the
only reason a variant cannot end up booted against another variant's gate. The
forked asm text is then generated by `bm653_construct.fork()`, which re-applies
the named deltas and undoes them back to rung6's text for every pairing.

Three proofs before a fixture file is written:

1. ASSEMBLE, warning-free, each pairing, at exactly the container's size -- and
   the stage1 front end is rung6's, byte-identical below the tag slot, so the
   container refusal leg is the same code BM602 gated.

2. REPLAY. `bm602_mkimg.guest_walk` -- rung6's own host model, imported, not
   copied -- re-runs each medium and yields the ECC=, PAR= and computed CRC
   every leg must print. Leg 3 needs a model of a loader whose corrector is
   NOPs, so it gets its OWN (`walk_bee_off`): deliberately a second code path,
   because a bug shared by both would show up as agreement.

3. AGREE, and this is the leg-specific part. For every fixture, the bytes the
   replay says will sit at IMG2_DST when the loader jumps there are compared
   against the image FILE. On the green and repaired media they must match
   byte-for-byte -- that is what "the pixels the loader executes are the ones
   it repaired" means, checked before the boot rather than inferred from a
   banner afterwards. On leg 3 they must NOT: the control says how many of the
   2048 bytes the missing repair would have handed the CPU wrong.

Also predicted here, because only the host knows it in advance: what the
scribbler does to the executed handoff. The image writes 0xDEADBEEF over linear
0x201f1, which is inside the band the loader copies into the zero page AFTER the
image returns, so the poison reaches the kernel -- but only at offsets the
loader does not rewrite itself (it zeroes root_flags at 0x1f2, which erases two
of the four bytes). The predicted surviving bytes are computed from the payload
and handed to bm653_identity.py as an exact offset/value set.

  usage: python3 bm653_mkimg.py        # builds, replays, writes predictions
"""
import json
import re
import subprocess
import sys
import time
import zlib
from pathlib import Path

HERE = Path(__file__).resolve().parent
RUNG6 = HERE.parent / 'rung6'
RUNG9 = HERE.parent / 'rung9'
sys.path.insert(0, str(RUNG6))
sys.path.insert(0, str(HERE))
import bm602_mkimg as bm602                                           # noqa: E402
import bm602_pxcodec as codec                                         # noqa: E402
import bm903_pxcodec as pxc1                                          # noqa: E402
import bm653_construct as construct                                   # noqa: E402
import bm653_pxcodec as bm653_px                                      # noqa: E402

CANON_INC = 'bm653_px_layout.inc'          # written by bm653_pxcodec.py: green
BUILD = HERE / 'build'
FIXDIR = HERE / 'fixtures'
FIXJSON = HERE / 'bm653_fixtures.json'
IMAGES = {'green': 'img2_green.bin', 'halt': 'img2_halt.bin',
          'scribbler': 'img2_scribbler.bin'}
STAGE1_SRC = RUNG6 / 'bm602_stage1.asm'

# The four pairings: (inc name, control loader?). The BEE-OFF control reads the
# SAME .inc as its green twin -- same damage, same constants, one line of the
# loader's text different -- which is what makes the pair a control.
COMBOS = {
    'px':         {'image': 'green',     'inc': CANON_INC,  'control': False},
    'beeoff':     {'image': 'green',     'inc': CANON_INC,  'control': True},
    'halt':       {'image': 'halt',      'inc': 'bm653_px_halt.inc', 'control': False},
    'scr':        {'image': 'scribbler', 'inc': 'bm653_px_scr.inc',  'control': False},
}

POISON_AT = 0x1f1            # what the scribbler writes, and where
POISON_VAL = 0xDEADBEEF
# The loader's own zero-page writes, parsed out of the gated text below, so
# "which poisoned bytes survive" is a fact about the asm, not a memory.
ZP_WRITE = re.compile(r'mov\s+(byte|word|dword)\s+\[ZP_ADDR\s*\+\s*(0x[0-9A-Fa-f]+)\]')


def nasm(src, dst):
    """Warning-free or it does not count -- rung6's rule, its reason unchanged.
    HERE is on the include path first because the per-variant .inc files live
    beside the generated asm."""
    r = subprocess.run(['nasm', '-f', 'bin', '-o', str(dst),
                        '-I', str(HERE) + '/', '-I', str(RUNG6) + '/',
                        '-I', str(RUNG9) + '/', str(src)],
                       capture_output=True, text=True)
    if r.returncode:
        sys.stderr.write(f'nasm {src} FAILED:\n{r.stderr}{r.stdout}\n')
        raise SystemExit(2)
    if r.stderr.strip():
        sys.stderr.write(f'nasm {src} warnings:\n{r.stderr}\n')
        raise SystemExit(2)
    return Path(dst).read_bytes()


def walk_bee_off(med, c, pb, crc8_tab):
    """BM653's model of the CONTROL loader: the seven reads and the
    de-interleave and the CRC, with pass 1 absent, exactly as `times 5 nop`
    makes it absent in the asm.

    This is not `guest_walk` with a patched-out corrector, on purpose: the
    control's prediction is worth more coming from a second implementation,
    since the failure mode being tested is the two halves of one model agreeing
    for the wrong reason. It reads only the four DATA planes (nothing consults
    the parity), and it refuses up front if any destination could overlap a
    plane buffer, because that is the case where the asm's instruction order
    changes the answer and this file does not model it.
    """
    gb, chunk, plane_s, base = (c['PX_GROUP_BYTES'], c['PX_CHUNK_SECTORS'],
                               c['PX_PLANE_SECTORS'], c['PX_BASE_LBA'])
    words = gb // 4
    table = bm602.sub_table(c)
    sink = c['PX_SINK']
    spans = [(b, b + words) for b in pb[:4]]
    for start, end, dst in table + [(0, c['PX_GROUPS'], sink)]:
        assert all(dst + gb <= s or e <= dst for s, e in spans), \
            f'destination {dst:#x} overlaps a plane buffer: the fast ' \
            'de-interleave order would not be the asm\'s'
    bufs = [bytearray(words) for _ in pb[:4]]
    regions, out = {}, []
    crc = 0xFFFFFFFF
    for g in range(c['PX_GROUPS']):
        for p in range(4):
            off = (base + g * chunk + p * plane_s) * 512
            blk = med[off:off + words]
            assert len(blk) == words, f'group {g} plane {p} runs off the medium'
            bufs[p][:] = blk
        decoded = bytearray(gb)
        for p in range(4):
            decoded[p::4] = bufs[p]
        decoded = bytes(decoded)
        for b in decoded:
            crc = (crc >> 8) ^ crc8_tab[(crc ^ b) & 0xFF]
        out.append(decoded)
        dst, start = bm602.dest_for(g, table, sink)
        if start is None:
            regions[dst] = decoded       # bank padding: the same 16 KiB re-covered
            continue
        buf = regions.setdefault(dst, bytearray())
        assert len(buf) == (g - start) * gb, f'group {g}: dst {dst:#x} mis-stridden'
        buf += decoded
    return {'payload': b''.join(out), 'regions': regions,
            'crc': (crc ^ 0xFFFFFFFF) & 0xFFFFFFFF}


def zp_writes(asm_text):
    """Every linear offset the loader overwrites in the zero page, with its
    width -- read out of the asm, not from this file's memory of it."""
    out = {}
    for width, off in ZP_WRITE.findall(asm_text):
        n = {'byte': 1, 'word': 2, 'dword': 4}[width]
        for k in range(n):
            out[int(off, 16) + k] = n
    return out


def predict_poison(payload, forked_asm):
    """The scribbler's prediction: which poisoned bytes are still poisoned when
    the kernel reads the zero page. `payload[0x1f1:0x1f5]` is what the loader
    copies there before it touches its own fields."""
    writes = zp_writes(forked_asm)
    hits = []
    for k, val in enumerate(POISON_VAL.to_bytes(4, 'little')):
        off = POISON_AT + k
        if off in writes:
            continue                       # the loader re-puts it: no witness
        clean = payload[off]
        if clean != val:
            hits.append({'zp_offset': hex(off), 'clean': clean, 'scribbled': val})
    assert hits, 'the scribbler cannot change the zero page at all -- the leg ' \
        'would be vacuous, so it is a bug, not a pass'
    return hits


def data_band(c):
    """Bytes of the medium that sit AHEAD of the pixel band: stage1 plus the
    stage2 container. Nothing the walk decodes can be in there, so a banner
    found before this offset could only have come from the loader's own text --
    which is the thing the leg has to exclude."""
    return c['PX_BASE_LBA'] * 512


def main() -> int:
    t_all = time.time()
    BUILD.mkdir(exist_ok=True)
    FIXDIR.mkdir(exist_ok=True)
    tab_crc = pxc1.crc32_tab()
    inc_tab = [int(t, 0) for line in (RUNG9 / 'bm903_crc32tab.inc').read_text()
               .splitlines() if line.strip().startswith('dd ')
               for t in line.strip()[3:].split(',')]
    assert len(inc_tab) == 256 and inc_tab == tab_crc, \
        'guest CRC table != host CRC table'
    st2_bytes = bm602.defines((RUNG9 / 'bm903_layout.inc').read_text()) \
        ['STAGE2_SECTORS'] * 512

    # ---- the images, and the fact that they are BM651's ----
    imgs = {}
    for label, fn in IMAGES.items():
        p = HERE / fn
        assert p.exists(), f'{p.name} missing: run bm653_img2.py first'
        imgs[label] = p.read_bytes()
        assert len(imgs[label]) == bm653_px.IMG2_LEN

    # ---- stage1 once: the front end is not part of this row ----
    s1 = nasm(STAGE1_SRC, BUILD / 'bm653_stage1.bin')
    proven = (RUNG9 / 'bm903_stage1.bin').read_bytes()
    assert len(s1) == 512 and s1[-2:] == b'\x55\xaa', 'stage1 must be an MBR'
    c0 = bm602.defines((HERE / CANON_INC).read_text())
    assert len(proven) == 512
    assert s1[:c0['PX_TAG_OFF']] == proven[:c0['PX_TAG_OFF']], \
        'stage1 code below the tag slot changed -- the front end is no longer ' \
        'the one BM903 gated'
    assert s1[0x1BE:] == proven[0x1BE:], 'the MBR signature band moved'
    tag = int.from_bytes(s1[c0['PX_TAG_OFF']:c0['PX_TAG_OFF'] + 4], 'little')
    assert tag == c0['PX_CONTAINER'], \
        f'the assembled MBR carries {tag:#010x}, not {c0["PX_CONTAINER"]:#x}'

    # ---- the four pairings ----
    builds = {}
    for combo, spec in COMBOS.items():
        b = bm653_px.build_all(imgs[spec['image']], f'{spec["image"]}.bin')
        inc_name = spec['inc']
        text = bm653_px.inc_text(b)
        if inc_name == CANON_INC:
            # The standalone build's file must BE this text: if pxcodec.py and
            # mkimg ever disagreed about the green medium, the .inc the reader
            # looks at would not be the .inc that was assembled.
            assert (HERE / CANON_INC).read_text() == text, \
                f'{CANON_INC} is not what this build emits'
        else:
            (HERE / inc_name).write_text(text)
            # Only the two gate constants may differ from the green .inc: a
            # third line moving would mean an image variant changed the
            # MEDIUM's geometry, which is the claim bm653_pxcodec made.
            diffs = [(x, y) for x, y in zip((HERE / CANON_INC).read_text().splitlines(),
                                            text.splitlines()) if x != y]
            assert len(diffs) == 2 and all(
                l.startswith('%define EXPECTED_') for l, _ in diffs), \
                f'{inc_name} differs from {CANON_INC} in {len(diffs)} lines: ' \
                f'{[l for l, _ in diffs]}'
        asm_text, ctrl = construct.fork(inc_name, control=spec['control'])
        src_path = BUILD / f'bm653_stage2_{combo}.asm'
        src_path.write_text(ctrl if spec['control'] else asm_text)
        s2 = nasm(src_path, BUILD / f'bm653_stage2_{combo}.bin')
        assert len(s2) == st2_bytes, \
            f'{combo}: stage2 is {len(s2)} B, the container holds {st2_bytes}'
        c = bm602.defines(text)
        assert c['PX_GROUPS'] == b['ngroups'] and c['EXPECTED_CRC'] == b['crc']
        pb, pb_names = bm602.plane_table(asm_text, c)
        med = codec.encode(s1, s2, b['payload'])
        # Re-derive the expectation independently of guest_walk: the CRC the
        # gate compares against is zlib's over the payload, and the payload is
        # what was put in. rung6 proved the macro==zlib agreement; inheriting
        # it is cheaper than re-proving it, and it is rung6's proof, so it is
        # still being made by a program that exists.
        assert b['crc'] == zlib.crc32(b['payload']) & 0xFFFFFFFF
        t0 = time.time()
        w = bm602.guest_walk(med, c, pb, tab_crc)
        assert w['payload'] == b['payload'], f'{combo}: clean replay != payload'
        assert (w['fixed'], w['par'], w['crc']) == (0, 0, b['crc']), \
            f'{combo}: the clean medium did not replay clean: {w["fixed"]}/' \
            f'{w["par"]}/{w["crc"]:08X}'
        img_at_dst = bytes(w['regions'][c['IMG2_DST']])[:bm653_px.IMG2_LEN]
        assert img_at_dst == imgs[spec['image']], \
            f'{combo}: what the walk leaves at {c["IMG2_DST"]:#x} is not the ' \
            'image file -- the leg would execute something else'
        builds[combo] = {'b': b, 'c': c, 'pb': pb, 'asm': asm_text,
                         'fork_asm': asm_text, 'med': med, 's2': s2,
                         'replay_s': time.time() - t0}
        print(f'  {combo:5s} {inc_name:20s} stage2 {len(s2):,} B '
              f'({"BEE-OFF" if spec["control"] else "as forked"}), '
              f'medium {len(med):,} B, replay {(w["fixed"], w["par"])} '
              f'CRC={w["crc"]:08X}, image at {c["IMG2_DST"]:#x} == {IMAGES[spec["image"]]}')

    g = builds['px']
    g['poison'] = predict_poison(g['b']['payload'], g['fork_asm'])
    print(f'  scribbler prediction: {len(g["poison"])} of 4 poisoned bytes reach '
          'the kernel (' + ', '.join(f'{p["zp_offset"]}: {p["clean"]:02X}->{p["scribbled"]:02X}'
                                     for p in g['poison']) + ')')

    # BM651's banner-provenance proof, re-run on THIS loader: if the banner
    # string were anywhere in stage1 or stage2, `IMG2EXEC BANNER NID=...` on
    # the wire would only prove the loader ran. It is in the image and nowhere
    # else -- which is why the transcript line can be read as evidence that the
    # repaired pixels executed. (rung 5's leg printed it from the loader's own
    # copy-down window; this row has no copy-down, and this is the check that
    # says so.)
    BANNER = b'IMG2EXEC BANNER NID='
    assert BANNER not in s1, 'stage1 carries the banner string'
    for combo, bl in builds.items():
        assert BANNER not in bl['s2'], f'{combo}: stage2 payload carries the banner'
        assert BANNER not in bl['med'][:data_band(bl['c'])], \
            f'{combo}: the banner is in the medium before the pixel band, so a ' \
            'leg could print it without decoding anything'
    for label, img in imgs.items():
        assert img.count(BANNER) == 1, f'{label}: banner string {img.count(BANNER)}x'
    print(f'  banner provenance: {BANNER!r} in each image exactly once, in no '
          f'stage1/stage2 build and not in the {data_band(c)//1024} KiB ahead of '
          'the pixel band')

    # ---- fixtures, decided before any boot ----
    c, pb = g['c'], g['pb']
    words = c['PX_GROUP_BYTES'] // 4
    igrp = c['IMG2_GROUP']
    fixtures = []

    def add(name, combo, med, fault, exec_expect, anchor, handoff,
            extra=None, correct=True):
        """One fixture, replayed and recorded. `correct=False` is leg 3's model
        of a loader whose pass-1 call became NOPs: nothing gets fixed, so its
        ECC=/PAR= are zeros BY CONSTRUCTION and its computed CRC is the
        unrepaired one. Recording the repaired numbers there instead would have
        been this file's own first bug -- the fixture would predict the wire of
        a loader that does not exist, and leg 3 would be about a medium, not
        about the corrector."""
        b = builds[combo]
        if correct:
            r = bm602.guest_walk(med, b['c'], b['pb'], tab_crc)
            dec, fixed, par = r['payload'], r['fixed'], r['par']
        else:
            r = walk_bee_off(med, b['c'], b['pb'], tab_crc)
            dec, fixed, par = r['payload'], 0, 0
        good = r['crc'] == b['c']['EXPECTED_CRC'] and dec == b['b']['payload']
        img = bytes(r['regions'][b['c']['IMG2_DST']])[:bm653_px.IMG2_LEN]
        wrong = sum(1 for x, y in zip(img, imgs[COMBOS[combo]['image']])
                    if x != y)
        f = {'name': name, 'combo': combo, 'fault': fault,
             'medium': f'{name}.raw', 'medium_bytes': len(med),
             'pass1': correct,
             'ecc': f'{fixed:08X}', 'par': f'{par:08X}',
             'computed_crc': f'{r["crc"]:08X}',
             'expected_crc': f'{b["c"]["EXPECTED_CRC"]:08X}',
             'verdict': 'PASS' if good else 'FAIL',
             'payload_restored': dec == b['b']['payload'],
             'exec_expect': exec_expect,
             'exec_nid': f'{b["b"]["nid"]:04X}',
             'image_crc32': f'{b["b"]["img_crc"]:08X}',
             'image_bytes_wrong': wrong,
             'handoff_expect': handoff, 'anchor_required': anchor,
             'replay_exact_groups': r.get('exact_groups', 0)}
        if extra:
            f.update(extra)
        (FIXDIR / f['medium']).write_bytes(med)
        fixtures.append(f)
        return f

    # 1. the medium exactly as built: gate passes, image runs, kernel boots.
    add('exec_green', 'px', g['med'], 'none: PXC2-E with BM651\'s green image in '
        'padding group ' + str(igrp), 'OK', True, True)

    # 2. 256 bytes of ONE data plane, inside the image group. This is the row's
    #    headline: the damaged pixels are the executable ones, and the loader
    #    has to repair them before jumping into them.
    dmg = bm602.apply_fault(g['med'], c, [1], igrp, 256, 'stuck_ff')
    # DERIVED, not remembered: this string used to say "256 in-plane words, so
    # 1,024 bytes of the image are wrong", and the check 40 lines below proves
    # the opposite -- the plane-1 lanes are payload bytes 4k+1, so 256 medium
    # bytes wrong is 256 IMAGE bytes wrong inside a 1,024 B span. A leg
    # description that contradicts its own numbers is the kind of thing a
    # reader trusts and a boot does not.
    n_medium = sum(1 for x, y in zip(g['med'], dmg) if x != y)
    assert n_medium == 256, f'the injector changed {n_medium} medium bytes, not 256'
    f2 = add('exec_image_repaired', 'px', dmg,
             f'{n_medium} consecutive bytes of plane 1, at the start of the '
             f'IMAGE group\'s chunk ({igrp}), stuck at 0xFF: every fourth byte '
             f'of the image\'s first {n_medium * 4}, so {n_medium} of its '
             f'{bm653_px.IMG2_LEN} executed bytes are wrong on the medium and '
             'pass 1 must fix them before the jump',
             'OK', True, True)
    assert int(f2['ecc'], 16) > 0, 'a 256-byte fault counted as zero fixes'
    assert f2['image_bytes_wrong'] == 0, \
        f'the repaired medium hands the CPU {f2["image_bytes_wrong"]} wrong ' \
        'image bytes -- the repair did not reach the executable span'

    # 3. the SAME damaged pixels under a loader whose corrector call became five
    #    NOPs. Nothing about the medium differs; the counters and the verdict do.
    bo = builds['beeoff']
    dmg_bo = bm602.apply_fault(bo['med'], bo['c'], [1], igrp, 256, 'stuck_ff')
    data = c['PX_BASE_LBA'] * 512
    assert dmg_bo[data:] == dmg[data:], \
        'the control medium is not the damaged medium from byte ' \
        f'{data} on: the pair would not be a control'
    f3 = add('exec_beeoff_control', 'beeoff', dmg_bo,
             'identical damage to exec_image_repaired, loader with `call '
             'bee_correct` replaced by five NOPs (BM652 §6, size-neutral)',
             None, False, False, correct=False)
    assert f3['verdict'] == 'FAIL' and int(f3['ecc'], 16) == 0, \
        f'the control must refuse with nothing repaired: {f3}'
    assert f3['image_bytes_wrong'] == 256, \
        f'the control should hand the CPU 256 wrong image bytes, got ' \
        f'{f3["image_bytes_wrong"]}'
    # The pair's difference has to be the loader, so say what it is: same
    # damage, and the only changed numbers are the counters and the CRC the
    # two models compute over the same bytes.
    assert f2['image_bytes_wrong'] == 0 < f3['image_bytes_wrong'] and \
        f2['computed_crc'] == f2['expected_crc'] != f3['computed_crc'], \
        'the BEE-OFF control is not the twin of the repaired leg'
    # Which 256 bytes, and that is a check on the interleave model itself: a
    # fault in plane 1 at in-plane word k can only ever be payload byte 4k+1,
    # so if the answer comes back as anything else this file has been decoding
    # the medium in an order the loader does not use.
    r3 = walk_bee_off(dmg_bo, bo['c'], bo['pb'], tab_crc)
    img3 = bytes(r3['regions'][c['IMG2_DST']])[:bm653_px.IMG2_LEN]
    idx = [i for i, (x, y) in enumerate(zip(img3, imgs['green'])) if x != y]
    assert idx == [4 * k + 1 for k in range(256)], \
        f'the unrepaired image differs at {len(idx)} byte(s), first ' \
        f'{idx[:6]} -- not the {256} plane-1 lanes of words 0..255'
    assert r3['crc'] != bo['c']['EXPECTED_CRC'], \
        'the BEE-OFF replay passes the gate, so leg 3 would be measuring the ' \
        'gate and not the corrector'

    # 4/5. the two refusals, moved INTO the image group so what the gate stops
    #      is specifically an image from ever being entered.
    f4 = add('exec_two_symbol_in_image', 'px',
             bm602.apply_fault(g['med'], c, [0, 1], igrp, 1, 'flip',
                               start_word=100),
             'ONE codeword of the image group with a fault in two data planes '
             f'(group {igrp}, in-plane word 100 -> image bytes 400/401). The '
             'syndrome pattern names a symbol, so the corrector is confidently '
             'wrong and the gate is the last thing between that and a JMP',
             None, False, False)
    assert f4['verdict'] == 'FAIL' and int(f4['ecc'], 16) == 1 and \
        f4['image_bytes_wrong'] > 0, \
        f'two faults in one image codeword must be mis-fixed AND refused: {f4}'
    f5 = add('exec_blind_spot_in_image', 'px',
             bm602.apply_fault(g['med'], c, [0, 1, 2], igrp, 1, 'flip',
                               start_word=200),
             f'three equal faults, one in each of d0, d1, d2 of ONE image '
             f'codeword (group {igrp}, word 200): all syndromes zero, so the '
             'corrector prints the clean medium\'s ECC=0 PAR=0 while three '
             'image bytes stay wrong. Invisible to pass 1, refused by the CRC.',
             None, False, False)
    assert f5['verdict'] == 'FAIL' and int(f5['ecc'], 16) == 0 and \
        int(f5['par'], 16) == 0 and f5['image_bytes_wrong'] == 3, \
        f'the blind spot must be invisible AND fatal to the gate: {f5}'

    # 6. an image that enters and never comes back: the loader's own next
    #    instruction never runs, so the only verdict available is an ABSENCE.
    add('exec_halt', 'halt', builds['halt']['med'],
        'none: the clean medium carries the HALT variant, which banners and '
        'then hangs. The gate passed, so the EXEC verdict line can only be '
        'produced by the image returning -- and it does not.',
        'HALT', False, False)

    # 7. contract kept, machine poisoned. The gate passes, EXEC=OK prints, and
    #    the handoff the loader then builds is not the one the clean medium
    #    builds. Predicted above, byte by byte.
    add('exec_scribbler', 'scr', builds['scr']['med'],
        'none: the clean medium carries the SCRIBBLE variant, which keeps '
        'every word of the contract and writes 0xDEADBEEF over the kernel '
        'header band the loader copies into the zero page afterwards.',
        'OK', False, True,
        {'zp_poison': g['poison'],
         'note': 'anchor not required: whether Tiny Core still boots past a '
                 'poisoned loadflags is a RESULT of this leg, not a premise of '
                 'it. The claim is the dump.'})

    names = [f['name'] for f in fixtures]
    assert len(names) == len(set(names)) == 7, names
    for f in fixtures:
        if f['exec_expect'] in (None, 'HALT'):
            assert f['verdict'] == 'FAIL' or f['exec_expect'] == 'HALT', f
        if f['verdict'] == 'PASS':
            assert f['exec_expect'] in ('OK', 'HALT'), f

    FIXJSON.write_text(json.dumps({
        'generated_by': Path(__file__).name,
        # A DURATION, not a timestamp: it is the one line in this file that two
        # passes need not agree on, and run_bm653_e2e.sh strips exactly it when
        # it asks whether pass 2 re-derived pass 1's predictions.
        'host_replay_seconds': round(time.time() - t_all, 1),
        'container': f'{codec.CONTAINER} + executable image group',
        'medium_base_lba': c['PX_BASE_LBA'],
        'tag': f'{tag:08X}', 'tag_offset': hex(c['PX_TAG_OFF']),
        'stage2_container_bytes': st2_bytes,
        'planes': c['PX_PLANES'], 'groups': c['PX_GROUPS'],
        'codewords_per_group': words, 'image_group': igrp,
        'image_dst': hex(c['IMG2_DST']), 'image_len': bm653_px.IMG2_LEN,
        'plane_buffer_table': pb_names,
        'combos': {k: {'inc': v['inc'], 'image': v['image'],
                       'control': v['control'],
                       'stage2_bytes': len(builds[k]['s2']),
                       'payload_crc': f'{builds[k]["b"]["crc"]:08X}',
                       'exec_nid': f'{builds[k]["b"]["nid"]:04X}'}
                   for k, v in COMBOS.items()},
        'fixtures': fixtures,
    }, indent=1) + '\n')

    print(f'7 fixtures written to {FIXJSON.name}: every ECC=, PAR=, CRC=, '
          'EXEC= verdict and handoff dump predicted before a boot')
    for f in fixtures:
        print(f'  {f["name"]:24} combo={f["combo"]:5s} ECC={f["ecc"]} '
              f'PAR={f["par"]} CRC={f["computed_crc"]}/{f["expected_crc"]} '
              f'{f["verdict"]:4s} exec={str(f["exec_expect"]):5s} '
              f'img_wrong={f["image_bytes_wrong"]} nid={f["exec_nid"]}')
    print(f'host replay total {(time.time() - t_all):.0f} s')
    return 0


if __name__ == '__main__':
    sys.exit(main())
