#!/usr/bin/env python3
"""
generate_rs_fixtures.py — pin down the EXACT Reed-Solomon wire format so a Rust
receiver (geometry_os audio_codec.rs, TASK_C035) can decode what Python sends.

Two things this captures that a naive "RSCodec(nsym=10)" note would miss:

  1. The full reedsolo config (prim, fcr, generator, c_exp, nsize) — read off the
     live RSCodec object, not assumed. Rust RS crates frequently default to a
     DIFFERENT primitive polynomial; a mismatch means every payload fails to decode.
  2. The PhyECC wrapper (src/codec/phy_ecc.py) is NOT raw reedsolo — it splits bytes
     into nibbles, packs, RS-encodes, unpacks. We emit fixtures at BOTH the raw
     RSCodec level and the PhyECC.encode() level so the Rust side matches the actual
     transmit format, and so we can see whether the wrapper is a no-op.

Output: rs_fixtures.json — ground-truth (payload -> encoded) pairs + the config.
The Rust test asserts decode(encoded) == payload for every case.
"""

import json
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), 'src'))

from reedsolo import RSCodec
from codec.phy_ecc import PhyECC, DEFAULT_PARITY_BYTES

TEST_CASES = [
    b"",
    b"A",
    b"simple",
    bytes([0x00, 0xFF, 0x55, 0xAA, 0x42]),
    bytes(range(16)),
    bytes(range(256)),                 # spans multiple RS blocks (>245 data bytes)
    b'{"op":["fill","#ff0000"]}',       # a realistic pixel-op payload
]


def rs_config(rs: RSCodec) -> dict:
    """Read the actual parameters off the live codec (defaults included)."""
    keys = ["nsym", "nsize", "fcr", "prim", "generator", "c_exp"]
    cfg = {}
    for k in keys:
        v = getattr(rs, k, None)
        cfg[k] = v
    return cfg


def main():
    nsym = DEFAULT_PARITY_BYTES
    rs = RSCodec(nsym=nsym)
    phy = PhyECC(parity_bytes=nsym)

    cfg = rs_config(rs)
    print("Actual reedsolo config used by PhyECC(RSCodec(nsym=%d)):" % nsym)
    for k, v in cfg.items():
        pretty = hex(v) if isinstance(v, int) and k in ("prim",) else v
        print(f"  {k:10} = {pretty}")

    cases = []
    wrapper_is_noop = True
    for payload in TEST_CASES:
        rs_encoded = bytes(rs.encode(payload)) if payload else b""
        phy_encoded = phy.encode(payload) if payload else b""
        if rs_encoded != phy_encoded:
            wrapper_is_noop = False
        cases.append({
            "payload": list(payload),
            "rs_encoded": list(rs_encoded),
            "phyecc_encoded": list(phy_encoded),
        })

    fixtures = {
        "_comment": "Ground truth for Python->Rust Reed-Solomon interop (TASK_C035). "
                    "Generated by generate_rs_fixtures.py; DO NOT hand-edit.",
        "reedsolo_config": cfg,
        "phyecc_wrapper_equals_raw_reedsolo": wrapper_is_noop,
        "cases": cases,
    }

    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "rs_fixtures.json")
    with open(out, "w") as f:
        json.dump(fixtures, f, indent=2)

    print(f"\nPhyECC wrapper == raw reedsolo? {wrapper_is_noop}")
    print(f"Wrote {len(cases)} cases -> {os.path.basename(out)}")
    # Show one small case so the exact byte layout is visible.
    demo = cases[3]
    print(f"\nExample: payload={demo['payload']}")
    print(f"  rs_encoded     = {demo['rs_encoded']}")
    print(f"  phyecc_encoded = {demo['phyecc_encoded']}")


if __name__ == "__main__":
    main()
