[package]
name = "virtio_pixel_rs_v3_shared"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
miniz_oxide = { version = "0.9.1", default-features = false, features = ["with-alloc"] }
geos_pixel = { path = "../geos_pixel", default-features = false }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = "z"
