"""Prepend the BK-44 landing session entry to .builder_queue/PRODUCT_LANE_STATE.md."""
P = '.builder_queue/PRODUCT_LANE_STATE.md'
old = open(P).read()

entry = """### 2026-10-01 ~00:4x CDT — BK-44 LANDED (FS-allow posture guard, step 6 of the sequenced fence commit): the 0x03 FILE_WRITE and 0x04 FILE_READ HOST arms now consult GLYPH_FS_ALLOW roots — the measured attack-surface inversion BK-15's rationale forbade is fixed in place (builder af3e62239ce2, commit f3582b11 via branch bk44/fs-allow on the REUSED bk40-syscall worktree, merged fast-forward to mainline; picked at HEAD 07eefcc2 == monitor fingerprint, tracked dirty set verified = pre-existing monitor-fix files, mailbox rule clean, newest RULING mtime 09-29 09:08 < HEAD, ledger STATUS ACTIVE, CLAIM QUEUE empty — this was in-flight work from the prior session: engine fix + gate + probe drafted, found RED-leg-defective, completed and landed per the finish-in-flight rule):

- Fix (tools/glyph_isa_v2.py + glyph_dispatch mirror, md5 8dd8ce806e07249b570d2539a1260612 x2): the 0x03 and 0x04 host arms realpath-check the path against _get_fs_allow_roots() (deny-by-default, rc -1 refusal) — exactly the 0x13 arm's landed BK-15 check; placed AFTER the item-25 VFS reroute so VFS-attached writes/reads keep the VFS's own containment. No new dispatch-site consult: handler-posture parity, not a fence term (BK-39/40/42/43 consults untouched). 0x07/0x12 keep GLYPH_RUN_ALLOW; 0x08/0x09 AUDIO + 0x01 WRITE out of scope per the row.
- Gate tests/test_bk44_fs_allow_roots.py 7/7 GREEN. RED-first at landing time (engine stashed): L1 fails (b'WX' lands, rc 0 clean), L2 fails ('AUTUMN' lands, rc 6), L6 passes pre-fix by construction (consult absent == neutered, md5-pinned); fix -> 7/7. Probe .builder_queue/probe_bk44_red_af3e.py (md5 7a268057e72bd67f7f00e8d9f301dc09, measured at HEAD 07eefcc2) committed.
- GATE/TEST DEFECTS caught and fixed this session: (1) the in-flight BK-44 RED probe predated the landed BK-39/40/42 fences — its word-168 staging was trapped before any syscall verdict; re-filed with current geometry (staging run 192..199, dest run 224..231) per the row's own note. (2) test_defect_d_ram_scoped_handlers.py's 0x03 historical-leg anchor was STALE — it predated both the item-25 VFS reroute block and this landing's root check ('anchor stale' on first run); re-synced to the full live handler body (path line + VFS reroute + DEFECT-D comment + BK-44 check + data lines) and the suite got a per-test tmp_path autouse GLYPH_FS_ALLOW fixture — migrated, never weakened. (3) Same fixture migration for test_glyph_app_echo.py (autouse), test_glyph_file_io.py (try/finally), test_item25_vfs.py (fixture), test_bk42_fw_exfil_fence.py L4/L6 (/tmp arming). (4) experiments/glyph_l1_shell.py _stamp_path arms the session root via the shell's existing _arm_fs_allow — the single choke point all file verbs stamp through; append-only.
- Family on the committed tree: BK-44 7/7 + BK-15 + BK-38..43 + item-25 VFS + file-io + app-echo + defect_d = 111/111 combined substantive run; item-26..36 migration chain 9 suites all green post-commit incl. every test_n1 engine-byte guard (RED-by-design pre-commit per the BK-76/40/41/42/43 precedent, green at f3582b11); xv6-nano 13/13; pre-commit hook at landing: differential 38/38 + Pillar 2.3 parity 8/8. WGSL twin UNTOUCHED (0x03/0x04 honest no-op stubs pinned by test_defect_d). Numbers structural, rule-1 floors do not attach.
- NOT proved / open: BK-45 VFS reroute dests (next row); 0x01 WRITE + 0x08/0x09 AUDIO windows (separate class); VFS-attached legs (item-25's own gate owns those); symlink-escape/TOCTOU beyond realpath (single-threaded handler, out of scope); allowlist CONTENT policy beyond deny-by-default (operator chooses roots; the gate pins the mechanism only).
- Next tick: BK-45 (VFS reroute dests) per the row order, unless a new CLAIM QUEUE item or binding RULING appears first.

STATUS: ACTIVE

"""
open(P, 'w').write(entry + old)
print('ledger entry prepended')
