"""Append this tick's near-escalation entry (DEFECT-28 file (3)). Run once from the repo root."""

from pathlib import Path

ENTRY = """
## 2026-09-13 20:1x CDT — Almost asked: "DEFECT-28 file (3) says *fix the module (not the assertions) or show the caller is wrong* — but the constructor takes `n_fft=2048` while every failing gate leg feeds a 129/257/33-bin spectrogram. Is re-deriving `n_fft` from the input a *translation-semantics* change I should hold for Jericho, and is the caller (the test) the wrong side?"

**Decided instead:** measured which side carries the frame geometry, then classified it mechanism-class ("restoring self-documented behaviour") under `RULING_standing_authorization.md` and landed it; and on the way found the file carried a **second**, unrelated defect that the ticket had not named.
**Reason:** the ambiguity dissolved under one probe (`/tmp/probe_defect28f3_bin_inference.py`, librosa 0.11.0): `istft(bins=129, hop=64)` returns 960 samples and the *forward* `stft(len=960, n_fft=2048)` returns 1025 bins while `n_fft=256` returns 129 — i.e. librosa already treats the bin count as the carrier of `n_fft`, so the module's two calls were using **two different frame geometries inside one round trip**. There is no caller-side fix that makes that consistent, and "the module is the product unless measurement says otherwise" holds: the input wins, loudly (`UserWarning` naming both values, `ValueError` for `bins < 2`), never silently. The second defect had nothing to do with bins: `random_state` was honoured by `np.random.seed()` in `__init__` while the draws happen in `reconstruct()`, so two equally-seeded instances produced 99.6 %-different audio against the docstring's own promise — also mechanism-class.
**Outcome:** `tests/test_griffin_lim.py` **4 failed/18 passed → 22 passed** with the test file byte-identical (`sha256 8ac35422…` before == after), non-vacuity RED in both directions (re-pin the forward `stft` → 3 failed; revert the RNG → 1 failed), neighbour gate `6 failed/33 passed` (only delta: griffin 4 → 0). Commit `e8e71f0`. Two secondary decisions worth naming: (1) I landed in the **main checkout, not a worktree** — AGENTS.md's blast-radius pattern names *core codec* components and the loop names `baker.py`/`rv64i_to_glyph.py`/`glyph_dispatch/**`/WGSL; `src/griffin_lim.py` is an audio module no test other than its own imports, and nothing can be verified in isolation beyond what the gate already does — if that judgment is wrong, the fix is 45 lines and reverts cleanly. (2) The row-gate sweep produced **3 new TIMEOUTs** (`test_spatial_rv32i_cpu.py`, `test_sbi_firmware.py`, `test_rv64i_to_glyph_xv6_nano.py`) and I landed anyway rather than calling the row green — I re-ran all three in isolation (19 passed/39.95 s; 13 passed/49.02 s) under a load average of 5.8–9.7, showed none of them imports the changed module, and wrote the honest delta into the receipt instead of rounding "no other file may regress" up. Tell for next time: **when a defect ticket offers two options, measure the third possibility first — this file had two independent bugs and the ticket's "bin contract" framing hid the second one entirely; and when a sweep's only regressions are TIMEOUTs on files that pass in isolation, that is a load reading, not a verdict — attribute it explicitly rather than taking the verdict.**
"""

path = Path("NEAR_ESCALATIONS.md")
before = path.stat().st_size
with path.open("a") as handle:
    handle.write(ENTRY)
print(f"appended {path.stat().st_size - before} bytes (was {before}, now {path.stat().st_size})")
