#!/usr/bin/env python3
"""Append the BK-42 RESOLUTION tail to systems/GLYPH_BACKLOG.md row 69
(BK-42) — proven channel: append_bk40_resolution.py precedent."""
from pathlib import Path

p = Path("systems/GLYPH_BACKLOG.md")
text = p.read_text(encoding="utf-8")

marker = " | `.builder_queue/RESEARCH_fw_exfil_path_read.md` (2026-09-27, builder af3e62239ce2) |"
assert text.count(marker) == 1, f"marker count {text.count(marker)}"
tail = (" **RESOLUTION (2026-09-30, builder af3e62239ce2, commit bf60a51f via branch "
        "bk42/path-fence on the reused bk40-syscall worktree, merged fast-forward to "
        "mainline at HEAD bf60a51f): the FILE_WRITE exfil + path-decoder fence guard "
        "LANDED (sequenced fence commit step 4) — (a) GlyphCPUv2._bk42_source_fault(src, "
        "length, kind): word-granular DATA SOURCE window scan for 0x03 FILE_WRITE (the "
        "handler reads self.memory[src+i], one byte per word — BK-40's dest convention), "
        "consulted at the SYSCALL dispatch site BEFORE the handler runs; (b) "
        "GlyphCPUv2._bk42_path_fault(path_addr): walks the path decode EXACTLY as "
        "_read_path will (same FS-pixel alias arm admitted, same past-RAM break, same "
        "4096 ceiling) and refuses at the first out-of-fence word — an unterminated "
        "in-tile path can no longer decode across the tile boundary (_BK42_PATH_SYSCALLS "
        "= 0x03/0x04/0x07/0x08/0x09/0x12/0x13). Refusal = the landed E-K1 tail via "
        "_stack_fence_fault (fault_addr = word<<2, packed fault_pc, mode->SUPER, "
        "KFAULT_PC vector, kf==0 stop): handler never executes, no host file is created "
        "or touched. Reason tags `syscall_source_fence:<kind>` / `path_decode_fence`. "
        "Term set identical to every landed consult: USER + _tile_confinement + "
        "_iso_enabled + _addr_in_box (boxes + GO-2 tile); SUPER (E-K2 dispatch) and "
        "unfenced tasks untouched. General LD remains governed by "
        "RULING_BK38_READ_POSTURE (cooperative read-shared model) — this consult fences "
        "syscall ARGUMENT windows only. Gate tests/test_bk42_fw_exfil_fence.py 7/7 (L1 "
        "data-source refusal w/ fault_addr=src*4 + NO host file; L2 LD-fed shape traps "
        "AT THE LD (BK-38's GO-2 consult owns it) + no file; L3 unterminated path "
        "refused w/ path_decode_fence + pre-fix artifact absent; L4 in-tile FILE_WRITE "
        "lands + FILE_READ control; L5 ST trap control; L6 non-vacuity — both consults "
        "shadow-neutered per-instance, engine md5-pinned before/after, pre-fix exfil "
        "b'FK' lands clean; L7 family subprocess BK-40 + BK-41 + BK-39). RED-first at "
        "landing (unfixed tree, /tmp/bk42_red.log md5 "
        "74d14df5b755ecbc3877c09a9b3af05a, exit 1): L1 rc=0 clean, '[SYSCALL] "
        "FILE_WRITE: 2 bytes from addr 168 to path at 193' (exfil landed); L3 rc=0 "
        "clean, decode crossed into out-of-tile words 200..202; 2 failed / 5 passed "
        "(L2/L4/L5/L6/L7 green = harness live). Fix applied -> 7/7. GATE-DRAFT DEFECTS "
        "caught by the gate's own legs pre-evidence, receipted in the test docstring: "
        "(1) fixture geometry — the GO-2 tile (5,0,8,8) term is Hilbert-scattered, "
        "in-tile contiguous runs are (160..167),(192..199),(224..231)... "
        "(probe_bk42_geom_af3e, live _addr_in_box); first-draft staging at word 200 was "
        "OUT of tile and the landed BK-39 fence trapped the STAGING PARALLEL_ST "
        "(fault_addr=800), masking the syscall verdict (L4's control exposed it); all "
        "staging moved to run (192..199), paths shortened to 6 chars + NUL at word 199. "
        "(2) A first-draft 16-char path staged from word 196 crossed the run boundary — "
        "same masking shape. Family on the committed tree: BK-42 7/7; fence family "
        "BK-40 8/8 + BK-41 10/10 + BK-39 11/11 + BK-76 8/8 + BK-76-twin + BK-48-twin "
        "6/6 + BK-49 7/7 + BK-66 7/7 + invariants 3/3 (47 passed combined substantive "
        "run); xv6-nano 13/13 + 18p/2s boot regression; item-29 10/10 post-landing "
        "(test_n1 drift guard RED by design pre-commit, green at bf60a51f); pre-commit "
        "Pillar 2.3 parity 8/8 + transpiler differential suites green at commit "
        "(engine file touched, hook ran). Engine copies synced md5 "
        "d7549493447084b6047078d06df828b4 x2; WGSL twin UNTOUCHED (syscall handlers "
        "oracle-Python-only, no twin surface — BK-40 precedent). Numbers structural, "
        "rule-1 floors do not attach. NOT proved / still open: BK-43 RUN path/argv legs "
        "beyond the shared path-decode consult landed here (0x07/0x12 allowlist smuggle "
        "re-files under its own row/gate — the consult already blocks the decode-cross "
        "channel its L1 rides); VFS-attached FILE_WRITE/FILE_READ legs (no VFS device "
        "in this harness; the consult covers the VFS arms structurally at the dispatch "
        "site); 0x01 WRITE output window + 0x08/0x09 AUDIO windows (separate class); "
        "BK-44 FS-allow posture + BK-45 VFS reroute dests open rows; BK-50 twin door "
        "posture unchanged; live-kernel coverage = the 13-scenario xv6-nano suite.** |")
text = text.replace(marker, marker + tail, 1)
p.write_text(text, encoding="utf-8")
print("appended; new line count:", text.count("\n"))
