#!/usr/bin/env python3
"""Prepend the BK-42 session entry to .builder_queue/PRODUCT_LANE_STATE.md."""
from pathlib import Path

p = Path(".builder_queue/PRODUCT_LANE_STATE.md")
old = p.read_text(encoding="utf-8")
entry = """### 2026-09-30 ~23:2x CDT — BK-42 LANDED (FILE_WRITE exfil + path-decoder fence guard, step 4 of the sequenced fence commit): 0x03 FILE_WRITE's data SOURCE window and the shared _read_path decode are fenced — a tiled USER task can no longer exfil guest RAM to an arbitrary host path, and an unterminated path can no longer decode across the tile boundary (builder af3e62239ce2, commit bf60a51f via branch bk42/path-fence on the REUSED bk40-syscall worktree — disk constraint, see below — merged fast-forward to mainline; picked at HEAD 2a203221 == monitor fingerprint, tracked dirty set verified = pre-existing monitor-fix files, mailbox rule clean, newest RULING mtime 09-29 09:08 < HEAD 22:55, ledger STATUS ACTIVE, CLAIM QUEUE empty):

- Fix (tools/glyph_isa_v2.py + glyph_dispatch mirror, md5 d7549493447084b6047078d06df828b4 x2): GlyphCPUv2._bk42_source_fault(src, length, kind) — word-granular DATA SOURCE window scan for 0x03 FILE_WRITE (handler reads self.memory[src+i], one byte per word — BK-40's dest convention), consulted at the SYSCALL dispatch site BEFORE the handler runs; GlyphCPUv2._bk42_path_fault(path_addr) — walks the path decode EXACTLY as _read_path will (same FS-pixel alias arm admitted, same past-RAM break, same 4096 ceiling) and refuses at the first out-of-fence word, covering _BK42_PATH_SYSCALLS = 0x03/0x04/0x07/0x08/0x09/0x12/0x13. Refusal = the landed E-K1 tail via _stack_fence_fault: handler never executes, no host file created or touched. Reason tags `syscall_source_fence:<kind>` / `path_decode_fence`. Term set identical to every landed consult: USER + _tile_confinement + _iso_enabled + _addr_in_box; SUPER (E-K2 dispatch) and unfenced tasks untouched. General LD stays governed by RULING_BK38_READ_POSTURE (cooperative read-shared model) — syscall ARGUMENT windows only.
- Gate tests/test_bk42_fw_exfil_fence.py 7/7 GREEN. RED-first at landing (unfixed tree, /tmp/bk42_red.log md5 74d14df5b755ecbc3877c09a9b3af05a, exit 1): L1 rc=0 clean, '[SYSCALL] FILE_WRITE: 2 bytes from addr 168 to path at 193' (exfil landed); L3 rc=0 clean, path decode crossed into out-of-tile words 200..202 (the measured pre-fix channel); 2 failed / 5 passed (L2/L4/L5/L6/L7 green = harness live, consults absent). Fix applied -> 7/7.
- GATE-DRAFT DEFECTS caught by the gate's own legs pre-evidence, receipted in the test docstring: (1) FIXTURE GEOMETRY — the GO-2 tile (5,0,8,8) fence term is Hilbert-scattered: in-tile contiguous runs are (160..167),(192..199),(224..231),(256..263)... (probe .builder_queue/probe_bk42_geom_af3e.py, live _addr_in_box); the first-draft staging at word 200 was OUT of tile and the landed BK-39 fence trapped the STAGING PARALLEL_ST (fault_addr=800), masking the syscall verdict — L4's in-tile control failing exposed it; all staging moved to run (192..199). (2) A first-draft 16-char path staged from word 196 crossed the run boundary at 200 — same masking shape; paths shortened to 6 chars + NUL at word 199.
- DISK CONSTRAINT (operations note): /home at 99% (21G free), each full worktree ~25G (large binary fixtures) — `git worktree add` for a fresh bk42 worktree died ENOSPC (partial checkout cleaned, branch deleted, worktree pruned). Landed instead on the REUSED bk40-syscall worktree: untracked leftovers removed, branch re-pointed `git switch -c bk42/path-fence 2a203221` — same worktree-isolation guarantee (engine changes isolated from mainline until gate-green), zero new disk. Worktree cleanup/merge-back decision for bk42/path-fence vs re-pointing again next rung: next session's call.
- Family on the committed tree: BK-42 7/7; fence family BK-40 8/8 + BK-41 10/10 + BK-39 11/11 + BK-76 8/8 + BK-76-twin + BK-48-twin 6/6 + BK-49 7/7 + BK-66 7/7 + invariants 3/3 (47 passed combined substantive run); xv6-nano 13/13 + 18p/2s boot regression; item-29 10/10 post-landing (test_n1 drift guard RED by design pre-commit, green at bf60a51f — BK-76/BK-40/BK-41 precedent); pre-commit Pillar 2.3 parity 8/8 + transpiler differential suites green at commit (engine file touched, hook ran). WGSL twin UNTOUCHED (syscall handlers oracle-Python-only, no twin surface — BK-40 precedent). Numbers structural, rule-1 floors do not attach.
- NOT proved / open: BK-43 RUN path/argv legs beyond the shared path-decode consult landed here (the consult already blocks the decode-cross channel BK-43's L1 rides; its allowlist-smuggle gate re-files under its own row); VFS-attached FILE_WRITE/FILE_READ legs (no VFS device in this harness; consult covers the VFS arms structurally at the dispatch site); 0x01 WRITE output window + 0x08/0x09 AUDIO windows (separate class); BK-44 FS-allow posture + BK-45 VFS reroute dests open rows; BK-50 twin door posture unchanged; live-kernel coverage = the 13-scenario xv6-nano suite.
- Next tick: BK-43 (RUN path/argv gate — mostly pre-blocked by this landing's consult; verify L1/L2 shapes then re-file its gate) or BK-44/45 per the row order, unless a new CLAIM QUEUE item or binding RULING appears first.

STATUS: ACTIVE

"""
p.write_text(entry + old, encoding="utf-8")
print("prepended; lines:", (entry + old).count("\n"))
