#!/usr/bin/env python3
"""BM903 step 1: medium layout + pinned include files for the asm (brief step 1).

Emits:
  bm903_layout.inc   nasm %defines for the medium geometry
  bm903_cmdline.inc  the oracle cmdline, byte-exact, zero-padded to 512 B
  bm903_e820.inc     the oracle e820 blob (frozen MUST-MATCH class: BM902's
                     construction copies this table, it does not re-query BIOS)
  bm903_layout.json  the same numbers for the image builder + the gate
"""
import json
import struct
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
KERNEL = HERE / "vmlinuz64.extracted"
INITRD = HERE.parent / "rung7" / "core.gz"
ORACLE_ZP = HERE / "oracle_zp_leg0.bin"
ORACLE_CMDLINE = HERE / "oracle_cmdline_leg0.bin"

SECTOR = 512
STAGE2_SECTORS = 16          # reserved slot: breaks the stage2-size define cycle
CMDLINE_ADDR = 0x1f800
CMDLINE_BYTES = 512
INITRD_ADDR = 0x10000000     # OUR choice (loader-specific; addendum row)
HDR_SCRATCH = 0x20000        # where stage2 lands the kernel's first 2 sectors
ZP_ADDR = 0x13ab0            # frozen (rsi)


def sectors(nbytes: int) -> int:
    return (nbytes + SECTOR - 1) // SECTOR


def main() -> int:
    kimg = KERNEL.read_bytes()
    initrd = INITRD.read_bytes()
    zp = ORACLE_ZP.read_bytes()
    cmd = ORACLE_CMDLINE.read_bytes()
    assert len(zp) == 4096 and len(cmd) == CMDLINE_BYTES, "oracle dumps wrong size"
    assert kimg[0x202:0x206] == b"HdrS", "kernel header magic missing"
    setup_sects = kimg[0x1f1]
    assert setup_sects == 0x1B, f"setup_sects {setup_sects:#x} != 0x1b"
    payload_off = (setup_sects + 1) * SECTOR
    payload = len(kimg) - payload_off

    kernel_lba = 1 + STAGE2_SECTORS
    kernel_sects = sectors(len(kimg))
    payload_lba = kernel_lba + payload_off // SECTOR
    payload_sects = sectors(payload)
    initrd_lba = kernel_lba + kernel_sects
    initrd_sects = sectors(len(initrd))

    n_e820 = zp[0x1e8]
    e820 = zp[0x2D0:0x2D0 + n_e820 * 20]
    assert len(e820) == n_e820 * 20

    Path("bm903_layout.inc").write_text(
        f"""; generated by bm903_consts.py -- DO NOT EDIT
%define STAGE2_SECTORS {STAGE2_SECTORS}
%define KERNEL_LBA {kernel_lba}
%define KERNEL_SECTORS {kernel_sects}
%define PAYLOAD_LBA {payload_lba}
%define PAYLOAD_SECTORS {payload_sects}
%define PAYLOAD_BYTES {payload}
%define INITRD_LBA {initrd_lba}
%define INITRD_SECTORS {initrd_sects}
%define INITRD_BYTES {len(initrd)}
%define INITRD_ADDR {hex(INITRD_ADDR)}
%define HDR_SCRATCH {hex(HDR_SCRATCH)}
%define ZP_ADDR {hex(ZP_ADDR)}
%define CMDLINE_ADDR {hex(CMDLINE_ADDR)}
%define CMDLINE_BYTES {CMDLINE_BYTES}
""")

    # cmdline: emit every byte (the L2 leg compares all 512)
    lines = ["; generated from oracle_cmdline_leg0.bin -- byte-exact"]
    for i in range(0, CMDLINE_BYTES, 16):
        lines.append("  db " + ", ".join(str(b) for b in cmd[i:i + 16]))
    Path("bm903_cmdline.inc").write_text("\n".join(lines) + "\n")

    lines = [f"; oracle e820 raw bytes, 20 B/entry ({n_e820} entries)"]
    for i in range(0, len(e820), 20):
        lines.append("  db " + ", ".join(str(b) for b in e820[i:i + 20]))
    Path("bm903_e820.inc").write_text("\n".join(lines) + "\n")

    json.dump({"kernel_lba": kernel_lba, "kernel_sectors": kernel_sects,
               "kernel_bytes": len(kimg), "payload_lba": payload_lba,
               "payload_sectors": payload_sects, "payload_bytes": payload,
               "initrd_lba": initrd_lba, "initrd_sectors": initrd_sects,
               "initrd_bytes": len(initrd), "initrd_addr": INITRD_ADDR,
               "stage2_sectors": STAGE2_SECTORS, "zp_addr": ZP_ADDR,
               "cmdline_addr": CMDLINE_ADDR, "e820_entries": n_e820,
               "medium_sectors": initrd_lba + initrd_sects},
              open("bm903_layout.json", "w"), indent=1)
    print(f"kernel LBA {kernel_lba} ({kernel_sects} s), payload LBA "
          f"{payload_lba} ({payload_sects} s), initrd LBA {initrd_lba} "
          f"({initrd_sects} s) -> medium {initrd_lba + initrd_sects} sectors")
    return 0


if __name__ == "__main__":
    sys.exit(main())
