#!/usr/bin/env python3
"""
Pattern extraction script - analyzes existing SPATIAL_RV64I.wgsl to identify
instruction patterns for migration to the DSL.

This shows how to incrementally migrate from monolithic WGSL to the DSL approach.
"""

import re
from typing import Dict, List, Tuple
from dataclasses import dataclass


@dataclass
class ExtractedPattern:
    """Pattern extracted from existing WGSL code"""
    instruction_name: str
    opcode: int
    opcode_match: str
    funct3: int
    funct7: int
    description: str
    wgsl_implementation: str
    line_numbers: Tuple[int, int]


class WGSLPatternExtractor:
    """Extract instruction patterns from existing WGSL code"""

    def __init__(self, wgsl_file: str):
        with open(wgsl_file, 'r') as f:
            self.lines = f.readlines()
        self.patterns: List[ExtractedPattern] = []

    def extract_instruction_patterns(self):
        """Extract all instruction patterns from the WGSL file"""
        
        # Pattern to match: else if (opcode == 0xXXu && funct3 == 0xXu && funct7 == 0xXXu) {
        opcode_pattern = r'opcode == (0x[0-9a-f]+)u'
        funct3_pattern = r'funct3 == (0x[0-9a-f]+)u'
        funct7_pattern = r'funct7 == (0x[0-9a-f]+)u'
        
        for i, line in enumerate(self.lines):
            # Look for instruction decoding patterns
            if 'opcode == 0x' in line and 'else if' in line:
                
                # Extract opcode
                opcode_match = re.search(opcode_pattern, line)
                if not opcode_match:
                    continue
                opcode = int(opcode_match.group(1), 16)
                
                # Extract funct3 if present
                funct3 = None
                funct3_match = re.search(funct3_pattern, line)
                if funct3_match:
                    funct3 = int(funct3_match.group(1), 16)
                
                # Extract funct7 if present
                funct7 = None
                funct7_match = re.search(funct7_pattern, line)
                if funct7_match:
                    funct7 = int(funct7_match.group(1), 16)
                
                # Find the implementation (next few lines until closing brace)
                impl_start = i + 1
                impl_lines = []
                brace_count = 1
                
                for j in range(impl_start, len(self.lines)):
                    impl_lines.append(self.lines[j])
                    brace_count += self.lines[j].count('{') - self.lines[j].count('}')
                    if brace_count == 0:
                        impl_end = j
                        break
                
                # Try to identify the instruction from comments
                instruction_name = "UNKNOWN"
                description = ""
                
                for impl_line in impl_lines:
                    if '//' in impl_line:
                        comment = impl_line.strip()
                        if '//' in comment and any(cmd in comment.lower() for cmd in ['add', 'sub', 'mul', 'div', 'load', 'store', 'csr']):
                            description = comment.split('//')[1].strip().lower()
                            # Extract instruction name
                            if 'mul' in description:
                                instruction_name = description.upper().replace(' ', '_')
                            elif 'add' in description and 'sub' not in description:
                                instruction_name = "ADD" if funct7 == 0 else "SUB"
                            elif 'sub' in description:
                                instruction_name = "SUB"
                
                wgsl_impl = ''.join(impl_lines).strip()
                
                pattern = ExtractedPattern(
                    instruction_name=instruction_name,
                    opcode=opcode,
                    opcode_match=line.strip(),
                    funct3=funct3,
                    funct7=funct7,
                    description=description,
                    wgsl_implementation=wgsl_impl,
                    line_numbers=(i, impl_end)
                )
                
                self.patterns.append(pattern)

    def generate_dsl_definitions(self) -> str:
        """Generate Python DSL definitions from extracted patterns"""
        output = ["# Auto-generated DSL definitions from SPATIAL_RV64I.wgsl"]
        output.append("# Generated by WGSL Pattern Extractor")
        output.append("")
        
        for pattern in self.patterns:
            output.append(f"# {pattern.description}")
            output.append(f"# Lines {pattern.line_numbers[0]}-{pattern.line_numbers[1]}")
            
            if pattern.funct7 is not None:
                output.append(f'dsl.add_instruction(InstructionDefinition(')
                output.append(f'    name="{pattern.instruction_name}",')
                output.append(f'    opcode=0x{pattern.opcode:02x},')
                output.append(f'    format=OpcodeFormat.R_TYPE,')
                if pattern.funct3 is not None:
                    output.append(f'    funct3=0x{pattern.funct3:x},')
                output.append(f'    funct7=0x{pattern.funct7:02x},')
                output.append(f'    description="{pattern.description}",')
                output.append(f'    implementation="// Auto-extracted from WGSL lines {pattern.line_numbers[0]}"')
                output.append('))')
            else:
                output.append(f'dsl.add_instruction(InstructionDefinition(')
                output.append(f'    name="{pattern.instruction_name}",')
                output.append(f'    opcode=0x{pattern.opcode:02x},')
                output.append(f'    format=OpcodeFormat.I_TYPE,')  # Default
                if pattern.funct3 is not None:
                    output.append(f'    funct3=0x{pattern.funct3:x},')
                output.append(f'    description="{pattern.description}",')
                output.append(f'    implementation="// Auto-extracted from WGSL lines {pattern.line_numbers[0]}"')
                output.append('))')
            
            output.append("")
        
        return '\n'.join(output)

    def generate_statistics(self) -> str:
        """Generate statistics about extracted patterns"""
        stats = ["Pattern Extraction Statistics", "=" * 50]
        stats.append(f"Total patterns found: {len(self.patterns)}")
        
        # Count by opcode
        opcode_counts: Dict[int, int] = {}
        for pattern in self.patterns:
            opcode_counts[pattern.opcode] = opcode_counts.get(pattern.opcode, 0) + 1
        
        stats.append("\nInstructions by opcode:")
        for opcode, count in sorted(opcode_counts.items()):
            stats.append(f"  Opcode 0x{opcode:02x}: {count} instructions")
        
        # Count by instruction type
        instruction_types: Dict[str, int] = {}
        for pattern in self.patterns:
            instr_type = pattern.instruction_name[:3] if len(pattern.instruction_name) >= 3 else "UNK"
            instruction_types[instr_type] = instruction_types.get(instr_type, 0) + 1
        
        stats.append("\nInstructions by type:")
        for instr_type, count in sorted(instruction_types.items()):
            stats.append(f"  {instr_type}: {count} instructions")
        
        return '\n'.join(stats)


def main():
    # Extract patterns from existing WGSL
    extractor = WGSLPatternExtractor('SPATIAL_RV64I.wgsl')
    extractor.extract_instruction_patterns()
    
    print("=" * 70)
    print("WGSL PATTERN EXTRACTION ANALYSIS")
    print("=" * 70)
    print()
    
    # Show statistics
    print(extractor.generate_statistics())
    print()
    
    # Show sample patterns
    print("Sample Extracted Patterns:")
    print("-" * 70)
    
    for i, pattern in enumerate(extractor.patterns[:5]):  # Show first 5
        print(f"\n{i+1}. {pattern.instruction_name}")
        funct3_str = f"0x{pattern.funct3:x}" if pattern.funct3 else "None"
        funct7_str = f"0x{pattern.funct7:02x}" if pattern.funct7 else "None"
        print(f"   Opcode: 0x{pattern.opcode:02x}, funct3: {funct3_str}, funct7: {funct7_str}")
        print(f"   Description: {pattern.description}")
        print(f"   Lines: {pattern.line_numbers[0]}-{pattern.line_numbers[1]}")
        print(f"   WGSL snippet: {pattern.wgsl_implementation[:100]}...")
    
    # Generate DSL definitions
    print("\n" + "=" * 70)
    print("GENERATED DSL DEFINITIONS (Sample)")
    print("=" * 70)
    
    dsl_output = extractor.generate_dsl_definitions()
    print(dsl_output[:1000] + "...")
    
    # Save full output
    with open('extracted_dsl_definitions.py', 'w') as f:
        f.write(dsl_output)
    
    print(f"\nFull DSL definitions saved to: extracted_dsl_definitions.py")


if __name__ == "__main__":
    main()