# Auto-generated DSL definitions from SPATIAL_RV64I.wgsl
# Generated by WGSL Pattern Extractor

# csrrw/csrrwi always write; the set/clear variants skip the write when the
# Lines 1439-1884
dsl.add_instruction(InstructionDefinition(
    name="EMULATOR_ALSO_MAPS_TO_STATE.MTIMECMP)._IF_THE_NATIVE_HANDLER_ARMED",
    opcode=0x63,
    format=OpcodeFormat.I_TYPE,
    description="csrrw/csrrwi always write; the set/clear variants skip the write when the",
    implementation="// Auto-extracted from WGSL lines 1439"
))

# csrrw/csrrwi always write; the set/clear variants skip the write when the
# Lines 1463-1884
dsl.add_instruction(InstructionDefinition(
    name="EMULATOR_ALSO_MAPS_TO_STATE.MTIMECMP)._IF_THE_NATIVE_HANDLER_ARMED",
    opcode=0x03,
    format=OpcodeFormat.I_TYPE,
    description="csrrw/csrrwi always write; the set/clear variants skip the write when the",
    implementation="// Auto-extracted from WGSL lines 1463"
))

# csrrw/csrrwi always write; the set/clear variants skip the write when the
# Lines 1528-1884
dsl.add_instruction(InstructionDefinition(
    name="EMULATOR_ALSO_MAPS_TO_STATE.MTIMECMP)._IF_THE_NATIVE_HANDLER_ARMED",
    opcode=0x23,
    format=OpcodeFormat.I_TYPE,
    description="csrrw/csrrwi always write; the set/clear variants skip the write when the",
    implementation="// Auto-extracted from WGSL lines 1528"
))

# csrrw/csrrwi always write; the set/clear variants skip the write when the
# Lines 1566-1884
dsl.add_instruction(InstructionDefinition(
    name="EMULATOR_ALSO_MAPS_TO_STATE.MTIMECMP)._IF_THE_NATIVE_HANDLER_ARMED",
    opcode=0x33,
    format=OpcodeFormat.R_TYPE,
    funct7=0x01,
    description="csrrw/csrrwi always write; the set/clear variants skip the write when the",
    implementation="// Auto-extracted from WGSL lines 1566"
))

# csrrw/csrrwi always write; the set/clear variants skip the write when the
# Lines 1590-1884
dsl.add_instruction(InstructionDefinition(
    name="EMULATOR_ALSO_MAPS_TO_STATE.MTIMECMP)._IF_THE_NATIVE_HANDLER_ARMED",
    opcode=0x33,
    format=OpcodeFormat.I_TYPE,
    description="csrrw/csrrwi always write; the set/clear variants skip the write when the",
    implementation="// Auto-extracted from WGSL lines 1590"
))

# csrrw/csrrwi always write; the set/clear variants skip the write when the
# Lines 1754-1884
dsl.add_instruction(InstructionDefinition(
    name="EMULATOR_ALSO_MAPS_TO_STATE.MTIMECMP)._IF_THE_NATIVE_HANDLER_ARMED",
    opcode=0x37,
    format=OpcodeFormat.I_TYPE,
    description="csrrw/csrrwi always write; the set/clear variants skip the write when the",
    implementation="// Auto-extracted from WGSL lines 1754"
))

# csrrw/csrrwi always write; the set/clear variants skip the write when the
# Lines 1759-1884
dsl.add_instruction(InstructionDefinition(
    name="EMULATOR_ALSO_MAPS_TO_STATE.MTIMECMP)._IF_THE_NATIVE_HANDLER_ARMED",
    opcode=0x17,
    format=OpcodeFormat.I_TYPE,
    description="csrrw/csrrwi always write; the set/clear variants skip the write when the",
    implementation="// Auto-extracted from WGSL lines 1759"
))

# csrrw/csrrwi always write; the set/clear variants skip the write when the
# Lines 1764-1884
dsl.add_instruction(InstructionDefinition(
    name="EMULATOR_ALSO_MAPS_TO_STATE.MTIMECMP)._IF_THE_NATIVE_HANDLER_ARMED",
    opcode=0x67,
    format=OpcodeFormat.I_TYPE,
    description="csrrw/csrrwi always write; the set/clear variants skip the write when the",
    implementation="// Auto-extracted from WGSL lines 1764"
))

# csrrw/csrrwi always write; the set/clear variants skip the write when the
# Lines 1783-1884
dsl.add_instruction(InstructionDefinition(
    name="EMULATOR_ALSO_MAPS_TO_STATE.MTIMECMP)._IF_THE_NATIVE_HANDLER_ARMED",
    opcode=0x73,
    format=OpcodeFormat.I_TYPE,
    description="csrrw/csrrwi always write; the set/clear variants skip the write when the",
    implementation="// Auto-extracted from WGSL lines 1783"
))
