"""tools/pyshader_divergence.py — PS010b rung: divergence-cost sweep,
host-side (the sequential baseline the future GPU-SIMD leg must beat).

SKELETON (skeleton-driven-development): interfaces LOCKED, bodies
stubbed. Spec: GPU_CPU_EMULATOR_ROADMAP.md:233-310 (the non-vacuity
requirement — divergence cost is a MEASURED OUTPUT, reported as a sweep
at realistic scale, "numbers in the receipt, not prose"); builder
contract: .builder_queue/brief_ps010b_divergence_sweep.md.
The builder populates ONE stub per run; each stub's gate clause lives in
the brief's step table. If a signature below looks wrong, file
REPAIR_PENDING_ps010b_<topic>.md — do NOT edit this file's interfaces.

Model: N harts, one instruction per hart per round (roadmap :225-228 —
"inter-hart state visible only at boundaries"); here the programs are
dmem-free, so the thing under test is the ROUND SCHEDULER's lane
occupancy, not memory ordering (the mailbox brief adjudicated that).

Metric (roadmap :250-252): efficiency = useful_transitions /
live_hart_slots. A live_hart_slot = one round in which a hart was still
live — halted harts keep occupying lanes in real warp hardware, which
is exactly the cost being measured. (What this does NOT measure: warp
execution efficiency from profiling counters — that needs the GPU leg,
a later rung.)

Divergence legs (roadmap :250-252 + research sharpening :293-310):
  - uniform: every hart runs the same short program (0% divergence).
  - static mix: a population fraction runs a short program, the rest a
    long one (divergence by program mix).
  - adversarial: every hart runs the SAME program but a per-hart
    register splits the population mid-run — "half take one branch,
    half the other" (the honest worst case; same program text, so the
    divergence is not visible in any static artifact).

Three honest outcomes (roadmap :270-279, named in advance so neither
gets quietly reframed as failure): tolerable cost (per-invocation-hart
route validated); severe cost (GeoASM needs scheduling discipline —
warp-coherent dispatch — before Path B is GPU-viable); or bad at low N
but tolerable at realistic scale. The CURVE decides, not any single
cell — sweep N ∈ {2, 8, 64, 4096, 65536}.

What the stubs return is deliberate: they raise NotImplementedError
(silence would be dangerous); the pins are asserted by the behavioral
tests.
"""
from __future__ import annotations

import time
from typing import Dict, List, Optional

from tools.rv32i_asm import assemble
from tools.pyshader_ctl import ControlHalt, execute_ctl
from tools.pyshader_fde import REG_N, State, execute_one, fetch
from tools.pyshader_rvdecode import decode_ref

__all__ = [
    "LOW_PROG", "MIX_PROG_SHORT", "MIX_PROG_LONG", "DIVERGENT_PROG",
    "SWEEP_NS", "DivergenceCell", "sweep", "gate_divergence",
]

# ── locked program texts (words come from assemble(), NEVER hand-
#    encoding — tools/pyshader_hart.py:286-289 lesson) ──────────────────

# 5 transitions (probe-measured 2026-09-20, pre-brief).
LOW_PROG = """
        addi x1, x0, 2
loop:   addi x1, x1, -1
        bne  x1, x0, -4
        ebreak
"""

# 1 transition (ADDI only; EBREAK halts UNCOUNTED, PS008 convention).
MIX_PROG_SHORT = """
        addi x1, x0, 0
        ebreak
"""

# 17 transitions (probe-measured).
MIX_PROG_LONG = """
        addi x1, x0, 8
loop:   addi x1, x1, -1
        bne  x1, x0, -4
        ebreak
"""

# x5=4 (taken): 2 transitions; x5=0 (not-taken): 18 (probe-measured).
# The spin counts down with BLT-signed: a BNE-to-zero spins ~2^32
# because the u32 wraps past 0 (probe-measured hang) — hence BLT.
DIVERGENT_PROG = """
        bne  x5, x0, 12       # taken -> skip the spin loop (+3 insns)
        addi x1, x0, 8        # spin-loop counter
spin:   addi x1, x1, -1
        blt  x0, x1, -4       # while 0 < x1 (signed)
        ebreak
"""


def _words(asm_text: str) -> List[int]:
    b = assemble(asm_text)
    return [int.from_bytes(b[i:i + 4], "little")
            for i in range(0, len(b), 4)]


# Sweep scales (roadmap :275-279 — realistic scale before a verdict;
# 65536 = one full warp-width population at agent scale).
SWEEP_NS = (2, 8, 64, 4096, 65536)

# ── locked result shape ─────────────────────────────────────────────────


class DivergenceCell(Dict):
    """Per-(N, mix) sweep cell. Keys:
    n, mix, rounds, useful, slots, efficiency, wall_seconds,
    sampled_steps (per-hart transition counts for up to 2 harts)."""
    pass


# ── stubs (populate ONE per run; gate clauses in the brief) ─────────────


def sweep(prog_words: List[List[int]],
          x5_inits: Optional[List[int]] = None,
          max_rounds: int = 64) -> DivergenceCell:
    """Populate PS010b steps 1-3 (the gate clauses differentiate them;
    one function, three calling patterns). Drive N harts in rounds: each
    live hart executes ONE transition per round (STEPS_PER_ROUND=1, the
    locked mailbox convention — no coarse batching), against its OWN
    state; programs are dmem-free so harts are fully independent.

    prog_words: per-hart instruction images (len N). NOT mutated.
    x5_inits: optional per-hart x5 preload (the adversarial leg's
    register split). Default all zeros.

    Returns a DivergenceCell with:
      rounds        — the round in which the LAST hart halted
                      (1-indexed; EBREAK halts in, not after, a round).
      useful        — total transitions across all harts.
      slots         — sum over rounds of the number of LIVE harts
                      (halted harts still occupy lanes in warp
                      hardware; a hart that halts mid-sweep occupies a
                      slot in every round up to and including its halt).
      useful/slots  — efficiency (the metric; see module docstring).
      wall_seconds  — time.perf_counter around the round loop
                      (informational; never gated on).
      sampled_steps — [steps[0], steps[-1]] (first + last hart).
      mix           — caller-assigned label ("" from sweep; gate sets it).

    Budget: RuntimeError naming max_rounds if any hart is still live at
    exhaustion — never a silent partial result (PS010 step-3 lesson).
    """
    n = len(prog_words)
    if n == 0:
        raise ValueError("sweep: prog_words must contain at least one hart")
    if x5_inits is not None and len(x5_inits) != n:
        raise ValueError(
            f"sweep: x5_inits has {len(x5_inits)} entries for {n} harts")

    # Per-hart COPIES — the caller's program images are never mutated.
    imems = [list(p) for p in prog_words]
    states: List[State] = [{"pc": 0, "regs": [0] * REG_N} for _ in range(n)]
    if x5_inits is not None:
        for s, v in zip(states, x5_inits):
            s["regs"][5] = v & 0xFFFFFFFF

    halted = [False] * n
    steps = [0] * n
    t0 = time.perf_counter()

    for rnd in range(1, max_rounds + 1):
        for i in range(n):
            if halted[i]:
                continue
            d = decode_ref(fetch(states[i]["pc"], imems[i]))
            if d["fmt"] in ("R", "I") and d["opcode"] in (0x33, 0x13):
                states[i] = execute_one(states[i], imems[i])
            else:
                # control/memory layer (PS008); programs here are
                # dmem-free so no dmem is passed (the mailbox brief
                # adjudicated memory ordering — not under test).
                try:
                    states[i] = execute_ctl(states[i], d, None)
                except ControlHalt:
                    # EBREAK is the halt signal; UNCOUNTED per the PS008
                    # convention. The hart's slot count is its COUNTED
                    # transitions (brief step-2 arithmetic: "SHORT harts
                    # halt in round 1 and still occupy slots for the
                    # remaining 16 rounds" — slots == n * rounds).
                    halted[i] = True
                    continue
            steps[i] += 1
        if all(halted):
            wall = time.perf_counter() - t0
            rounds = max(steps)
            useful = sum(steps)
            slots = n * rounds  # every lane occupied through the last round
            return DivergenceCell(
                n=n, mix="", rounds=rounds,
                useful=useful, slots=slots,
                efficiency=useful / slots if slots else 0.0,
                wall_seconds=wall,
                sampled_steps=[steps[0], steps[-1]])

    live = n - sum(halted)
    raise RuntimeError(
        f"sweep: round budget {max_rounds} exhausted with {live} hart(s) "
        f"still live — budget exhaustion must be loud (PS010 step-3 lesson)")


def gate_divergence() -> Dict:
    """Populate PS010b step 4 — THE roadmap gate (:246-268 + :293-310).
    Build the pinned program images, run the sweep at every N in
    SWEEP_NS for each leg (uniform LOW_PROG; half-mixed SHORT/LONG;
    adversarial DIVERGENT_PROG with half x5=4 / half x5=0), and return
    a receipt dict (does NOT raise on pin mismatch — the receipt IS the
    gate artifact):

      ok            — False if any adjudication pin fails:
                      (a) uniform efficiency == 1.0 at every N;
                      (b) adversarial efficiency at N=8 == (4*2+4*18)/
                          (8*18) rounded to 4dp;
                      (c) monotone decay: efficiency(adversarial) <
                          efficiency(uniform) at every N;
                      (d) the N=65536 adversarial cell RAN and
                          completed (report its efficiency; no value
                          pinned — host scheduler != warp hardware).
      cells         — the 5*3 DivergenceCells (mix-labelled).
      pin_failures  — list of failed pin names (empty when ok).
      what_pass_does_not_prove — the honest boundary (no GPU leg, host
                      scheduler only, wall-clock informational).
    """
    low_words = _words(LOW_PROG)
    short_words = _words(MIX_PROG_SHORT)
    long_words = _words(MIX_PROG_LONG)
    div_words = _words(DIVERGENT_PROG)
    adv_x5 = [4, 0]  # alternating per-hart split (half taken / half not)

    cells: List[DivergenceCell] = []
    for n in SWEEP_NS:
        # (1) uniform: every hart runs the same short program.
        c = sweep([low_words] * n, max_rounds=64)
        c["mix"] = "uniform"
        cells.append(c)

        # (2) half-mixed: half the population SHORT (1 transition),
        # half LONG (17) — divergence by program mix.
        c = sweep([short_words] * (n // 2) + [long_words] * (n // 2),
                  max_rounds=64)
        c["mix"] = "half-mixed"
        cells.append(c)

        # (3) adversarial: same program text everywhere, per-hart x5
        # preload splits the population mid-run (register divergence).
        c = sweep([div_words] * n,
                  x5_inits=[adv_x5[i % 2] for i in range(n)],
                  max_rounds=64)
        c["mix"] = "adversarial"
        cells.append(c)

    by = {(c["n"], c["mix"]): c for c in cells}
    pin_failures: List[str] = []

    # (a) uniform efficiency == 1.0 at every N.
    for n in SWEEP_NS:
        if by[(n, "uniform")]["efficiency"] != 1.0:
            pin_failures.append(f"uniform-efficiency-at-N={n}")

    # (b) adversarial efficiency at N=8 == the row-3 pin (4dp).
    if round(by[(8, "adversarial")]["efficiency"], 4) != 0.5556:
        pin_failures.append("adversarial-efficiency-at-N=8")

    # (c) monotone decay: adversarial < uniform at every N.
    for n in SWEEP_NS:
        if not (by[(n, "adversarial")]["efficiency"]
                < by[(n, "uniform")]["efficiency"]):
            pin_failures.append(f"monotone-decay-at-N={n}")

    # (d) the N=65536 adversarial cell RAN and completed (value NOT
    # pinned — host scheduler != warp hardware; report only).
    adv_max = by[(65536, "adversarial")]
    if adv_max["rounds"] <= 0 or adv_max["useful"] <= 0:
        pin_failures.append("N=65536-adversarial-ran")

    return {
        "ok": not pin_failures,
        "cells": cells,
        "pin_failures": pin_failures,
        "what_pass_does_not_prove": (
            "No GPU leg: this is the HOST round scheduler only (the "
            "sequential baseline a future GPU-SIMD rung must beat or "
            "match). Efficiency is lane occupancy of a host loop, NOT "
            "warp-execution efficiency from profiling counters. "
            "wall_seconds is informational (machine-dependent) and "
            "never gated on. The N=65536 adversarial cell's efficiency "
            "is reported unpinned. The verdict language belongs to the "
            "curve (roadmap :270-279: tolerable / needs scheduling "
            "discipline / bad-at-low-N-tolerable-at-scale), decided "
            "from the sweep, not any single cell."),
    }
