"""tools/pyshader_hart.py — PS010 rung 1: two-hart mailbox, host-driven.

SKELETON (skeleton-driven-development): interfaces LOCKED, bodies
stubbed. Spec: GPU_CPU_EMULATOR_ROADMAP.md PS010 section (:221-334);
builder contract: .builder_queue/brief_ps010_two_hart_mailbox.md.
The builder populates ONE stub per run; each stub's gate clause lives in
the brief's step table. If a signature below looks wrong, file
REPAIR_PENDING_ps010_<topic>.md — do NOT edit this file's interfaces.

Model (the roadmap's "host-driven rounds" shape, per-hart execution via
the PS008 control layer — NO GPU legs in rung 1):

    hart A (writer) ─┐
                     ├─ each round: every live hart executes up to
    hart B (spinner)─┘  steps_per_round transitions against its OWN
                        double-buffered dmem copy, then hart buffers are
                        WRITE-MERGED in round order (not final-state).

Inter-hart state is visible only at round boundaries — an honest,
documented narrowing vs QEMU SMP interleaving (roadmap :225-228).
sync="single" runs both harts on ONE shared dmem with no per-round
copies: the deliberate race variant, used by the RED leg to prove the
sync recipe is load-bearing (roadmap gate :229-231).

Mailbox word layout (dmem, words): dmem[0] = flag+payload (A writes 1),
dmem[1] = A's pin record (7), dmem[2] = sentinel (123, never written).

Hand-computed pin (author, 2026-09-20 — re-derive before step 1 GREEN;
steps counted per the PS008 run_ctl_trace convention: EBREAK halts
WITHOUT counting as a transition):
A: 6 transitions (2 ADDI, SW, ADDI, SW, JAL — poison at insn 6 SKIPPED;
   EBREAK at insn 7 halts uncounted). Final A regs: x1=7, x9=1, x10=0,
   x31=0 (poison value 99 never lands).
B: 6 transitions. Rounds 1-2: ADDI, then LW sees flag=0 (A's round-3 SW
   becomes visible to B only at the round-4 boundary). Round 3: BEQ
   taken (back to insn 1). Round 4: LW AGAIN (pc=1), now sees flag=1.
   Round 5: BEQ not-taken, falls through. Round 6: ADDI x6 = 1+6 = 7.
   Round 7: EBREAK halts. Final B regs: x5=1, x6=7, x10=0.
   (steps_b was pinned 5 until RULING_ps010_steps_b_pin.md: the
   original trace dropped B's round-4 spin re-read of the LW.)
Rounds to completion: 7 (A's EBREAK lands in round 7; rounds = max over
   harts of the round in which the hart halted).
Final dmem: [1, 7, 123, 0, 0, 0, 0, 0].

What the stubs return is deliberate: run_two_hart raises
NotImplementedError (silence would be dangerous); the pins above are
asserted by the behavioral tests.
"""
from __future__ import annotations

import struct
from typing import Dict, List, Optional

from tools.rv32i_asm import assemble
from tools.pyshader_compiler import U32_MASK
from tools.pyshader_ctl import ControlHalt, execute_ctl
from tools.pyshader_fde import REG_N, execute_one, fetch
from tools.pyshader_rvdecode import decode_ref

__all__ = [
    "DMEM_WORDS", "STEPS_PER_ROUND", "MAILBOX_PROG_A", "MAILBOX_PROG_B",
    "DMEM0", "TwoHartResult", "run_two_hart", "gate_mailbox",
]

# ── locked constants ────────────────────────────────────────────────────

DMEM_WORDS = 8         # tiny data memory, words (sentinel lives at [2])
STEPS_PER_ROUND = 1    # one transition per hart per round (fine rounds:
                       # the mailbox must NOT depend on coarse batching)

# Hart A — writer: set flag+payload, record pin, skip poison, halt.
# Hand-computed: 6 transitions; JAL at 5 skips the poison ADDI at 6;
# x31 must stay 0.
MAILBOX_PROG_A = """
        addi x9, x0, 1       # 0: payload value
        addi x10, x0, 0      # 1: base byte address of dmem[0]
        sw   x9, 0(x10)      # 2: dmem[0] = 1  (flag SET + payload)
        addi x1, x0, 7       # 3: A's pin record
        sw   x1, 4(x10)      # 4: dmem[1] = 7
        jal  x0, 8           # 5: skip the poison (+2 insns)
        addi x31, x0, 99     # 6: POISON (must never execute)
        ebreak               # 7: halt
"""

# Hart B — spinner: spin on dmem[0]==0, then read payload and record.
# Hand-computed: 6 transitions (ADDI, LW, BEQ taken, LW re-read sees 1,
# BEQ not-taken, ADDI; EBREAK halts uncounted); BEQ at insn 2 with
# imm -4 bytes = back one insn to insn 1.
# (Word 2 was BNE until RULING_ps010_bne_spin_polarity.md — the spin
# timeline requires BEQ polarity; see that ruling + the RULED blocker.)
MAILBOX_PROG_B = """
        addi x10, x0, 0      # 0: base byte address
        lw   x5, 0(x10)      # 1: spin read (flag)
        beq  x5, x0, -4      # 2: flag==0 -> back to insn 1
        addi x6, x5, 6       # 3: x6 = payload + 6 = 7
        ebreak               # 4: halt
"""

# Initial dmem: sentinel 123 at word 2 must survive BOTH legs untouched.
DMEM0 = [0, 0, 123, 0, 0, 0, 0, 0]

# ── locked result shape ─────────────────────────────────────────────────


class TwoHartResult(Dict):
    """Receipt dict. Keys (all present when completed):
    completed, rounds, steps_a, steps_b, dmem, regs_a, regs_b,
    writes_a, writes_b, sync. (gate_mailbox adds single_buffer_ok.)"""
    pass


# ── stubs (populate ONE per run; gate clauses in the brief) ─────────────


def run_two_hart(prog_a: List[int], prog_b: List[int],
                 dmem0: Optional[List[int]] = None,
                 sync: str = "double",
                 order: str = "ab",
                 steps_per_round: int = STEPS_PER_ROUND,
                 max_rounds: int = 256) -> TwoHartResult:
    """Populate PS010 step 1 (steps 2-3 add the merge guard + the loud
    budget). Drive both harts in rounds of steps_per_round transitions.

    sync="double": each hart executes against its OWN dmem copy; after
    every round, hart dmems are WRITE-MERGED into a shared view in round
    order and the shared view is copied back (per-hart visibility of
    foreign writes begins next round). Receipt records each hart's write
    log [(round, word_index, value), ...] — the step-2 merge test
    adjudicates ORDER on these.

    sync="single": both harts execute against ONE shared dmem list, no
    per-round copies — the deliberate race variant for the RED leg.
    NOTE (design, 2026-09-20): at steps_per_round=1 with a fixed hart
    order, single-buffer execution is a BENIGN interleaving for a
    monotonic mailbox (every interleaving respects the data dependency)
    — the step-4 RED leg therefore demonstrates the hazard with a
    crafted consistency pair (flag + payload written by A in SEQUENCE;
    B reads BOTH inside one coarse round: single-buffer lets B observe
    a TORN one-new/one-old state, double-buffer only ever all-old or
    all-new) at steps_per_round >= 2. The gate leg itself stays at the
    locked STEPS_PER_ROUND=1, order="ab".

    order: per-round execution order of the harts ("ab" = A then B).
    steps_per_round: transitions each LIVE hart gets per round.

    Budget: if max_rounds is exhausted with a hart still live (not
    halted), raise RuntimeError naming the round budget — never return
    a silent completed=False (step 3 gate).
    """
    if sync not in ("double", "single"):
        raise ValueError(f"run_two_hart: unknown sync {sync!r}")
    if order not in ("ab", "ba"):
        raise ValueError(f"run_two_hart: unknown order {order!r}")
    if steps_per_round < 1:
        raise ValueError("run_two_hart: steps_per_round must be >= 1")

    dmem0 = list(DMEM0 if dmem0 is None else dmem0)

    def _new_state():
        return {"pc": 0, "regs": [0] * REG_N}

    def _drive_one(hart: str, imem: List[int], dmem: List[int],
                   state: Dict):
        """Run up to steps_per_round transitions for one hart against
        its OWN dmem view. Returns (state, halted, steps, writes)."""
        writes: List[tuple] = []
        steps = 0
        while steps < steps_per_round:
            d = decode_ref(fetch(state["pc"], imem))
            if d["fmt"] in ("R", "I") and d["opcode"] in (0x33, 0x13):
                state = execute_one(state, imem)
                steps += 1
            else:
                # memory/control layer (PS008): intercept SW to log the
                # write against the ROUND it happens in.
                if d["fmt"] == "S" and d.get("funct3") == 2:
                    regs = state["regs"]
                    addr = (regs[d["rs1"]] + d["imm"]) & U32_MASK
                    if addr % 4 == 0 and 0 <= addr // 4 < len(dmem):
                        writes.append((addr // 4, regs[d["rs2"]]))
                try:
                    state = execute_ctl(state, d, dmem)
                except ControlHalt:
                    return state, True, steps, writes
                steps += 1
        return state, False, steps, writes

    # ── hart setup ────────────────────────────────────────────────────
    imems = {"a": list(prog_a), "b": list(prog_b)}
    states = {"a": _new_state(), "b": _new_state()}
    halted = {"a": False, "b": False}
    total_steps = {"a": 0, "b": 0}
    all_writes = {"a": [], "b": []}
    halt_round = {"a": 0, "b": 0}

    if sync == "double":
        shared = list(dmem0)
        views = {"a": list(shared), "b": list(shared)}
        for rnd in range(1, max_rounds + 1):
            for h in ([ "a", "b" ] if order == "ab" else [ "b", "a" ]):
                if halted[h]:
                    continue
                states[h], halted[h], got, wr = _drive_one(
                    h, imems[h], views[h], states[h])
                total_steps[h] += got
                for (w, v) in wr:
                    all_writes[h].append((rnd, w, v))
                    shared[w] = v
                if halted[h]:
                    halt_round[h] = rnd
                # refresh this hart's view so its own writes are visible
                # to itself next transition within the merge discipline
                views[h] = list(shared)
            # round boundary: write-merge (round order, not final-state)
            # then copy the shared view back to every live hart
            for h in ("a", "b"):
                if not halted[h]:
                    views[h] = list(shared)
            if all(halted.values()):
                return TwoHartResult(
                    completed=True,
                    rounds=max(halt_round.values()),
                    steps_a=total_steps["a"],
                    steps_b=total_steps["b"],
                    dmem=list(shared),
                    regs_a=list(states["a"]["regs"]),
                    regs_b=list(states["b"]["regs"]),
                    writes_a=list(all_writes["a"]),
                    writes_b=list(all_writes["b"]),
                    sync=sync,
                )
        raise RuntimeError(
            f"run_two_hart: round budget {max_rounds} exhausted with "
            f"hart(s) still live (a halted={halted['a']}, "
            f"b halted={halted['b']}) — livelock/deadlock must be loud")

    if sync == "single":
        # The deliberate race variant (roadmap gate RED leg): ONE shared
        # dmem list, no per-round copies. Order is FIXED (order param),
        # so this is a deterministic adversarial interleaving, not a
        # scheduler race — the divergence it exhibits is exactly the
        # visibility hazard the double-buffer discipline removes.
        shared = list(dmem0)
        for rnd in range(1, max_rounds + 1):
            for h in ([ "a", "b" ] if order == "ab" else [ "b", "a" ]):
                if halted[h]:
                    continue
                states[h], halted[h], got, wr = _drive_one(
                    h, imems[h], shared, states[h])
                total_steps[h] += got
                for (w, v) in wr:
                    all_writes[h].append((rnd, w, v))
                if halted[h]:
                    halt_round[h] = rnd
            if all(halted.values()):
                return TwoHartResult(
                    completed=True,
                    rounds=max(halt_round.values()),
                    steps_a=total_steps["a"],
                    steps_b=total_steps["b"],
                    dmem=list(shared),
                    regs_a=list(states["a"]["regs"]),
                    regs_b=list(states["b"]["regs"]),
                    writes_a=list(all_writes["a"]),
                    writes_b=list(all_writes["b"]),
                    sync=sync,
                )
        raise RuntimeError(
            f"run_two_hart: round budget {max_rounds} exhausted with "
            f"hart(s) still live (a halted={halted['a']}, "
            f"b halted={halted['b']}) — livelock/deadlock must be loud")

    raise AssertionError("run_two_hart: unreachable sync dispatch")


def gate_mailbox() -> Dict:
    """Populate PS010 step 4 — THE roadmap gate (:229-231). Build the
    pinned mailbox images (assemble(MAILBOX_PROG_A/B)), run the
    double-buffer gate leg and the single-buffer RED leg on the SAME
    program, and adjudicate against the hand-computed pin (module
    docstring: rounds==7, steps_a==6, steps_b==6, dmem [1,7,123,0,...],
    A x1=7/x9=1/x31=0, B x5=1/x6=7). Returns a receipt dict; ok=False on
    any pin mismatch (it does NOT raise on mismatch — the receipt IS the
    gate artifact). single_buffer_ok is False when the single-buffer leg
    demonstrably diverges from the pin (torn read / order dependence) —
    that False is the REQUIRED RED evidence that the double-buffer
    recipe is load-bearing.
    """
    wa = list(struct.unpack("<%dI" % (len(assemble(MAILBOX_PROG_A)) // 4),
                            assemble(MAILBOX_PROG_A)))
    wb = list(struct.unpack("<%dI" % (len(assemble(MAILBOX_PROG_B)) // 4),
                            assemble(MAILBOX_PROG_B)))

    d = run_two_hart(wa, wb, list(DMEM0), sync="double")
    s = run_two_hart(wa, wb, list(DMEM0), sync="single")

    # ── RED leg: crafted consistency pair (run_two_hart docstring NOTE,
    # measured in probe_ps010_torn_pair.py, 2026-09-20). At the LOCKED
    # default (STEPS_PER_ROUND=1, order="ab") the mailbox interleaving is
    # benign — the docstring says so and the probe confirms single==double
    # trace-wise. The hazard needs A writing flag+payload IN SEQUENCE and
    # B reading BOTH inside one coarse round (steps_per_round=2):
    #   single: B's LW pair lands mid-round after A's FIRST SW only ->
    #           TORN state (x5=1 flag-new, x6=0 payload-old)
    #   double: B only ever sees all-old or all-new (x5=0, x6=0 here)
    CONSISTENCY_PROG_A = [
        0x00100493,  # 0: addi x9, x0, 1   (payload value)
        0x00902023,  # 1: sw   x9, 0(x0)   -> dmem[0] = 1 (flag+payload)
        0x00700513,  # 2: addi x10, x0, 7  (pin)
        0x00A02223,  # 3: sw   x10, 4(x0)  -> dmem[1] = 7
        0x00100073,  # 4: ebreak
    ]
    CONSISTENCY_PROG_B = [
        0x0000A283,  # 0: lw x5, 0(x0)   (flag)
        0x00402303,  # 1: lw x6, 4(x0)   (payload) [assembler-verified]
        0x00100073,  # 2: ebreak
    ]
    torn_s = run_two_hart(CONSISTENCY_PROG_A, CONSISTENCY_PROG_B,
                          list(DMEM0), sync="single", steps_per_round=2)
    torn_d = run_two_hart(CONSISTENCY_PROG_A, CONSISTENCY_PROG_B,
                          list(DMEM0), sync="double", steps_per_round=2)
    torn_s_seen = (torn_s["regs_b"][5], torn_s["regs_b"][6])
    torn_d_seen = (torn_d["regs_b"][5], torn_d["regs_b"][6])
    torn = torn_s_seen != torn_d_seen and torn_d_seen == (0, 0) \
        and torn_s_seen[0] == 1 and torn_s_seen[1] == 0
    single_divergence = [] if torn else [
        f"single: crafted-pair leg did NOT demonstrate the torn state "
        f"(single saw {torn_s_seen}, double saw {torn_d_seen})"]

    # hand-computed pin (module docstring; steps_b==6 per
    # RULING_ps010_steps_b_pin.md)
    double_pin = {
        "completed": True,
        "rounds": 7,
        "steps_a": 6,
        "steps_b": 6,
        "dmem": [1, 7, 123, 0, 0, 0, 0, 0],
    }
    double_divergence = [k for k, v in double_pin.items()
                         if d.get(k) != v]
    ra = d.get("regs_a", [0] * REG_N)
    rb = d.get("regs_b", [0] * REG_N)
    if (ra[1], ra[9], ra[10], ra[31]) != (7, 1, 0, 0):
        double_divergence.append("regs_a")
    if (rb[5], rb[6]) != (1, 7):
        double_divergence.append("regs_b")

    double_ok = not double_divergence
    # single_buffer_ok is False when the hazard leg DEMONSTRATED the race
    # (required RED evidence) — a benign single leg would mean the RED leg
    # failed to fire.
    single_buffer_ok = not torn

    return {
        "ok": double_ok,
        "double_ok": double_ok,
        "double_divergence": double_divergence,
        "double": d,
        "single_buffer_ok": single_buffer_ok,
        "single_divergence": single_divergence,
        "single": s,
        "torn_pair": {
            "single_seen": list(torn_s_seen),
            "double_seen": list(torn_d_seen),
            "dmem_single": torn_s["dmem"],
            "dmem_double": torn_d["dmem"],
        },
        "what_pass_does_not_prove": [
            "no GPU leg (host correctness first, per the brief)",
            "N=2 harts only",
            "no divergence-cost measurement (roadmap :246-268 leg)",
            "the single-buffer hazard is demonstrated on the crafted "
            "consistency pair at steps_per_round=2 (per the run_two_hart "
            "docstring NOTE); at the locked STEPS_PER_ROUND=1 the "
            "mailbox's single-buffer interleaving is benign and matches "
            "the double-buffer trace (probe_ps010_single_race.py)",
            "single-buffer divergence measured under FIXED order='ab' "
            "(deterministic interleaving), not a scheduler race",
        ],
    }
