"""tools/pyshader_fde_gpu.py — PS009a: GPU-resident single-hart FDE loop.

RULING_ps009 (e839cab7, "MEASURE-ONLY GO"): 009a builds what the
roadmap's PS009 text assumed existed — a GPU-resident FDE loop. The
shader internally iterates a decoded-instruction buffer (batch = N
straight-line instructions per dispatch, snapshotting each committed
state into a trace ring); the host re-dispatches on taken branches /
halt. Gate: trace-diff of the FIB workload AND a >1k-insn
straight-line program vs the Python FDE (tools.pyshader_fde.run_fde)
AND the pixel CPU (SpatialRV32ICore) — 100% trace match. NO
performance claim, NO fork arithmetic: this file is the correctness
rung only; batched-N measurement is 009b (probe_ps009_baseline_rv32i
one_rep discipline) and its receipt is Jericho's [J-DECISION], not
this module's output.

Seam design (RULING_ps009 RED-first clause, option 2 — "the batch loop
lives in hand-written WGSL wrapping the generated decode table"): the
hand-written loop/decode header below embeds the GENERATED step_r /
step_i WGSL bodies extracted via tools.pyshader_rvexec._alu_body_wgsl
(the PS006 body-extraction trick). The generated emitter itself is NOT
loosened: _assert_ps001_shapes still caps at 2 predecessors — the
2-predecessor guard is untouched; the hand-written wrapper is the
named new shape.

Honest boundaries (mirroring pyshader_wgsl / pyshader_rvexec):
    - Instruction subset = the PS006/PS007 executor: R-type (0x33,
      ALU funct3 0/1/4/5/6/7), ALU-Imm (0x13), BNE only (0x63,
      funct3=1). Anything else sets stop_reason=BAD_OPCODE (3) and the
      loop HALTS at the faulting instruction — it does not fabricate
      progress.
    - Branches: EVERY taken branch ends the dispatch (host
      re-dispatches), so a batch is by construction straight-line.
    - pc counts INSTRUCTION INDICES (not bytes), matching
      tools.pyshader_fde. SPEC branch semantics: target = pc + imm//4
      (RULING_ps008_branch_convention).
    - Fetch past the end sets stop_reason=IMEM_OOB (2); the faulting
      fetch does NOT commit a state.
    - x0-write suppression is shader-side (rd==0 writes discarded),
      closing the PS007 step-4 boundary inside the GPU loop itself.
    - imem longer than MAX_IMEM_WORDS is rejected host-side (packing
      would silently truncate); a trace longer than TRACE_CAP states
      stops the loop with TRACE_FULL (4) rather than truncating.
    - No performance claim anywhere in this module: dispatch counts
      and buffer sizes are recorded for 009b's design, but the
      measurement legs live in the probe, same-process, per the
      ruling's same-process pairing clause.
"""
from __future__ import annotations

from typing import Dict, List, Optional

from tools.pyshader_fde import State, load_program

__all__ = [
    "REG_N", "PC_OFF", "RUNNING_OFF", "STOP_OFF", "NINSN_OFF",
    "TRACEN_OFF", "PREFIX_WORDS", "IMEM_BASE", "MAX_IMEM_WORDS",
    "TRACE_BASE", "TRACE_CAP", "TRACE_STRIDE", "ARRAY_WORDS",
    "STOP_HALT", "STOP_MAX_STEPS", "STOP_IMEM_OOB", "STOP_BAD_OPCODE",
    "STOP_TRACE_FULL", "run_fde_gpu",
]

# ── storage buffer layout (u32 words) ──────────────────────────────────
REG_N = 32             # [0..31]     registers
PC_OFF = 32            # [32]        instruction index
RUNNING_OFF = 33       # [33]        1 while the guest may run
STOP_OFF = 34          # [34]        stop reason (0 while running)
NINSN_OFF = 35         # [35]        imem length in instructions
TRACEN_OFF = 36        # [36]        states written to the trace ring
PREFIX_WORDS = 37
IMEM_BASE = PREFIX_WORDS
MAX_IMEM_WORDS = 2048
TRACE_BASE = IMEM_BASE + MAX_IMEM_WORDS
TRACE_STRIDE = 1 + REG_N          # pc + 32 regs per state
TRACE_CAP = 2048                  # max retained states per run
ARRAY_WORDS = TRACE_BASE + TRACE_CAP * TRACE_STRIDE

STOP_HALT = 0          # unused by the shader (host reserved)
STOP_MAX_STEPS = 1     # host: max_steps reached, guest still runnable
STOP_IMEM_OOB = 2      # shader: fetch outside [0, ninsn)
STOP_BAD_OPCODE = 3    # shader: opcode/fmt outside the executor subset
STOP_TRACE_FULL = 4    # shader: trace ring exhausted (host config error)

_SHADER_HEADER = """// generated by tools/pyshader_fde_gpu.py — PS009a FDE loop
@group(0) @binding(0) var<storage, read_write> buf: array<u32, %(ARRAY_WORDS)u>;

// ── GENERATED step_r body (tools.pyshader_rvexec.STEP_R_SRC via
//    _alu_body_wgsl — the PS006 extraction, unmodified). Params are
//    named r1..r4 (funct3, funct7, rs1v, rs2v) exactly as the PS006
//    regfile driver names them; temps r5..r25 are the emitter's
//    statement-scoped locals, declared here as in _REGFILE_SHADER. ──
fn step_r(r1: u32, r2: u32, r3: u32, r4: u32) -> u32 {
    var r0: u32 = 0u;
%(STEP_R_DECLS)s
%(STEP_R_BODY)s
}

// ── GENERATED step_i body (tools.pyshader_rvexec.STEP_I_SRC) ──
fn step_i(r1: u32, r2: u32, r3: u32, r4: u32) -> u32 {
    var r0: u32 = 0u;
%(STEP_I_DECLS)s
%(STEP_I_BODY)s
}

@compute @workgroup_size(1, 1, 1)
fn main() {
    let ninsn = buf[%(NINSN_OFF)u];
    var pc = buf[%(PC_OFF)u];
    var s: u32 = 0u;
    loop {
        if (s >= %(BATCH)u) { break; }
        if (pc >= ninsn) {
            buf[%(STOP_OFF)u] = %(STOP_IMEM_OOB)u;
            buf[%(RUNNING_OFF)u] = 0u;
            buf[%(PC_OFF)u] = pc;
            return;
        }
        var word: u32 = buf[%(IMEM_BASE)u + pc];
        let opcode = word & 127u;
        let rd = (word >> 7u) & 31u;
        let funct3 = (word >> 12u) & 7u;
        let rs1 = (word >> 15u) & 31u;
        let rs2 = (word >> 20u) & 31u;
        let funct7 = (word >> 25u) & 127u;
        if (opcode == 99u) {
            // B-type: BNE only (funct3==1). imm_b raw bits, sign-extended.
            let imm = ((word >> 31u) & 1u) * 4096u
                    + ((word >> 7u) & 1u) * 2048u
                    + ((word >> 25u) & 63u) * 32u
                    + ((word >> 8u) & 15u) * 2u;
            let signed_imm = i32(imm ^ 4096u) - 4096;
            if (funct3 != 1u) {
                buf[%(STOP_OFF)u] = %(STOP_BAD_OPCODE)u;
                buf[%(RUNNING_OFF)u] = 0u;
                buf[%(PC_OFF)u] = pc;
                return;
            }
            if (buf[rs1] != buf[rs2]) {
                // SPEC semantics: target = pc + imm//4 (no +1);
                // a taken branch ENDS the batch — host re-dispatches.
                let target_u = (pc * 4u) + u32(signed_imm);
                pc = target_u / 4u;
                // snapshot the post-branch state (branches commit a
                // state like every other instruction; regs unchanged)
                let tb = %(TRACE_BASE)u + buf[%(TRACEN_OFF)u] * %(TRACE_STRIDE)u;
                buf[tb] = pc;
                var tj: u32 = 0u;
                loop {
                    if (tj >= 32u) { break; }
                    buf[tb + 1u + tj] = buf[tj];
                    tj = tj + 1u;
                }
                buf[%(TRACEN_OFF)u] = buf[%(TRACEN_OFF)u] + 1u;
                buf[%(PC_OFF)u] = pc;
                return;
            }
            pc = pc + 1u;
            s = s + 1u;
        } else if (opcode == 51u) {
            let result = step_r(funct3, funct7, buf[rs1], buf[rs2]);
            if (rd != 0u) { buf[rd] = result; }   // x0 hardwired
            pc = pc + 1u;
            s = s + 1u;
        } else if (opcode == 19u) {
            let imm_i = (word >> 20u) & 4095u;
            let simm = i32(imm_i ^ 2048u) - 2048;
            let result = step_i(funct3, funct7, buf[rs1], u32(simm));
            if (rd != 0u) { buf[rd] = result; }   // x0 hardwired
            pc = pc + 1u;
            s = s + 1u;
        } else {
            buf[%(STOP_OFF)u] = %(STOP_BAD_OPCODE)u;
            buf[%(RUNNING_OFF)u] = 0u;
            buf[%(PC_OFF)u] = pc;
            return;
        }
        // snapshot the committed state into the trace ring
        let ti = buf[%(TRACEN_OFF)u];
        if (ti >= %(TRACE_CAP)u) {
            buf[%(STOP_OFF)u] = %(STOP_TRACE_FULL)u;
            buf[%(RUNNING_OFF)u] = 0u;
            buf[%(PC_OFF)u] = pc;
            return;
        }
        let base = %(TRACE_BASE)u + ti * %(TRACE_STRIDE)u;
        buf[base] = pc;
        var j: u32 = 0u;
        loop {
            if (j >= 32u) { break; }
            buf[base + 1u + j] = buf[j];
            j = j + 1u;
        }
        buf[%(TRACEN_OFF)u] = ti + 1u;
    }
    buf[%(PC_OFF)u] = pc;
}
"""


def _temp_decls() -> str:
    """The emitter's statement-scoped temp registers r5..r24, declared
    exactly as PS006's _REGFILE_SHADER declares them."""
    return "\n".join(f"    var r{i}: u32 = 0u;" for i in range(5, 25))


def _build_shader(batch: int) -> str:
    """Hand-written loop/decode header + GENERATED ALU bodies."""
    from tools.pyshader_compiler import compile_function
    from tools.pyshader_rvexec import (
        STEP_I_SRC, STEP_R_SRC, _alu_body_wgsl)

    body_r = _alu_body_wgsl(compile_function(STEP_R_SRC))
    body_i = _alu_body_wgsl(compile_function(STEP_I_SRC))
    decls = _temp_decls()
    return _SHADER_HEADER % {
        "ARRAY_WORDS": ARRAY_WORDS,
        "IMEM_BASE": IMEM_BASE,
        "TRACE_BASE": TRACE_BASE,
        "TRACE_CAP": TRACE_CAP,
        "TRACE_STRIDE": TRACE_STRIDE,
        "TRACEN_OFF": TRACEN_OFF,
        "STEP_R_DECLS": decls,
        "STEP_I_DECLS": decls,
        "STEP_R_BODY": body_r,
        "STEP_I_BODY": body_i,
        "NINSN_OFF": NINSN_OFF,
        "PC_OFF": PC_OFF,
        "RUNNING_OFF": RUNNING_OFF,
        "STOP_OFF": STOP_OFF,
        "STOP_IMEM_OOB": STOP_IMEM_OOB,
        "STOP_BAD_OPCODE": STOP_BAD_OPCODE,
        "STOP_TRACE_FULL": STOP_TRACE_FULL,
        "BATCH": batch,
    }


def run_fde_gpu(imem: List[int], state: State, max_steps: int,
                batch: int = 256, trace: bool = True) -> Dict:
    """Run the GPU-resident FDE loop until imem-OOB / bad-opcode /
    trace-full / max_steps. Returns a receipt whose `trace` has the
    SAME shape as tools.pyshader_fde.run_fde: trace[0] is the initial
    state, then one snapshot per EXECUTED instruction (pc after the
    instruction, regs after the writeback). pc counts instruction
    indices. ok is False only on a guest-visible fault (BAD_OPCODE) or
    a host config error (TRACE_FULL); falling off the end of imem is
    the normal termination of a straight-line program."""
    imem = load_program(imem)
    if not imem:
        raise ValueError("run_fde_gpu: empty imem")
    if len(imem) > MAX_IMEM_WORDS:
        raise ValueError(
            f"run_fde_gpu: imem {len(imem)} > MAX_IMEM_WORDS "
            f"({MAX_IMEM_WORDS}) — packing would truncate")
    if trace and max_steps > TRACE_CAP:
        raise ValueError(
            f"run_fde_gpu: max_steps {max_steps} > TRACE_CAP "
            f"({TRACE_CAP}) with trace=True — raise TRACE_CAP or "
            f"raise a named shape; do not truncate silently")

    import struct

    import wgpu

    from tools.pyshader_wgsl import _cached_device

    device = _cached_device()
    shader = device.create_shader_module(
        code=_build_shader(batch), label="ps009a-fde")
    n = ARRAY_WORDS
    gpu_buf = device.create_buffer(
        size=n * 4,
        usage=(wgpu.BufferUsage.STORAGE | wgpu.BufferUsage.COPY_SRC
               | wgpu.BufferUsage.COPY_DST),
        label="ps009a-state")
    readback = device.create_buffer(
        size=n * 4,
        usage=wgpu.BufferUsage.COPY_DST | wgpu.BufferUsage.MAP_READ,
        label="ps009a-read")
    pipe = device.create_compute_pipeline(
        layout="auto",
        compute={"module": shader, "entry_point": "main"},
        label="ps009a-pipe")
    bg = device.create_bind_group(
        layout=pipe.get_bind_group_layout(0),
        entries=[{"binding": 0,
                  "resource": {"buffer": gpu_buf, "offset": 0,
                               "size": n * 4}}],
        label="ps009a-bind")

    # initial prefix: regs, pc, running, stop, ninsn, trace_n=0
    prefix = ([v & 0xFFFFFFFF for v in state["regs"][:REG_N]]
              + [0] * (REG_N - len(state["regs"][:REG_N]))
              + [state["pc"] & 0xFFFFFFFF, 1, 0, len(imem), 0])
    assert len(prefix) == PREFIX_WORDS
    payload = prefix + [w & 0xFFFFFFFF for w in imem]
    device.queue.write_buffer(
        gpu_buf, 0, struct.pack(f"<{len(payload)}I", *payload))

    trace_out: List[Dict] = []
    if trace:
        trace_out.append({
            "pc": state["pc"],
            "regs": [v & 0xFFFFFFFF for v in
                     (list(state["regs"]) + [0] * REG_N)[:REG_N]],
        })

    dispatches = 0
    steps_executed = 0
    stop_reason: Optional[int] = None
    final_pc = state["pc"]
    while steps_executed < max_steps:
        enc = device.create_command_encoder(label="ps009a-enc")
        cp = enc.begin_compute_pass()
        cp.set_pipeline(pipe)
        cp.set_bind_group(0, bg)
        cp.dispatch_workgroups(1, 1, 1)
        cp.end()
        enc.copy_buffer_to_buffer(gpu_buf, 0, readback, 0, n * 4)
        device.queue.submit([enc.finish()])
        readback.map_sync(mode=wgpu.MapMode.READ)
        words = list(struct.unpack(f"<{n}I", bytes(readback.read_mapped())))
        readback.unmap()
        dispatches += 1

        stop_reason = words[STOP_OFF]
        final_pc = words[PC_OFF]
        n_trace = words[TRACEN_OFF]

        if trace and n_trace > len(trace_out) - 1:
            for k in range(len(trace_out) - 1, n_trace):
                base = TRACE_BASE + k * TRACE_STRIDE
                trace_out.append({
                    "pc": words[base],
                    "regs": [w & 0xFFFFFFFF
                             for w in words[base + 1:base + 1 + REG_N]],
                })
        steps_executed = (len(trace_out) - 1) if trace \
            else min(n_trace, max_steps)

        if stop_reason != STOP_HALT:
            break

    if steps_executed >= max_steps and stop_reason == STOP_HALT:
        stop_reason = STOP_MAX_STEPS

    ok = stop_reason not in (STOP_BAD_OPCODE, STOP_TRACE_FULL)
    return {
        "ok": ok,
        "stop_reason": stop_reason,
        "dispatches": dispatches,
        "steps_executed": steps_executed,
        "final_pc": final_pc,
        "trace": trace_out,
    }
