"""tools/pyshader_multihart.py — PS010c rung: N-hart GPU kernel, correctness.

SKELETON (skeleton-driven-development): interfaces LOCKED, bodies
stubbed. Spec: GPU_CPU_EMULATOR_ROADMAP.md:233-310 + the PS010b step-4
CORRECTION (.builder_queue/brief_ps010b_divergence_sweep.md — the host
proxy is scale-invariant, so the divergence verdict needs a leg whose
numbers can move); builder contract:
.builder_queue/brief_ps010c_gpu_multihart.md.
The builder populates ONE stub per run; each stub's gate clause lives in
the brief's step table. If a signature below looks wrong, file
REPAIR_PENDING_ps010c_<topic>.md — do NOT edit this file's interfaces.

Model (the PS009a seam extended to N harts, PS010b round semantics):
one storage buffer, one block per hart; the shader's main() runs one
invocation per hart (dispatch_workgroups(ceil(N/WG),1,1)); each
invocation executes EXACTLY ONE transition per dispatch (the round
model — inter-hart state visible only at boundaries; the programs here
are dmem-free so harts are independent and parity is bit-for-bit).
The host loops dispatches (rounds) until every hart is halted
(running==0), or max_rounds is exhausted (loud RuntimeError).

Per-hart block layout (u32 words, HART_BLOCK_WORDS stride):
    [0..31]  registers
    [32]     pc (instruction index)
    [33]     running (1 while live)
    [34]     stop (0 running / 2 IMEM_OOB / 3 BAD_OPCODE)
    [35]     ninsn (per-hart imem length)
    [36]     imem_base (word index of this hart's program start)
imem is appended after all N blocks (static-mix leg packs two programs;
per-hart imem_base points at the hart's own copy — no aliasing).

Instruction subset == PS009a's, plus EBREAK halt:
    R-type 0x33 (ALU funct3 0/1/4/5/6/7) via GENERATED step_r body,
    ALU-Imm 0x13 via GENERATED step_i body,
    B-type 0x63, all six funct3 (BEQ/BNE/BLT/BGE/BLTU/BGEU, RULING_ps010c_
    blt_in_divergent_prog), SPEC semantics target = pc + imm//4
    (RULING_ps008_branch_convention); EBREAK 0x00100073 halts UNCOUNTED
    (running=0, no transition committed — the PS008 convention).
Anything else = STOP_BAD_OPCODE. IMEM_OOB is a per-hart fault surfaced
in the receipt's stop list, never swallowed.

Honest boundary (MIRRORED from PS009a, still true here): no performance
claim anywhere in this rung. wall_seconds are recorded because they are
free; the uniform-vs-adversarial comparison that answers roadmap
:246-268 is the MEASUREMENT rung (same-process pairing, floors
attached), not this correctness gate.

What the stubs return is deliberate: they raise NotImplementedError
(silence would be dangerous); the pins are asserted by the behavioral
tests.
"""
from __future__ import annotations

import time
from typing import Dict, List, Optional

from tools.pyshader_divergence import (
    DIVERGENT_PROG, LOW_PROG, MIX_PROG_LONG, MIX_PROG_SHORT)
from tools.pyshader_fde import REG_N, State, load_program

__all__ = [
    "PC_OFF", "RUNNING_OFF", "STOP_OFF", "NINSN_OFF", "IMEMBASE_OFF",
    "HART_BLOCK_WORDS", "WG_SIZE", "STOP_NONE", "STOP_IMEM_OOB",
    "STOP_BAD_OPCODE", "EBREAK_WORD", "MAX_TOTAL_WORDS",
    "host_reference", "run_multihart_gpu", "gate_multihart_parity",
]

# ── per-hart block layout ───────────────────────────────────────────────
PC_OFF = 32
RUNNING_OFF = 33
STOP_OFF = 34
NINSN_OFF = 35
IMEMBASE_OFF = 36
HART_BLOCK_WORDS = 37

WG_SIZE = 64                    # invocations per workgroup

STOP_NONE = 0
STOP_IMEM_OOB = 2
STOP_BAD_OPCODE = 3

EBREAK_WORD = 0x00100073

# Buffer cap: 65536 harts * 37 + programs. Guard, not a tuning knob.
MAX_TOTAL_WORDS = 65536 * HART_BLOCK_WORDS + 65536 * 8

_SHADER_HEADER = """// generated by tools/pyshader_multihart.py — PS010c N-hart kernel
@group(0) @binding(0) var<storage, read_write> buf: array<u32, %(ARRAY_WORDS)u>;

// GENERATED step_r / step_i bodies (tools.pyshader_rvexec.STEP_*_SRC
// via _alu_body_wgsl — the PS006 extraction, unmodified; the PS009a
// seam reused verbatim).
fn step_r(r1: u32, r2: u32, r3: u32, r4: u32) -> u32 {
    var r0: u32 = 0u;
%(STEP_R_DECLS)s
%(STEP_R_BODY)s
}
fn step_i(r1: u32, r2: u32, r3: u32, r4: u32) -> u32 {
    var r0: u32 = 0u;
%(STEP_I_DECLS)s
%(STEP_I_BODY)s
}

@compute @workgroup_size(%(WG_SIZE)u, 1, 1)
fn main(@builtin(global_invocation_id) gid: vec3<u32>) {
    let hart = gid.x;
    if (hart >= buf[0u]) { return; }   // buf[0] = nharts (pinned prefix)
    let b = %(HART_BLOCK)su + hart * %(STRIDE)u;
    if (buf[b + %(RUNNING)su] == 0u) { return; }   // halted harts idle
    let base = buf[b + %(IMEMBASE)su];
    let ninsn = buf[b + %(NINSN)su];
    let pc = buf[b + %(PC)su];
    if (pc >= ninsn) {
        buf[b + %(STOP)su] = %(STOP_IMEM_OOB_C)su;
        buf[b + %(RUNNING)su] = 0u;
        return;
    }
    let word = buf[base + pc];
    let opcode = word & 127u;
    let rd = (word >> 7u) & 31u;
    let funct3 = (word >> 12u) & 7u;
    let rs1 = (word >> 15u) & 31u;
    let rs2 = (word >> 20u) & 31u;
    let funct7 = (word >> 25u) & 127u;

    if (word == %(EBREAK)su) {
        // EBREAK halts UNCOUNTED (PS008): no transition committed.
        buf[b + %(RUNNING)su] = 0u;
        return;
    }
    if (opcode == 99u) {
        // All six B-type funct3 (RULING_ps010c_blt_in_divergent_prog:
        // semantics verbatim from the LOCKED host oracle ref_ctl,
        // tools/pyshader_ctl.py — BEQ eq, BNE ne, BLT/BGE signed,
        // BLTU/BGEU unsigned). funct3 2/3 = STOP_BAD_OPCODE.
        // SPEC: target = pc + imm//4 (RULING_ps008_branch_convention).
        if (funct3 == 2u || funct3 == 3u) {
            buf[b + %(STOP)su] = %(STOP_BAD_OPCODE_C)su;
            buf[b + %(RUNNING)su] = 0u;
            return;
        }
        let imm = ((word >> 31u) & 1u) * 4096u
                + ((word >> 7u) & 1u) * 2048u
                + ((word >> 25u) & 63u) * 32u
                + ((word >> 8u) & 15u) * 2u;
        let signed_imm = i32(imm ^ 4096u) - 4096;
        let a = buf[b + rs1];
        let bval = buf[b + rs2];
        let eq = a == bval;
        // u32-vs-u32 compare IS the unsigned compare (BLTU/BGEU);
        // i32 reinterpretation IS the signed compare (BLT/BGE) —
        // exactly ref_ctl's _signed_lt.
        let slt = i32(a) < i32(bval);
        var taken = false;
        if (funct3 == 0u) { taken = eq; }           // BEQ
        if (funct3 == 1u) { taken = !eq; }          // BNE
        if (funct3 == 4u) { taken = slt; }          // BLT
        if (funct3 == 5u) { taken = !slt; }         // BGE
        if (funct3 == 6u) { taken = a < bval; }     // BLTU
        if (funct3 == 7u) { taken = a >= bval; }    // BGEU
        var npc = pc + 1u;
        if (taken) {
            npc = (pc * 4u + u32(signed_imm)) / 4u;
        }
        buf[b + %(PC)su] = npc;   // one transition per dispatch
        return;
    }
    if (opcode == 51u) {
        let result = step_r(funct3, funct7, buf[b + rs1], buf[b + rs2]);
        if (rd != 0u) { buf[b + rd] = result; }
        buf[b + %(PC)su] = pc + 1u;
        return;
    }
    if (opcode == 19u) {
        let imm_i = (word >> 20u) & 4095u;
        let simm = i32(imm_i ^ 2048u) - 2048;
        let result = step_i(funct3, funct7, buf[b + rs1], u32(simm));
        if (rd != 0u) { buf[b + rd] = result; }
        buf[b + %(PC)su] = pc + 1u;
        return;
    }
    buf[b + %(STOP)su] = %(STOP_BAD_OPCODE_C)su;
    buf[b + %(RUNNING)su] = 0u;
}
"""

# Programs for gate legs (LOCKED texts imported; words via _words()).
GATE_LEGS = ("uniform", "static_mix", "adversarial")
GATE_NS = (2, 8, 64, 4096, 65536)


def _words(asm_text: str) -> List[int]:
    from tools.rv32i_asm import assemble
    b = assemble(asm_text)
    return [int.from_bytes(b[i:i + 4], "little")
            for i in range(0, len(b), 4)]


# ── stubs (populate ONE per run; gate clauses in the brief) ─────────────


def _build_shader(array_words: int) -> str:
    """Locked _SHADER_HEADER + GENERATED step_r/step_i bodies (the PS009a
    seam: tools/pyshader_fde_gpu._build_shader pattern, reused — no new
    executor). Private helper of run_multihart_gpu; not a new interface."""
    from tools.pyshader_compiler import compile_function
    from tools.pyshader_fde_gpu import _temp_decls
    from tools.pyshader_rvexec import STEP_I_SRC, STEP_R_SRC, _alu_body_wgsl

    body_r = _alu_body_wgsl(compile_function(STEP_R_SRC))
    body_i = _alu_body_wgsl(compile_function(STEP_I_SRC))
    decls = _temp_decls()
    return _SHADER_HEADER % {
        "ARRAY_WORDS": array_words,
        "WG_SIZE": WG_SIZE,
        # Prefix word 0 = nharts; block 0 starts one full stride in so the
        # prefix region mirrors the block stride (buf[0] never aliases a
        # hart's registers).
        "HART_BLOCK": HART_BLOCK_WORDS,
        "STRIDE": HART_BLOCK_WORDS,
        "RUNNING": RUNNING_OFF,
        "IMEMBASE": IMEMBASE_OFF,
        "NINSN": NINSN_OFF,
        "PC": PC_OFF,
        "STOP": STOP_OFF,
        "STOP_IMEM_OOB_C": STOP_IMEM_OOB,
        "STOP_BAD_OPCODE_C": STOP_BAD_OPCODE,
        "EBREAK": EBREAK_WORD,
        "STEP_R_DECLS": decls,
        "STEP_I_DECLS": decls,
        "STEP_R_BODY": body_r,
        "STEP_I_BODY": body_i,
    }


def host_reference(asm_text: str, x5: int = 0) -> State:
    """Host-side reference: run ONE hart of the pinned program to halt
    with the LOCKED primitives (decode_ref/execute_one/execute_ctl —
    the tools.pyshader_divergence.sweep stepping, verbatim). EBREAK
    halts uncounted. Returns the final state (pc + 32 regs)."""
    from tools.pyshader_ctl import ControlHalt, execute_ctl
    from tools.pyshader_fde import execute_one, fetch
    from tools.pyshader_rvdecode import decode_ref

    imem = _words(asm_text)
    if not imem:
        raise ValueError("host_reference: empty program")
    state: State = {"pc": 0, "regs": [0] * REG_N}
    state["regs"][5] = x5 & 0xFFFFFFFF
    for _ in range(64):  # hard budget; pinned programs halt in <=18
        d = decode_ref(fetch(state["pc"], imem))
        if d["fmt"] in ("R", "I") and d["opcode"] in (0x33, 0x13):
            state = execute_one(state, imem)
        else:
            # control/memory layer (PS008); programs here are dmem-free.
            try:
                state = execute_ctl(state, d, None)
            except ControlHalt:
                # EBREAK halts UNCOUNTED (PS008 convention).
                return state
            except IndexError as e:
                raise RuntimeError(
                    f"host_reference: fetch out of bounds at pc "
                    f"{state['pc']}: {e}") from e
    raise RuntimeError(
        "host_reference: 64-step budget exhausted — a pinned program "
        "never runs this long; suspect a bad branch offset")


def run_multihart_gpu(programs: List[str],
                      x5_inits: Optional[List[int]] = None,
                      max_rounds: int = 64) -> Dict:
    """Populate PS010c steps 1-3 (the gate clauses differentiate them;
    one function, three calling patterns).

    programs: per-hart ASM TEXTS (len N) — compiled via _words() here,
    packed imem back-to-back, per-hart imem_base pointing at its own
    copy. NOT mutated (texts).
    x5_inits: optional per-hart x5 preload (the adversarial register
    split). Default all zeros.

    One dispatch = one ROUND: every live hart executes ONE transition
    (the shader commits one transition per invocation; halted harts
    idle in-lane — exactly the warp-occupancy cost the measurement rung
    prices). Host loops dispatches until all harts report running==0.

    Returns a receipt dict:
      n           — hart count
      rounds      — dispatches until the LAST hart halted (1-indexed)
      steps       — per-hart COUNTED transitions (EBREAK uncounted)
      regs        — per-hart final 32-register lists
      stops       — list of (hart, stop_code) for any hart that faulted
                    (STOP_IMEM_OOB / STOP_BAD_OPCODE); empty when clean
      wall_seconds— time.perf_counter around the dispatch loop
                    (informational; never gated on)

    Budget: RuntimeError naming max_rounds if any hart is still running
    at exhaustion — never a silent partial result (PS010 step-3 lesson).
    """
    n = len(programs)
    if n == 0:
        raise ValueError("run_multihart_gpu: programs must not be empty")
    if x5_inits is not None and len(x5_inits) != n:
        raise ValueError(
            f"run_multihart_gpu: x5_inits has {len(x5_inits)} entries "
            f"for {n} harts")

    imems = [_words(t) for t in programs]  # texts never mutated
    total_words = (1 + n) * HART_BLOCK_WORDS + sum(len(w) for w in imems)
    if total_words > MAX_TOTAL_WORDS:
        raise ValueError(
            f"run_multihart_gpu: {total_words} words > MAX_TOTAL_WORDS "
            f"({MAX_TOTAL_WORDS})")

    # buf[0] = nharts (pinned prefix, read by every invocation); hart b's
    # block starts at (1+b)*HART_BLOCK_WORDS so word 0 never aliases regs.
    block0 = HART_BLOCK_WORDS
    payload: List[int] = [n] + [0] * (block0 - 1)
    imem_base = block0 + n * HART_BLOCK_WORDS
    for i, words in enumerate(imems):
        b = block0 + i * HART_BLOCK_WORDS
        regs = [0] * REG_N
        if x5_inits is not None:
            regs[5] = x5_inits[i] & 0xFFFFFFFF
        payload += regs + [0, 1, STOP_NONE, len(words), imem_base]
        imem_base += len(words)
    assert len(payload) == block0 + n * HART_BLOCK_WORDS
    payload += [w & 0xFFFFFFFF for words in imems for w in words]
    assert len(payload) == total_words

    import struct

    import wgpu

    from tools.pyshader_wgsl import _cached_device

    device = _cached_device()  # ONE device, ever (device-exhaustion class)
    shader = device.create_shader_module(
        code=_build_shader(total_words), label="ps010c-multihart")
    gpu_buf = device.create_buffer(
        size=total_words * 4,
        usage=(wgpu.BufferUsage.STORAGE | wgpu.BufferUsage.COPY_SRC
               | wgpu.BufferUsage.COPY_DST),
        label="ps010c-state")
    readback = device.create_buffer(
        size=total_words * 4,
        usage=wgpu.BufferUsage.COPY_DST | wgpu.BufferUsage.COPY_SRC,
        label="ps010c-stage")
    host_read = device.create_buffer(
        size=total_words * 4,
        usage=wgpu.BufferUsage.COPY_DST | wgpu.BufferUsage.MAP_READ,
        label="ps010c-read")
    pipe = device.create_compute_pipeline(
        layout="auto",
        compute={"module": shader, "entry_point": "main"},
        label="ps010c-pipe")
    bg = device.create_bind_group(
        layout=pipe.get_bind_group_layout(0),
        entries=[{"binding": 0,
                  "resource": {"buffer": gpu_buf, "offset": 0,
                               "size": total_words * 4}}],
        label="ps010c-bind")

    device.queue.write_buffer(
        gpu_buf, 0, struct.pack(f"<{total_words}I", *payload))

    def _round() -> List[int]:
        """One dispatch = one ROUND; read back the full buffer."""
        enc = device.create_command_encoder(label="ps010c-enc")
        cp = enc.begin_compute_pass()
        cp.set_pipeline(pipe)
        cp.set_bind_group(0, bg)
        cp.dispatch_workgroups((n + WG_SIZE - 1) // WG_SIZE, 1, 1)
        cp.end()
        enc.copy_buffer_to_buffer(gpu_buf, 0, readback, 0, total_words * 4)
        enc.copy_buffer_to_buffer(readback, 0, host_read, 0,
                                  total_words * 4)
        device.queue.submit([enc.finish()])
        host_read.map_sync(mode=wgpu.MapMode.READ)
        words = list(struct.unpack(
            f"<{total_words}I", bytes(host_read.read_mapped())))
        host_read.unmap()
        return words

    t0 = time.perf_counter()
    stops: List[tuple] = []
    rounds = 1
    # Snapshot 0 is the PRE-dispatch payload (initial state), so round 1's
    # committed transition is counted like every other round's.
    prev: List[List[int]] = [payload]
    words = _round()
    prev.append(words)
    while True:
        live = 0
        for i in range(n):
            b = block0 + i * HART_BLOCK_WORDS
            if words[b + RUNNING_OFF] != 0:
                live += 1
            elif words[b + STOP_OFF] != STOP_NONE and not any(
                    s[0] == i for s in stops):
                stops.append((i, words[b + STOP_OFF]))
        if not live:
            break
        if rounds >= max_rounds:
            raise RuntimeError(
                f"run_multihart_gpu: round budget {max_rounds} exhausted "
                f"with {live} hart(s) still live — budget exhaustion must "
                f"be loud (PS010 step-3 lesson)")
        words = _round()
        rounds += 1
        prev.append(words)
    wall = time.perf_counter() - t0

    # Per-hart COUNTED steps: walk the per-round snapshots — a hart
    # counted a step in round k iff it was live at k's start and its pc
    # moved during k. EBREAK (pc frozen, running drops) is uncounted by
    # construction; a not-taken branch moves pc+1, so pc-movement is an
    # exact proxy for "a COUNTED transition committed" for this subset
    # (every non-EBREAK instruction advances pc by ≥1: ALU pc+1, BNE
    # taken pc+imm//4 ≠ pc — the assembler never emits imm==0 branches
    # in the pinned programs, and a BNE-to-self would hang loudly at
    # max_rounds instead of passing silently).
    steps = [0] * n
    for k in range(1, len(prev)):
        before, after = prev[k - 1], prev[k]
        for i in range(n):
            b = block0 + i * HART_BLOCK_WORDS
            if before[b + RUNNING_OFF] != 0 and (
                    after[b + PC_OFF] != before[b + PC_OFF]):
                steps[i] += 1

    # rounds — the sweep convention (tools/pyshader_divergence.py:192):
    # rounds = max(steps); EBREAK halts IN a round (uncounted), so the
    # final EBREAK dispatch is not a round of its own.
    rounds = max(steps)

    regs_out: List[List[int]] = []
    for i in range(n):
        b = block0 + i * HART_BLOCK_WORDS
        regs_out.append([v & 0xFFFFFFFF for v in
                         words[b + 0:b + REG_N]])

    return {
        "n": n,
        "rounds": rounds,
        "steps": steps,
        "regs": regs_out,
        "stops": stops,
        "wall_seconds": wall,
    }


# ── step-4 pin machinery (private helpers, not locked interfaces) ────────


def _analytic_steps(leg: str, n: int) -> List[int]:
    """The probe-pin per-hart step counts (probe_ps010b receipt: LOW=5,
    SHORT=1, LONG=17, DIVERGENT taken(x5=4)=2 / not-taken(x5=0)=18)."""
    half = n // 2
    if leg == "uniform":
        return [5] * n
    if leg == "static_mix":
        return [1] * half + [17] * (n - half)
    if leg == "adversarial":
        return [2] * half + [18] * (n - half)
    raise ValueError(f"_analytic_steps: unknown leg {leg!r}")


_PIN_REF_CACHE: Dict[str, list] = {}


def _pinned_ref_regs(leg: str) -> list:
    """host_reference final regs per leg variant, cached (one host run
    per variant, not per cell)."""
    if leg not in _PIN_REF_CACHE:
        def _m(s):
            return [v & 0xFFFFFFFF for v in s["regs"]]
        if leg == "uniform":
            _PIN_REF_CACHE[leg] = [_m(host_reference(LOW_PROG, 0))]
        elif leg == "static_mix":
            _PIN_REF_CACHE[leg] = [
                _m(host_reference(MIX_PROG_SHORT, 0)),
                _m(host_reference(MIX_PROG_LONG, 0))]
        elif leg == "adversarial":
            _PIN_REF_CACHE[leg] = [
                _m(host_reference(DIVERGENT_PROG, 4)),
                _m(host_reference(DIVERGENT_PROG, 0))]
        else:
            raise ValueError(f"_pinned_ref_regs: unknown leg {leg!r}")
    return _PIN_REF_CACHE[leg]


def _cell_pins(leg: str, n: int, receipt: Dict) -> List[str]:
    """Pin (a) evaluator for ONE (leg, N) cell: sampled harts
    (0, N//2, N-1) bit-for-bit vs host_reference + step-sum exact vs the
    analytic pin + stops empty. Returns the FAILED pin names (empty when
    the cell is clean) — the non-vacuity instrument, usable on any
    run_multihart_gpu receipt, real or mutant."""
    failures: List[str] = []
    half = n // 2
    refs = _pinned_ref_regs(leg)
    for i in sorted({0, half, n - 1}):
        ref = refs[0] if leg == "uniform" else (refs[0] if i < half
                                                else refs[1])
        if list(receipt["regs"][i]) != ref:
            failures.append(f"parity hart {i}")
    if sum(receipt["steps"]) != sum(_analytic_steps(leg, n)):
        failures.append(
            f"step-sum {sum(receipt['steps'])} != "
            f"{sum(_analytic_steps(leg, n))}")
    if receipt.get("stops"):
        failures.append(f"stops {receipt['stops']}")
    return failures


def gate_multihart_parity() -> Dict:
    """Populate PS010c step 4 — THE correctness gate.
    Runs the three legs (uniform / static_mix / adversarial) at every N
    in GATE_NS via run_multihart_gpu and returns a receipt dict (does
    NOT raise on pin mismatch — the receipt IS the gate artifact):
      ok           — False if any pin fails:
                     (a) parity: sampled harts (0, N/2, N-1) bit-for-bit
                         vs host_reference + per-hart steps match the
                         probe pins (5/17/18; uniform LOW=5);
                     (b) rounds match the probe pins at every N;
                     (c) wall_seconds reported per cell (informational).
      cells        — per (leg, N) receipt dicts.
      pin_failures — failed pin names (empty when ok).
      what_pass_does_not_prove — no wall-clock verdict (measurement
                     rung), no shared-dmem ordering, no divergence-cost
                     number exists yet.
    """
    cells: List[Dict] = []
    pin_failures: List[str] = []
    for leg in GATE_LEGS:
        if leg == "uniform":
            programs = [LOW_PROG]
        elif leg == "static_mix":
            programs = [MIX_PROG_SHORT, MIX_PROG_LONG]
        elif leg == "adversarial":
            programs = [DIVERGENT_PROG]
        else:
            raise ValueError(f"gate_multihart_parity: unknown leg {leg!r}")
        for n in GATE_NS:
            if leg == "uniform":
                progs = programs * n
                x5 = None
            elif leg == "static_mix":
                half = n // 2
                progs = [programs[0]] * half + [programs[1]] * (n - half)
                x5 = None
            else:  # adversarial
                progs = programs * n
                x5 = [4] * (n // 2) + [0] * (n - n // 2)
            t0 = time.perf_counter()
            r = run_multihart_gpu(progs, x5_inits=x5)
            wall = time.perf_counter() - t0
            fails = _cell_pins(leg, n, r)
            analytic = _analytic_steps(leg, n)
            cell = {
                "leg": leg,
                "n": n,
                "rounds": r["rounds"],
                "useful": sum(r["steps"]),
                "slots": n * r["rounds"],
                "wall_seconds": wall,
                "parity_ok": not fails,
                "stops": r["stops"],
            }
            cells.append(cell)
            pin_failures.extend(
                f"{leg}/N={n}: {f}" for f in fails)
            # Pin (b): rounds match the probe pins at EVERY N.
            rounds_pin = {"uniform": 5, "static_mix": 17,
                          "adversarial": 18}[leg]
            if r["rounds"] != rounds_pin:
                pin_failures.append(
                    f"{leg}/N={n}: rounds {r['rounds']} != "
                    f"{rounds_pin}")
            # Per-hart step PATTERN pin (distinct from the sum): harts
            # below the mix boundary vs above, sampled at the analytic
            # extremes — the static-mix steps pin that carried step 2.
            for i in {0, n // 2, n - 1}:
                expect = analytic[0] if i < n // 2 else analytic[-1]
                if r["steps"][i] != expect:
                    pin_failures.append(
                        f"{leg}/N={n}: hart {i} steps "
                        f"{r['steps'][i]} != {expect}")
            # Pin (c): wall_seconds reported per cell — presence, never
            # a threshold (the brief forbids gating on it here).
            if "wall_seconds" not in cell:
                pin_failures.append(f"{leg}/N={n}: wall missing")
    return {
        "ok": not pin_failures,
        "cells": cells,
        "pin_failures": pin_failures,
        "what_pass_does_not_prove": (
            "no wall-clock verdict (measurement rung), no shared-dmem "
            "ordering, no divergence-cost number exists yet — lanes "
            "are one-transition-per-dispatch"),
    }
