"""tools/pyshader_wgsl.py — GlyphIR -> WGSL backend (PS002).

Second backend for the pyshader chain: the same verified GlyphIRModule
that emit_glyph_asm() lowers to spatial assembly is here lowered to a
WGSL compute shader, which wgpu (naga) compiles to SPIR-V and runs on
the real GPU. Structured WGSL if/loop is reconstructed from the IR
block graph; naga handles the SPIR-V structured-control-flow encoding
(OpSelectionMerge / OpLoopMerge) that hand-emission gets wrong.

Design:
    GlyphIRModule -> emit_wgsl() -> WGSL text
                  -> wgpu device -> dispatch(1,1,1) -> readback buffer

Honest boundaries:
    - PS001 shapes only: our front-end produces reducible if/else and
      while graphs; the emitter structurally asserts this and loudly
      rejects anything else (unstructured control flow is future work).
    - u32 semantics mirror GlyphCPUv2: wrapping add/sub/mul (native WGSL
      u32 wrap), shifts masked mod 32, LD/ST on the 64-word region.
    - Region accesses outside [REGION_BASE_WORD, +REGION_WORDS) read 0
      and drop writes on the GPU engine; the interpreter and pixel CPU
      have different OOB behavior (flat 1024-word RAM / linear wrap), so
      differential tests must stay in-bounds. Enforced by a test.
    - One invocation (workgroup 1x1x1): sequential execution, not yet
      parallel. Parallelism over region indices is the next rung.

Differential gate:
    The pure-Python IRInterpreter stays the oracle. The GPU run is a
    THIRD engine: registers and the region window are written to a
    storage buffer at HALT and compared against the oracle AND the
    pixel CPU. Three engines agreeing on known-expected values is the
    receipt; any two agreeing while wrong is the failure class this
    gate exists to catch (see the CMP/JZ inversion, PS001).
"""
from __future__ import annotations

from typing import Dict, List, Optional, Set, Tuple

from tools.glyph_ir import BasicBlock, GlyphIRModule
from tools.pyshader_compiler import (
    FIRST_PARAM,
    REGION_BASE_WORD,
    REGION_WORDS,
    StaticVerificationError,
    U32_MASK,
)

# WGSL storage buffer layout (u32 words):
#   [0..31]  registers r0..r31
#   [32]     running flag (0 = halted)
#   [33]     exit code (r9 snapshot)
#   [34..97] region window (REGION_WORDS words)
REGS_OFF = 0
RUNNING_OFF = 32
EXIT_OFF = 33
REGION_OFF = 34
BUFFER_WORDS = REGION_OFF + REGION_WORDS

_N_PARAMS_MAX = 8


# ── emission ────────────────────────────────────────────────────────────

def emit_wgsl(module: GlyphIRModule, params: Optional[List[int]] = None
              ) -> str:
    """Lower a verified module to a WGSL compute shader string.

    `params` are baked in as r1..rN initializations (the shader has no
    input bindings; each param set gets its own shader text).
    """
    blocks = module.blocks
    index_of = {b.label: i for i, b in enumerate(blocks)}
    _assert_ps001_shapes(blocks, index_of)

    n_params = len(params) if params is not None else _infer_param_count(
        module)
    if n_params > _N_PARAMS_MAX:
        raise StaticVerificationError(
            f"wgsl backend: {n_params} params exceeds max "
            f"{_N_PARAMS_MAX}")

    body = _emit_region(module, index_of, blocks[0].label,
                        frozenset(), depth=0, visited=set())

    lines: List[str] = [
        "// generated by tools/pyshader_wgsl.py — do not edit",
        f"// module: {module.name}",
        "const REGION_BASE: u32 = "
        f"{REGION_BASE_WORD}u;",
        f"const REGION_LEN: u32 = {REGION_WORDS}u;",
        "",
        "@group(0) @binding(0) "
        f"var<storage, read_write> buf: array<u32, {BUFFER_WORDS}>;",
        "",
        "@compute @workgroup_size(1, 1, 1)",
        "fn main() {",
    ]
    for i in range(32):
        lines.append(f"    var r{i}: u32 = 0u;")
    if params:
        lines.append("    // baked parameters")
        for i, v in enumerate(params):
            lines.append(f"    r{FIRST_PARAM + i} = {v & U32_MASK}u;")
    lines.append("    // ---- structured body ----")
    lines.extend(body)
    lines.append("}")
    return "\n".join(lines)


# ── shape checks (loud rejection of anything unstructured) ─────────────

def _assert_ps001_shapes(blocks: List[BasicBlock],
                         index_of: Dict[str, int]) -> None:
    preds: Dict[str, int] = {}
    for b in blocks:
        for s in _successors(b, index_of):
            preds[s] = preds.get(s, 0) + 1
    for b in blocks:
        if b.terminator in ("JZ", "JNZ"):
            succs = _successors(b, index_of)
            if len(succs) != 2:
                raise StaticVerificationError(
                    f"wgsl backend: block '{b.label}' conditional with "
                    f"{len(succs)} successors")
            if succs[0] == succs[1]:
                raise StaticVerificationError(
                    f"wgsl backend: block '{b.label}' branches both arms "
                    "to the same block")
        n = preds.get(b.label, 0)
        if n > 2:
            raise StaticVerificationError(
                f"wgsl backend: block '{b.label}' has {n} predecessors; "
                "PS001 allows at most 2 (loop header / if-join)")


def _successors(b: BasicBlock, index_of: Dict[str, int]) -> Tuple[str, ...]:
    if b.terminator is None:
        return ()
    if b.terminator == "HALT":
        return ()
    if b.terminator in ("JZ", "JNZ"):
        succs: List[str] = []
        if b.terminator_target:
            succs.append(b.terminator_target)
        i = index_of[b.label]
        if i + 1 < len(index_of):
            succs.append(_label_at(index_of, i + 1))
        return tuple(succs)
    if b.terminator == "JMP":
        return (b.terminator_target,) if b.terminator_target else ()
    raise StaticVerificationError(
        f"wgsl backend: unsupported terminator '{b.terminator}'")


def _label_at(index_of: Dict[str, int], i: int) -> str:
    for lbl, idx in index_of.items():
        if idx == i:
            return lbl
    raise StaticVerificationError(f"wgsl backend: no block at index {i}")


def _infer_param_count(module: GlyphIRModule) -> int:
    """Params = highest r1..r8 read before any write across the module."""
    written: Set[str] = set()
    max_p = 0
    for b in module.blocks:
        for ins in b.instructions:
            for o in ins.sources:
                if o.phys_reg and o.phys_reg[0] == "r":
                    n = int(o.phys_reg[1:])
                    if 1 <= n <= _N_PARAMS_MAX and n not in written:
                        max_p = max(max_p, n)
            for o in ins.dests:
                if o.phys_reg:
                    written.add(o.phys_reg)
    return max_p


# ── structured region emission ──────────────────────────────────────────

def _emit_region(module: GlyphIRModule, index_of: Dict[str, int],
                 start: str, stops: frozenset, depth: int,
                 visited: Set[str]) -> List[str]:
    """Emit straight-line + structured if/loop regions starting at
    `start`, stopping (without emitting the jump) when reaching a label
    in `stops`. `visited` guards against re-emission across the module.
    """
    blocks = module.blocks
    ind = "    " * (depth + 1)
    lines: List[str] = []
    label: Optional[str] = start

    while label is not None and label not in stops:
        if label in visited:
            raise StaticVerificationError(
                f"wgsl backend: block '{label}' reached twice outside a "
                "recognized if/loop shape — unstructured control flow")
        visited.add(label)
        b = blocks[index_of[label]]
        nxt = (_label_at(index_of, index_of[label] + 1)
               if index_of[label] + 1 < len(blocks) else None)

        # ── while loop: conditional whose fall-through returns here ──
        # The header block ends with CMP+cond-jump, but the loop body
        # must re-run the CMP each iteration: emit the header's jump as
        # the FIRST statement inside `loop {}`, not outside it. (Getting
        # this wrong bakes a stale flag into the loop — the GPU hang
        # class. The CMP instruction itself is re-emitted inside via the
        # header block's instruction list.)
        if b.terminator in ("JZ", "JNZ") and nxt is not None \
                and _path_returns_to(module, index_of, nxt,
                                     stops | {label}):
            lines.append(f"{ind}// while header at {label}")
            taken = b.terminator_target
            cond = "r0 == 0u" if b.terminator == "JNZ" else "r0 != 0u"
            lines.append(f"{ind}loop {{")
            # header instructions (incl. CMP) re-execute every iteration
            lines.extend(_emit_insns(b, ind + "    "))
            lines.append(f"{ind}    if ({cond}) {{ break; }}")
            lines.extend(_emit_region(module, index_of, nxt,
                                      frozenset({label}),
                                      depth + 1, visited))
            lines.append(f"{ind}}}")
            label = taken
            continue

        # ── if/else diamond: both arms converge on a join ────────────
        if b.terminator in ("JZ", "JNZ") and nxt is not None:
            taken = b.terminator_target
            join_t = _first_jmp_target(module, index_of, taken,
                                       stops)
            join_f = _first_jmp_target(module, index_of, nxt, stops)
            if join_t is not None and join_t == join_f:
                cond = "r0 == 0u" if b.terminator == "JNZ" \
                    else "r0 != 0u"
                lines.extend(_emit_insns(b, ind))
                lines.append(f"{ind}if ({cond}) {{")
                lines.extend(_emit_region(module, index_of, taken,
                                          frozenset({join_t}),
                                          depth + 1, visited))
                lines.append(f"{ind}}} else {{")
                lines.extend(_emit_region(module, index_of, nxt,
                                          frozenset({join_t}),
                                          depth + 1, visited))
                lines.append(f"{ind}}}")
                label = join_t
                continue
            raise StaticVerificationError(
                f"wgsl backend: conditional at '{b.label}' has no common "
                f"join (taken→{join_t}, fall→{join_f})")

        # ── straight-line / JMP / HALT ───────────────────────────────
        lines.extend(_emit_insns(b, ind))
        if b.terminator == "HALT":
            lines.extend(_emit_halt(ind))
            label = None
        elif b.terminator == "JMP":
            label = b.terminator_target
        elif b.terminator is None:
            label = nxt
        else:
            raise StaticVerificationError(
                f"wgsl backend: terminator '{b.terminator}'")
    return lines


def _path_returns_to(module: GlyphIRModule, index_of: Dict[str, int],
                     start: str, stops: frozenset) -> bool:
    """True if following the fall-through/JMP chain from `start` (through
    non-conditional blocks) reaches label `target` — the while back-edge."""
    label: Optional[str] = start
    seen: Set[str] = set()
    while label is not None and label not in stops:
        if label in seen:
            return False
        seen.add(label)
        b = module.blocks[index_of[label]]
        if b.terminator == "JMP":
            if b.terminator_target in stops:
                return True
            label = b.terminator_target
        elif b.terminator is None:
            i = index_of[label]
            label = (_label_at(index_of, i + 1)
                     if i + 1 < len(module.blocks) else None)
        else:
            return False
    return False


def _first_jmp_target(module: GlyphIRModule, index_of: Dict[str, int],
                      start: str, stops: frozenset) -> Optional[str]:
    """First unconditional-jump target on the chain from `start` — the
    if/else join candidate. None if the path HALTs or enters a region we
    are not structuring."""
    label: Optional[str] = start
    seen: Set[str] = set()
    while label is not None and label not in stops:
        if label in seen:
            return None
        seen.add(label)
        b = module.blocks[index_of[label]]
        if b.terminator == "JMP":
            return b.terminator_target
        if b.terminator in ("JZ", "JNZ"):
            return None  # nested conditional inside an arm: not PS001
        if b.terminator == "HALT":
            return None
        i = index_of[label]
        label = (_label_at(index_of, i + 1)
                 if i + 1 < len(module.blocks) else None)
    return None


# ── instruction → WGSL ──────────────────────────────────────────────────

def _emit_insns(b: BasicBlock, ind: str) -> List[str]:
    out: List[str] = []
    for ins in b.instructions:
        out.extend(_emit_insn(ins, ind))
    return out


def _emit_insn(ins, ind: str) -> List[str]:
    op = ins.op
    d = ins.dests[0].phys_reg if ins.dests else None
    s = [o.phys_reg for o in ins.sources if o.phys_reg]
    imm = next((o.imm for o in ins.sources if o.imm is not None), None)

    # NOTE: WGSL `u` suffix is for numeric literals ONLY — register vars
    # (r1, r2, ...) never take it.
    if op == "LDI":
        return [f"{ind}{d} = {imm & U32_MASK}u;"]
    if op == "ADD":
        return [f"{ind}{d} = {d} + {s[0]};"]           # native u32 wrap
    if op == "SUB":
        return [f"{ind}{d} = {d} - {s[0]};"]
    if op == "MUL":
        return [f"{ind}{d} = {d} * {s[0]};"]
    if op == "AND":
        return [f"{ind}{d} = {d} & {s[0]};"]
    if op == "OR":
        return [f"{ind}{d} = {d} | {s[0]};"]
    if op == "XOR":
        return [f"{ind}{d} = {d} ^ {s[0]};"]
    if op == "SHL":
        return [f"{ind}{d} = {d} << ({s[0]} & 31u);"]
    if op == "SHR":
        return [f"{ind}{d} = {d} >> ({s[0]} & 31u);"]
    if op == "CMP":
        # r0 = (lhs == rhs) ? 1 : 0
        return [f"{ind}r0 = select(0u, 1u, {s[0]} == {s[1]});"]
    if op == "LD":
        return [
            f"{ind}{{",
            f"{ind}    let _a = {s[0]} - REGION_BASE;",
            f"{ind}    {d} = select(0u, buf[{REGION_OFF} + _a], "
            f"_a < REGION_LEN);",
            f"{ind}}}",
        ]
    if op == "ST":
        return [
            f"{ind}{{",
            f"{ind}    let _a = {s[0]} - REGION_BASE;",
            f"{ind}    if (_a < REGION_LEN) {{ "
            f"buf[{REGION_OFF} + _a] = {s[1]}; }}",
            f"{ind}}}",
        ]
    if op == "PRT":
        return [f"{ind}// PRT {s[0]} (no stdout on GPU; dropped)"]
    raise StaticVerificationError(f"wgsl backend: unsupported op '{op}'")


def _emit_halt(ind: str) -> List[str]:
    """Writeback at the HALT site, then return. WGSL `return` exits the
    entry point, so the trailing module-level writeback would never run
    if we just returned — every HALT must carry its own copy."""
    lines = [f"{ind}// HALT: writeback + return"]
    for i in range(32):
        lines.append(f"{ind}buf[{REGS_OFF + i}] = r{i};")
    lines.append(f"{ind}buf[{RUNNING_OFF}] = 0u;")
    lines.append(f"{ind}buf[{EXIT_OFF}] = r9;")
    lines.append(f"{ind}return;")
    return lines


# ── GPU run harness (wgpu 0.28.x) ───────────────────────────────────────

_DEVICE_CACHE: List = []  # [device] once created; module-singleton.


def _cached_device():
    """One device for the whole process. PS006 (many parametrized GPU
    tests in one pytest run) discovered that creating a fresh
    adapter+device per call exhausts the driver ("Parent device is
    lost") well before any test-logic issue; every GPU-touching module
    in this chain should request through here, not its own adapter."""
    if not _DEVICE_CACHE:
        import wgpu
        adapter = wgpu.gpu.request_adapter_sync(
            power_preference="high-performance")
        _DEVICE_CACHE.append(
            adapter.request_device_sync(label="pyshader-wgsl"))
    return _DEVICE_CACHE[0]


def run_on_gpu(wgsl_text: str):
    """Compile + dispatch the shader on the real GPU; return
    (registers dict, region list) read back from the storage buffer."""
    import wgpu

    device = _cached_device()

    shader = device.create_shader_module(code=wgsl_text,
                                         label="pyshader")
    n = BUFFER_WORDS
    gpu_buf = device.create_buffer(
        size=n * 4,
        usage=wgpu.BufferUsage.STORAGE | wgpu.BufferUsage.COPY_SRC,
        label="state")
    readback = device.create_buffer(
        size=n * 4,
        usage=wgpu.BufferUsage.COPY_DST | wgpu.BufferUsage.MAP_READ,
        label="readback")

    pipe = device.create_compute_pipeline(
        layout="auto",
        compute={"module": shader, "entry_point": "main"},
        label="pyshader-pipe")

    bg = device.create_bind_group(
        layout=pipe.get_bind_group_layout(0),
        entries=[{
            "binding": 0,
            "resource": {
                "buffer": gpu_buf,
                "offset": 0,
                "size": n * 4,
            },
        }],
        label="state-bind")

    enc = device.create_command_encoder(label="enc")
    cp = enc.begin_compute_pass()
    cp.set_pipeline(pipe)
    cp.set_bind_group(0, bg)
    cp.dispatch_workgroups(1, 1, 1)
    cp.end()
    enc.copy_buffer_to_buffer(gpu_buf, 0, readback, 0, n * 4)
    device.queue.submit([enc.finish()])

    readback.map_sync(mode=wgpu.MapMode.READ)
    data = readback.read_mapped()
    import struct
    words = list(struct.unpack(f"<{n}I", bytes(data)))
    readback.unmap()

    regs = {i: words[REGS_OFF + i] for i in range(32)}
    region = words[REGION_OFF:REGION_OFF + REGION_WORDS]
    return regs, region


def run_triple_differential(source: str, args: List[int],
                            region_init: Optional[Dict[int, int]] = None
                            ) -> Dict:
    """Compile once; run on oracle (IR interpreter), pixel CPU, and GPU.
    Compare r9 + region across all three; return a receipt dict."""
    from tools.pyshader_compiler import (
        IRInterpreter, compile_function, run_differential)
    from tools.pyshader_compiler import REGION_BASE_WORD as RBW

    module = compile_function(source, region_init)
    oracle = IRInterpreter(module).run(args)

    # pixel CPU leg (existing gate)
    cpu_receipt = run_differential(source, args, region_init)

    # GPU leg
    wgsl = emit_wgsl(module, params=args)
    regs, region = run_on_gpu(wgsl)
    gpu_r9 = regs[9]

    interp = IRInterpreter(module)
    interp.run(args)
    exp_region = [w & U32_MASK for w in
                  interp.memory[RBW:RBW + REGION_WORDS]]

    region_ok_gpu = region == exp_region
    ok = (gpu_r9 == (oracle & U32_MASK)) and region_ok_gpu \
        and cpu_receipt["ok"]
    return {
        "ok": ok,
        "oracle_r9": oracle & U32_MASK,
        "cpu_r9": cpu_receipt["cpu_r9"],
        "gpu_r9": gpu_r9,
        "region_ok_gpu": region_ok_gpu,
        "wgsl": wgsl,
    }
