#!/usr/bin/env python3
"""roadmap_scoreboard.py — Deterministic, zero-token status scoreboard.

Reports:
  1. Roadmap Milestones & Gates (from systems/GLYPH_SELF_HOSTING_ROADMAP.md)
  2. Git HEAD & Recent Commits
  3. Working Tree Breakdown (Code vs Visual Audio Runtime vs Untracked)
  4. Builder Loop Status (from ~/.hermes/cron/executions.db)
  5. Disk & Substrate Health

Usage:
  python3 tools/roadmap_scoreboard.py
  python3 tools/roadmap_scoreboard.py --json
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sqlite3
import subprocess
from pathlib import Path
from typing import Any, Dict, List

REPO_ROOT = Path(__file__).resolve().parent.parent
ROADMAP_PATH = REPO_ROOT / "systems" / "GLYPH_SELF_HOSTING_ROADMAP.md"
EXECUTIONS_DB = Path.home() / ".hermes" / "cron" / "executions.db"

# Visual-audio runtime artifacts (AGENTS.md protected / generated by dispatch daemon)
RUNTIME_ARTIFACTS = {
    "db/wordbase.db",
    "spoken.upic.json",
    ".update_proposals.log",
}

# Builder loop job (single source: overridable via env for other loops)
BUILDER_JOB_ID = os.environ.get("GLYPH_BUILDER_JOB_ID", "af3e62239ce2")


def parse_roadmap(path: Path) -> List[Dict[str, str]]:
    if not path.is_file():
        return []
    items = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            if not line.strip().startswith("|"):
                continue
            parts = [p.strip() for p in line.strip().rstrip("|").split("|")[1:]]
            if len(parts) >= 4:
                item_id, name = parts[0], parts[1]
                # Status is the LAST cell: rows may contain embedded '|' in
                # the description/gate cells (e.g. GH-25 "row<<8|col" splits
                # into 8 fragments) — the fixed 4th column would read
                # description text, not status.
                status = parts[-1]
                # Embedded '|' in description cells (GH-25 PTE row<<8|col)
                # fragment one physical row into many logical cells; the
                # real status cell is the LAST physical cell of the markdown
                # row, i.e. the last fragment BEFORE the trailing '|'. A
                # fragment that ends mid-expression (no sentence/text
                # boundary) means we are inside a fragmented cell — scan
                # leftward for the cell that actually carries status
                # (starts with ✅/⏳/⏸️/❌/done).
                if not re.match(r"^(✅|⏳|⏸️|❌|⏸|done|queued|DRAFT|⚠️)", status):
                    for p in reversed(parts[:-1]):
                        if re.match(r"^(✅|⏳|⏸️|❌|⏸|done|queued|DRAFT|⚠️)", p):
                            status = p
                            break
                if re.match(r"^GH-\d+", item_id):
                    st_icon = "⏳"
                    if "✅" in status:
                        st_icon = "✅"
                    elif "QUEUED" in status:
                        st_icon = "⏸️"
                    items.append({
                        "id": item_id,
                        "name": name.split(":")[0],
                        "status_raw": status[:60],
                        "status": st_icon,
                    })
    return items


def get_git_info() -> Dict[str, Any]:
    info: Dict[str, Any] = {"head": "unknown", "recent_commits": [], "dirty": {"code": [], "runtime": [], "untracked": 0}}
    try:
        head = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=REPO_ROOT, text=True).strip()
        info["head"] = head
    except Exception:
        pass

    try:
        log = subprocess.check_output(["git", "log", "-n", "4", "--oneline"], cwd=REPO_ROOT, text=True).strip().splitlines()
        info["recent_commits"] = log
    except Exception:
        pass

    try:
        st = subprocess.check_output(["git", "status", "--porcelain"], cwd=REPO_ROOT, text=True).strip().splitlines()
        for line in st:
            if not line:
                continue
            tag = line[:2]
            path = line[3:].strip()
            if tag == "??":
                info["dirty"]["untracked"] += 1
            else:
                if path in RUNTIME_ARTIFACTS:
                    info["dirty"]["runtime"].append(path)
                else:
                    info["dirty"]["code"].append(path)
    except Exception:
        pass

    return info


def get_cron_telemetry() -> List[Dict[str, Any]]:
    if not EXECUTIONS_DB.is_file():
        return []
    try:
        conn = sqlite3.connect(f"file:{EXECUTIONS_DB}?mode=ro", uri=True)
        c = conn.cursor()
        c.execute("""
            SELECT id, job_id, status, started_at, finished_at, error
            FROM executions
            WHERE job_id = ?
            ORDER BY started_at DESC
            LIMIT 4
        """, (BUILDER_JOB_ID,))
        rows = c.fetchall()
        conn.close()
        res = []
        for r in rows:
            res.append({
                "id": r[0][:8],
                "status": r[2],
                "started": r[3],
                "finished": r[4] or "running",
                "error": (r[5] or "")[:80],
            })
        return res
    except Exception:
        return []


def get_disk_info() -> Dict[str, Any]:
    try:
        total, used, free = shutil.disk_usage(str(Path.home()))
        return {
            "total_gb": round(total / (1024 ** 3), 1),
            "used_gb": round(used / (1024 ** 3), 1),
            "free_gb": round(free / (1024 ** 3), 1),
            "pct_used": round((used / total) * 100, 1),
        }
    except Exception:
        return {}


def format_scoreboard() -> str:
    roadmap = parse_roadmap(ROADMAP_PATH)
    git = get_git_info()
    cron = get_cron_telemetry()
    disk = get_disk_info()

    lines = []
    lines.append("=" * 68)
    lines.append("               GEOMETRY OS ROADMAP SCOREBOARD")
    lines.append("=" * 68)

    # 1. Milestones
    lines.append("\n[1] ROADMAP PROGRESS (Agent OS / Linux Integration Arcs):")
    def _num(x):
        m = re.match(r"^GH-(\d+)", x["id"])
        return int(m.group(1)) if m else -1
    relevant = [it for it in roadmap if _num(it) >= 18]
    for it in relevant:
        lines.append(f"  {it['status']} {it['id']:<6} {it['name']}")

    # 2. Git State
    lines.append("\n[2] GIT STATUS & WORKING TREE:")
    lines.append(f"  HEAD: {git['head'][:10]}")
    for c in git["recent_commits"]:
        lines.append(f"    {c}")
    lines.append("  Working Tree Breakdown:")
    lines.append(f"    - Tracked Code Dirty:     {len(git['dirty']['code'])} {git['dirty']['code']}")
    lines.append(f"    - Visual-Audio Runtime:   {len(git['dirty']['runtime'])} {git['dirty']['runtime']}")
    lines.append(f"    - Untracked Probe/Files:  {git['dirty']['untracked']} files")

    # 3. Builder Telemetry
    lines.append(f"\n[3] BUILDER LOOP TELEMETRY (Job {BUILDER_JOB_ID}):")
    if cron:
        for r in cron:
            err_str = f" | err={r['error']}" if r["error"] else ""
            lines.append(f"  [{r['status'].upper():<9}] ID: {r['id']} | Start: {r['started'][11:19]} -> {r['finished'][11:19] if r['finished'] != 'running' else 'RUNNING'}{err_str}")
    else:
        lines.append("  No recent executions recorded.")

    # 4. System Health
    lines.append("\n[4] SYSTEM & DISK HEALTH:")
    if disk:
        lines.append(f"  /home Space: {disk['free_gb']} GB free of {disk['total_gb']} GB ({disk['pct_used']}% used)")
    lines.append("=" * 68)

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Deterministic Roadmap Scoreboard")
    parser.add_argument("--json", action="store_true", help="Output raw JSON")
    args = parser.parse_args()

    if args.json:
        data = {
            "roadmap": parse_roadmap(ROADMAP_PATH),
            "git": get_git_info(),
            "builder": get_cron_telemetry(),
            "disk": get_disk_info(),
        }
        print(json.dumps(data, indent=2))
    else:
        print(format_scoreboard())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
