#!/usr/bin/env python3
"""run_bm801_path_audit_gate.py -- B8: enumerate every sampling path on the two offset
frames and measure, not infer, which of `dx dy ko jo mode` each one honours.

Two such paths were found in `rung8/bm801_align.py` by accident: `materialize()`
bypassed `plane()` and re-derived its own `% view.h` / `% view.w` indices (B6, landed
`c450342c`), and `OriginFrame.grid()` inherited a `vga.Frame` carve that ignored all
four offsets (B7, landed `64257fb6`). Both were named in a receipt before anything
measured them, and both survived four gates that each printed 9/9. So the open question
has a definite answer: how many more are there, and which of them does any leg reach?

This is an audit, capped at one run, and it changes no source. Row set and columns come
from measurement:

  * the rows are `dir()` on the two classes minus dunders -- so a method added tomorrow
    appears here whether or not anyone remembers to list it;
  * the defining class of each row comes from the MRO, which is how `OriginFrame.lum`
    (never overridden, inherited from `vga.Frame`) is separated from
    `OffsetFrame.lum` (overridden at `bm801_align.py:125`);
  * a row "touches pixels" when its body -- transitively, through its own `self.<m>()`
    calls -- subscripts `self.pixels`, which is computed by AST walk, not by reading;
  * every honour cell is a comparison against a value derived by hand from the PPM
    bytes (`want_*` below), never by calling the aligner, so a fix cannot make the
    table true by agreeing with itself. A cell reads `yes` only when the accessor is
    BOTH sensitive to the perturbation AND equal to the hand-derived value at it;
  * the mode probe is taken at a non-zero phase, because at zero phase no cell is
    out-of-frame and every accessor would pass a mode test vacuously.

`--emit-table` prints the generated markdown table and nothing else; the landed audit
file holds exactly that block between its markers, and leg 11 re-emits it and diffs.

**Corrected by B9 (2026-09-25), which landed the fix this audit queued.** Lines 17-19
above describe the code as B8 found it, and they are kept because the row set is
mechanical: with `OriginFrame.lum` overridden the MRO line still separates the two
`lum` rows, it just separates them the other way. Legs 3 and 4 changed shape when the
row flipped. Leg 3 no longer asserts blindness -- it asserts the flip against the
blindness, reading the `OriginFrame.lum` row out of THIS file's own landed table at
commit `a5bf99e3` (`git show`, so the before cannot be edited into agreeing) and
requiring the fresh measurement to answer `yes` on all five columns. Leg 4 was "no
gate calls `.lum(`"; B9's gate is now a caller, so the leg asserts the opposite and
keeps its control. The blind side itself stays in evidence: it is a property of
`vga.Frame.lum`, which is live code and is what the base-class row is for.

**Corrected by B10 (2026-09-26), which landed the fix for the audit's last two NO rows.**
`OffsetFrame.lum()` and `OffsetFrame.rgb()` now route through a `drops()` gate, so both read
`yes` on `mode` and the table has no NO cell left anywhere. Legs 2 and 10 moved with that:
leg 2 asserts B8's `NO (wraps)` verdict for the pair out of the landed table at `a5bf99e3`
rather than out of the live measurement, and leg 10 -- which existed to catch a vacuous
audit -- can no longer ask fresh code for a defect, so it asks history for the three rows
and cross-checks the one column it can still compute two ways: the pixel-reaching rows with
no gate caller against the generated table's own `nothing` cells. Leg 0 grew a tenth
SOURCES entry, this item's gate.

Run: python3 rung8/run_bm801_path_audit_gate.py   (one beacon boot here, host-side otherwise;
leg 12 boots B7's gate as a subprocess, so a default run is two boots and no more.)
Set BM8_SKIP_OLDER=1 to skip leg 12's nested B7 gate.

**Corrected by B11 (2026-09-26), which cleared the last name on this file's finding 3.** No leg
changed shape: `OriginFrame.physical()` moved from `nothing` to `physical` in the generated table
because B11's gate calls it, which is the census doing its job, and leg 0 grew an eleventh
`SOURCES` entry. Leg 9 -- the module-level indexer census -- is untouched by that item, because
a gate that pins a coordinate need not subscript a frame's pixels anywhere.
"""

import ast
import hashlib
import inspect
import os
import subprocess
import sys
import tempfile
import textwrap

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import bm801_align as al        # noqa: E402
import bm801_capture as cap     # noqa: E402
import bm801_reader_decay as decay   # noqa: E402
import bm801_vga as vga         # noqa: E402

RESULTS = []
KEEP_OUT = 'ubuntu_desktop_pxc1_v3_selfhost'
AUDIT = os.path.join(HERE, 'AUDIT_BM801_SAMPLING_PATHS.md')
TB = '<!-- TABLE BEGIN: generated by `rung8/run_bm801_path_audit_gate.py --emit-table`; do not hand-edit -->'
TE = '<!-- TABLE END -->'
SOURCES = ('bm801_align.py', 'bm801_vga.py', 'bm801_reader_decay.py', 'bm801_capture.py',
           'run_bm801_align_gate.py', 'run_bm801_clamp_gate.py', 'run_bm801_materialize_gate.py',
           'run_bm801_grid_gate.py', 'run_bm801_lum_gate.py', 'run_bm801_rgb_gate.py',
           'run_bm801_physical_gate.py')
# the commit this audit landed in: leg 3 reads its own table out of that tree, so the
# before-side of the row B9 flipped is a fact in git rather than a number in prose
B8_SHA = 'a5bf99e3'

# one-at-a-time perturbations from zero phase; the mode probe carries a phase so that
# at least one sampled cell is out-of-frame under clamp
PX, PY, PK, PJ = 3, 5, 2, 7
TESTVAL = {'dx': PX, 'dy': PY, 'ko': PK, 'jo': PJ}
# logical cells probed: interior, top-left, inside the calibration block, and the
# bottom-right cell -- which is out-of-frame at (PX,PY) and so is where clamp bites
CELLS = [(10, 30), (4, 20), (0, 0), (15, 8), (24, 79), (vga.ROWS - 1, 0)]
PIXEL_XY = [(0, 0), (3, 7), (8, 15), (0, 15), (8, 0)]   # corners and interior of a cell


def predict(name, text):
    print('--> %-32s predicts: %s' % (name, text))


def check(name, ok, detail):
    RESULTS.append((name, bool(ok)))
    print('    %s %-32s %s' % ('PASS' if ok else 'FAIL', name, detail))


# ---------------------------------------------------------------- hand-derived wants
def want_px(rows, w, h, cw, ch, p, r, c, x, y, rgb=False):
    """One pixel of logical cell (r,c): relabel, then phase, then mode. By hand."""
    pr, pc = (r + p['ko']) % vga.ROWS, (c + p['jo']) % vga.COLS
    y0, x0 = pr * ch + p['dy'], pc * cw + p['dx']
    if not (y0 >= 0 and y0 + ch <= h and x0 >= 0 and x0 + cw <= w) and p['mode'] == 'clamp':
        return (0, 0, 0) if rgb else 0
    px = rows[(y0 + y) % h][(x0 + x) % w]
    return (px[0], px[1], px[2]) if rgb else sum(px)


def want_cell(rows, w, h, cw, ch, p, r, c):
    return [[want_px(rows, w, h, cw, ch, p, r, c, x, y) for x in range(cw)]
            for y in range(ch)]


def want_raw(rows, w, h, cw, ch, p, r, c):
    return [want_px(rows, w, h, cw, ch, p, r, c, x, y, rgb=True)
            for y in range(ch) for x in range(cw)]


def want_plane(rows, w, h, cw, ch, p, r, c):
    g = want_cell(rows, w, h, cw, ch, p, r, c)
    flat = [v for row in g for v in row]
    if max(flat) - min(flat) < vga.FLAT_SPAN:
        return tuple([0] * (cw * ch)), True
    mid = (min(flat) + max(flat)) / 2.0
    m = [[1 if v > mid else 0 for v in row] for row in g]
    corners = [m[0][0], m[0][cw - 1], m[ch - 1][0], m[ch - 1][cw - 1]]
    if sum(corners) * 2 > len(corners):
        m = [[1 - v for v in row] for row in m]
    return tuple(v for row in m for v in row), False


def want_profile(rows, w, h, cw, ch, p):
    prof = [0] * cw
    for r in range(vga.ROWS):
        for c in range(vga.COLS):
            g = want_cell(rows, w, h, cw, ch, p, r, c)
            for x in range(cw):
                col = [g[y][x] for y in range(ch)]
                prof[x] += max(col) - min(col)
    return prof


def want_in_frame(w, h, cw, ch, p, r, c):
    pr, pc = (r + p['ko']) % vga.ROWS, (c + p['jo']) % vga.COLS
    y0, x0 = pr * ch + p['dy'], pc * cw + p['dx']
    return y0 >= 0 and y0 + ch <= h and x0 >= 0 and x0 + cw <= w


ZERO = {'dx': 0, 'dy': 0, 'ko': 0, 'jo': 0, 'mode': 'wrap'}

# the anchor every probe hangs from: a phase that IS out-of-frame somewhere, so the
# clamp column has something to bite on
BASE = {'dx': PX, 'dy': PY, 'ko': PK, 'jo': PJ, 'mode': 'wrap'}


def at(**over):
    p = dict(ZERO)
    p.update(over)
    return p


def row_line(doc, label):
    """The landed table row for `label`, as one pipe-delimited line ('' if absent)."""
    for ln in doc.splitlines():
        if ln.startswith('| `%s' % label):
            return ln
    return ''


def cols_of(line):
    """The five honour cells and the gate column of a rendered table row."""
    if not line:
        return None, None
    cols = [x.strip() for x in line.strip('|').split('|')]
    return cols[2:7], cols[7]


def gate_cell(doc, label):
    """The generated table's gate column for `label`, or '?' if the row is not there."""
    line = row_line(doc, label)
    if not line:
        return '?'
    return [x.strip() for x in line.strip('|').split('|')][7]


def landed_table(sha):
    """The generated block as it stood in commit `sha` -- history, not this tree's copy.

    B10 needs this because it fixes the only two `NO` rows the audit ever found: a leg
    that asserted the defect against the *fresh* measurement would be deleted by landing
    the fix, which is how a hole gets quietly marked settled. Asserting against the table
    at the commit that published it survives every later edit of this file.
    """
    proc = subprocess.run(['git', '-C', os.path.dirname(os.path.dirname(os.path.dirname(HERE))),
                           'show', '%s:tools/bare_metal_poc/rung8/%s'
                           % (sha, os.path.basename(AUDIT))],
                          stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if proc.returncode != 0:
        raise RuntimeError('git show %s failed: %s'
                           % (sha, proc.stderr.decode('utf8', 'replace')[-120:]))
    return proc.stdout.decode()



def flatten(cls_name, **over):
    """Anchor params for `cls_name`: an OffsetFrame has no relabelling, so the hand-derived
    side of its rows must be computed with ko/jo at zero too, not just the view."""
    p = dict(BASE)
    p.update(over)
    if cls_name == 'OffsetFrame':
        p['ko'] = p['jo'] = 0
    return p


# ---------------------------------------------------------------- row mechanics
def member_rows(cls):
    """Every non-dunder member of `cls`, with the class in its MRO that defines it."""
    rows = []
    for name in sorted(dir(cls)):
        if name.startswith('__'):
            continue
        attr = getattr(cls, name)
        owner = None
        for klass in cls.__mro__:
            if name in klass.__dict__:
                owner = klass.__name__
                break
        rows.append((name, owner, callable(attr)))
    return rows


def func_src(cls, name):
    attr = getattr(cls, name, None)
    if not callable(attr):
        return None
    try:
        # getsource hands back the method WITH its leading indentation, which ast.parse
        # rejects; dedent is what makes the body parse instead of silently reading empty
        return ast.parse(textwrap.dedent(inspect.getsource(attr)))
    except Exception:
        return None


def self_calls(tree):
    """(name, hinted_class) pairs for work a body hands to another accessor.

    Covers `self.m()`, `self._off.m()` and the unbound `SomeFrame.m(self, ...)` form that
    `OffsetFrame.plane` uses to reach `vga.Frame.plane`. Deliberately an over-approximation
    on the receiver -- any call whose attribute is one of the accessor names counts, whoever
    it is called on. Reachability is a warning column, and the honest direction to err in is
    charging a row with pixels it might not touch, not clearing it.
    """
    out = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute):
            if node.func.attr not in ARITY:
                continue
            recv = node.func.value
            hint = None
            if isinstance(recv, ast.Attribute):        # vga.Frame.plane(self, ...)
                hint = recv.attr
            out.add((node.func.attr, hint))
    return out


def resolve_cls(hint, default):
    """`Frame` as a class object, if this process knows it; else the row's own class."""
    for mod in (vga, al):
        cls = getattr(mod, hint, None) if hint else None
        if isinstance(cls, type):
            return cls
    return default


FRAME_CLASSES = (vga.Frame, al.OffsetFrame, al.OriginFrame)


def delegation_targets(cls, name, hint):
    """Where a call of `name` can land: the base that defines it, and any sibling frame.

    `OriginFrame.raw_cell` hands off to `self._off`, which is an `OffsetFrame` -- not a base
    class -- so an MRO-only walk loses the path. Every class here that defines the accessor
    is tried; this column is an over-approximation on purpose.
    """
    targets = [base for base in cls.__mro__[1:] if name in base.__dict__]
    if hint:                                     # e.g. self._off.<name>(...)
        targets = [k for k in FRAME_CLASSES if name in k.__dict__] + targets
    return [k for k in targets if (k.__name__, name) != (cls.__name__, name)]


def touches_pixels(cls, name, seen=()):
    """Transitive: does this member's body reach a `self.pixels` subscript?

    The guard is on the (class, name) pair, not the name: `OriginFrame.plane` delegating to
    `vga.Frame.plane` is the path, and a name-only guard would cut it off as recursion.
    """
    key = (cls.__name__, name)
    if key in seen:
        return False
    tree = func_src(cls, name)
    if tree is None:
        return False
    for node in ast.walk(tree):
        if isinstance(node, ast.Attribute) and node.attr == 'pixels':
            parent = node.value
            if isinstance(parent, ast.Name) and parent.id == 'self':
                return True
    for callee, hint in self_calls(tree):
        targets = delegation_targets(cls, callee, hint) or [resolve_cls(hint, cls)]
        if any(touches_pixels(target, callee, seen + (key,)) for target in targets):
            return True
    return False


def returns_coord(cls, name):
    """Does the body return a 2-tuple of ints-shaped things (a cell coordinate)?"""
    tree = func_src(cls, name)
    if tree is None:
        return False
    for node in ast.walk(tree):
        if isinstance(node, ast.Return) and isinstance(node.value, ast.Tuple):
            if len(node.value.elts) == 2:
                return True
    return False


def build(cls_name, base, p):
    if cls_name == 'OffsetFrame':
        return al.OffsetFrame(base, p['dx'], p['dy'], p['mode'])
    return al.OriginFrame(base, p['dx'], p['dy'], p['ko'], p['jo'], p['mode'])


def call(view, name, args):
    fn = getattr(view, name)
    return fn(*args)


# arity per accessor: 'px' -> (r,c,x,y); 'cell' -> (r,c); 'all' -> whole frame
ARITY = {'lum': 'px', 'rgb': 'px', 'grid': 'cell', 'raw_cell': 'cell', 'plane': 'cell',
         'ink_profile': 'all', 'in_frame': 'cell', 'drops': 'cell', 'physical': 'cell',
         'pitch_is_exact': 'all'}

WANTS = {}


def want_for(cls_name, name, rows, w, h, cw, ch, p, r, c, x, y):
    if name == 'lum':
        return want_px(rows, w, h, cw, ch, p, r, c, x, y)
    if name == 'rgb':
        return want_px(rows, w, h, cw, ch, p, r, c, x, y, rgb=True)
    if name == 'grid':
        return want_cell(rows, w, h, cw, ch, p, r, c)
    if name == 'raw_cell':
        return want_raw(rows, w, h, cw, ch, p, r, c)
    if name == 'plane':
        return want_plane(rows, w, h, cw, ch, p, r, c)
    if name == 'ink_profile':
        return want_profile(rows, w, h, cw, ch, p)
    if name == 'in_frame':
        return want_in_frame(w, h, cw, ch, p, r, c)
    if name == 'drops':
        return p['mode'] == 'clamp' and not want_in_frame(w, h, cw, ch, p, r, c)
    if name == 'physical':
        return ((r + p['ko']) % vga.ROWS, (c + p['jo']) % vga.COLS)
    if name == 'pitch_is_exact':
        return w % vga.COLS == 0 and h % vga.ROWS == 0
    return None


def norm(v):
    """`self.pixels[a:b]` hands back bytes; the hand-derived value is a tuple of ints."""
    if isinstance(v, (bytes, bytearray)):
        return tuple(v)
    if isinstance(v, list):
        return [norm(x) for x in v]
    if isinstance(v, tuple):
        return tuple(norm(x) for x in v)
    return v


def cells_for(p):
    """Probed cells: interior samples plus the logical cells whose PHYSICAL row/column
    is the last one -- which is where a non-zero phase makes clamp bite. After the ko/jo
    relabelling the logical cell that runs off the edge is not (24,79), so it is computed
    here rather than hard-coded; a mode column measured only on in-frame cells is vacuous.
    """
    last_r = (vga.ROWS - 1 - p['ko']) % vga.ROWS
    last_c = (vga.COLS - 1 - p['jo']) % vga.COLS
    return CELLS + [(last_r, 30), (10, last_c), (last_r, last_c)]


def probe(rows, w, h, cw, ch, cls_name, base, name, frame_only):
    """Measure each dimension cell for one accessor. Returns {dim: (verdict, detail)}.

    One dimension at a time, but not away from zero: the anchor `BASE` carries the other
    perturbations, because at zero phase nothing is out-of-frame, and a mode column
    measured against that anchor would read `yes` for a frame that ignores the mode
    entirely. An `OffsetFrame` has no ko/jo at all, so the anchor is flattened for it and
    the hand-derived value is computed from the same flattened parameters -- the two sides
    of a row have to disagree about exactly the things the class cannot see.
    """
    arity = ARITY[name]
    out = {}
    for dim in ('dx', 'dy', 'ko', 'jo', 'mode'):
        if dim in ('ko', 'jo') and cls_name == 'OffsetFrame':
            out[dim] = ('n/a', 'the class has no such field')
            continue
        if dim == 'mode' and name in ('in_frame', 'physical', 'pitch_is_exact'):
            out[dim] = ('n/a', 'the value does not depend on the mode')
            continue
        if dim in TESTVAL:
            p0 = flatten(cls_name, **{dim: 0})
            p1 = flatten(cls_name)
        else:                                      # mode: probe at the anchored phase
            p0 = flatten(cls_name, mode='wrap')
            p1 = flatten(cls_name, mode='clamp')
        view0, view1 = build(cls_name, base, p0), build(cls_name, base, p1)
        ok = blind = over = stuck = off = moved = n = 0
        first_bad = ''
        for (r, c) in ([(0, 0)] if frame_only else cells_for(p1)):
            for (x, y) in (PIXEL_XY if arity == 'px' else [(0, 0)]):
                n += 1
                args = (r, c, x, y) if arity == 'px' else (r, c) if arity == 'cell' else ()
                try:
                    v0 = norm(call(view0, name, args))
                    v1 = norm(call(view1, name, args))
                except AttributeError:
                    out[dim] = ('absent', 'the class has no such attribute')
                    return out
                g0 = norm(want_for(cls_name, name, rows, w, h, cw, ch, p0, r, c, x, y))
                g1 = norm(want_for(cls_name, name, rows, w, h, cw, ch, p1, r, c, x, y))
                if g1 != g0:
                    moved += 1
                if v1 == v0 and g1 != g0:
                    blind += 1                        # it should have moved and did not
                    if v0 != g0:
                        off += 1
                    continue
                if v0 == g0 and v1 == g1:
                    ok += 1
                    continue
                if not first_bad:
                    first_bad = 'cell(%d,%d)px(%d,%d) got=%s want=%s' % (
                        r, c, x, y, repr(v1)[:34], repr(g1)[:34])
                if v1 != v0:
                    over += 1                         # moved, but not to the honouring value
                else:
                    stuck += 1                        # stationary and not the honouring value
        detail_off = ('; %d of them disagree with the model even at the anchor'
                      % off) if off else ''
        detail_stuck = ('; %d further samples are stationary AND off-model' % stuck
                        if stuck else '')
        if not moved:
            out[dim] = ('n/a', '%d/%d samples, this perturbation cannot change the value'
                        % (n, n))
        elif blind and not over:
            out[dim] = ('NO (wraps)' if dim == 'mode' else 'NO (blind)',
                        '%d/%d samples unchanged where the bytes differ%s%s'
                        % (blind, n, detail_off, detail_stuck))
        elif over or stuck:
            out[dim] = ('MISMATCH', '%d/%d samples equal neither value (%d moved off-model, %d '
                        'stationary off-model); %s' % (over + stuck, n, over, stuck, first_bad))
        else:
            out[dim] = ('yes', '%d/%d samples equal the hand-derived value, %d of them moved'
                        % (ok, n, moved))
    return out


def census():
    """Call sites of each accessor across the ladder, excluding this audit gate."""
    hits = {}
    for root, _dirs, files in os.walk(os.path.dirname(HERE)):
        for fn in files:
            if not fn.endswith('.py') or fn == os.path.basename(__file__):
                continue
            path = os.path.join(root, fn)
            try:
                tree = ast.parse(open(path).read())
            except Exception:
                continue
            for node in ast.walk(tree):
                if (isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute)
                        and node.func.attr in ARITY):
                    hits.setdefault(node.func.attr, []).append(
                        (os.path.relpath(path, os.path.dirname(HERE)), node.lineno))
    return hits


def gate_files_for(name, hits):
    """Which pre-existing gate legs reach it: call sites inside a run_bm80*_gate.py file.

    Matched on the basename -- the census paths are relative to `rung8/`, and matching on
    the path would silently return nothing for every row, which is a false pass for any leg
    that reads "no gate reaches this" as a finding.
    """
    return sorted({f for f, _l in hits.get(name, ())
                   if os.path.basename(f).startswith('run_bm80')
                   and '_gate.py' in os.path.basename(f)})


def measure(base, rows, w, h, cw, ch):
    """The table: one dict per (class, member) row reachable on the two offset frames."""
    hits = census()
    table = []
    for cls_name in ('OffsetFrame', 'OriginFrame'):
        cls = getattr(al, cls_name)
        for name, owner, is_callable in member_rows(cls):
            if not is_callable or name not in ARITY:
                continue
            reach = ('pixels' if touches_pixels(cls, name)
                     else 'coordinate' if returns_coord(cls, name) else 'derived')
            cells = probe(rows, w, h, cw, ch, cls_name, base, name, ARITY[name] == 'all')
            others = sorted({f for f, _l in hits.get(name, ()) if f != 'bm801_align.py'})
            table.append({'class': cls_name, 'name': name, 'owner': owner, 'reach': reach,
                          'cells': cells, 'sites': hits.get(name, ()),
                          'callers': others, 'gates': gate_files_for(name, hits)})
    # the base class rows, for contrast: what every one of the above inherits from
    for name in ('lum', 'grid', 'plane', 'ink_profile'):
        reach = 'pixels' if touches_pixels(vga.Frame, name) else 'derived'
        table.append({'class': 'vga.Frame', 'name': name, 'owner': 'Frame', 'reach': reach,
                      'cells': {d: ('n/a', 'base class: it has no offsets to honour')
                                for d in ('dx', 'dy', 'ko', 'jo', 'mode')},
                      'sites': hits.get(name, ()), 'callers': [], 'gates': []})
    return table


def render(table):
    lines = [TB, '',
             '| path | reaches | dx | dy | ko | jo | mode | reached by a pre-existing gate? |',
             '|---|---|---|---|---|---|---|---|']
    for row in table:
        c = row['cells']
        gates = 'nothing' if not row['gates'] else ', '.join(
            os.path.basename(g).replace('run_bm801_', '').replace('_gate.py', '')
            for g in row['gates'])
        lines.append('| `%s.%s()` (%s) | %s | %s | %s | %s | %s | %s | %s |' % (
            row['class'], row['name'], row['owner'], row['reach'],
            c['dx'][0], c['dy'][0], c['ko'][0], c['jo'][0], c['mode'][0], gates))
    lines += ['', TE]
    return '\n'.join(lines) + '\n'


def main():
    emit = '--emit-table' in sys.argv
    run = tempfile.mkdtemp(prefix='bm808_pathaudit.')
    img = os.path.join(run, 'beacon.img')
    subprocess.run(['nasm', '-o', os.path.join(run, 'b.bin'),
                    os.path.join(HERE, 'bm801_beacon.asm')], check=True)
    data = open(os.path.join(run, 'b.bin'), 'rb').read()
    with open(img, 'wb') as fh:
        fh.write(data + b'\0' * ((1 << 20) - len(data)))
    clean = cap.capture(img, settle=4.0, run_dir=run, keep=True)
    if not emit:
        print('# B8 sampling-path audit | run dir %s' % run)
    src_sha = hashlib.sha256(open(clean, 'rb').read()).hexdigest()[:16]
    base = vga.Frame(clean)
    wc_, hc_, rows = decay.read_rgb(clean)
    cw, ch, w, h = base.cw, base.ch, base.w, base.h
    clamp_probe = at(dx=PX, dy=PY, ko=PK, jo=PJ, mode='clamp')
    n_drop = sum(1 for (r, c) in [(r, c) for r in range(vga.ROWS) for c in range(vga.COLS)]
                 if want_in_frame(w, h, cw, ch, clamp_probe, r, c) is False)
    table = measure(base, rows, w, h, cw, ch)
    if os.environ.get('BM8_DETAILS'):
        for row in table:
            for d in ('dx', 'dy', 'ko', 'jo', 'mode'):
                print('    %-14s %-14s %-6s %s' % (row['class'] + '.' + row['name'], d,
                                                   row['cells'][d][0], row['cells'][d][1]),
                      file=sys.stderr)
    if emit:
        sys.stdout.write(render(table))
        return 0

    print('# frame %dx%d cell %dx%d | capture %s | phase (%d,%d) block (%d,%d): %d of %d '
          'cells out-of-frame under clamp' % (w, h, cw, ch, src_sha, PX, PY, PK, PJ, n_drop,
                                              vga.ROWS * vga.COLS))

    def cell(cls_name, name, dim):
        for row in table:
            if row['class'] == cls_name and row['name'] == name:
                return row['cells'][dim]
        raise KeyError('%s.%s' % (cls_name, name))

    # ---- leg 0: the audit is inert -------------------------------------------------
    predict('0 audit-is-inert',
            'no source under rung8/ changes: each of the %d files listed in SOURCES still hashes '
            'to its HEAD blob, and the capture is byte-identical at the end' % len(SOURCES))
    repo = os.path.dirname(os.path.dirname(HERE))
    drift = []
    for fn in SOURCES:
        rel = 'tools/bare_metal_poc/rung8/' + fn
        # B9 found the shape of this loop wrong: `check=True` here raised out of leg 0 when a
        # file in SOURCES is on disk but not yet in HEAD -- which is exactly what the item
        # adding it looks like mid-run. A missing blob is drift, named, not a traceback.
        proc = subprocess.run(['git', '-C', repo, 'show', 'HEAD:' + rel],
                              stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
        if proc.returncode != 0:
            drift.append('%s(not-in-HEAD)' % fn)
            continue
        disk = open(os.path.join(HERE, fn), 'rb').read()
        if hashlib.md5(proc.stdout).hexdigest() != hashlib.md5(disk).hexdigest():
            drift.append('%s(edited)' % fn)
    sha_after = hashlib.sha256(open(clean, 'rb').read()).hexdigest()[:16]
    self_text = open(os.path.abspath(__file__)).read()
    check('0 audit-is-inert', not drift and sha_after == src_sha
          and self_text.count(KEEP_OUT) == 1,
          'drifted=%s | sha before=%s after=%s | keep-out name occurrences=%d'
          % (drift or 'none', src_sha, sha_after, self_text.count(KEEP_OUT)))

    # ---- leg 1: rows are mechanical -----------------------------------------------
    n_rows = len(table)
    owners = sorted({'%s.%s<- %s' % (r['class'], r['name'], r['owner']) for r in table})
    predict('1 rows-are-mechanical',
            'dir() on the two classes yields the same 9-name accessor set for both, and the ONLY '
            'structural difference left is that OriginFrame has no rgb() -- so `OffsetFrame.lum<- '
            'OffsetFrame` and `OriginFrame.lum<- OriginFrame` both appear, which is the pair this '
            'audit exists to separate; every member left out of the table must be a '
            'data attribute or a helper that reaches no pixels')
    names_of = lambda cls: sorted(r['name'] for r in table if r['class'] == cls)
    skipped = []
    unparsed = []
    for cls_name in ('OffsetFrame', 'OriginFrame'):
        cls = getattr(al, cls_name)
        for name, _owner, is_callable in member_rows(cls):
            if name in ARITY and func_src(cls, name) is None:
                unparsed.append('%s.%s' % (cls_name, name))
            if name not in ARITY and is_callable and touches_pixels(cls, name):
                skipped.append('%s.%s' % (cls_name, name))
    check('1 rows-are-mechanical',
          names_of('OffsetFrame') == sorted(set(ARITY) - {'physical'})
          and names_of('OriginFrame') == sorted(set(ARITY) - {'rgb'})
          and 'OffsetFrame.lum<- OffsetFrame' in owners
          and 'OriginFrame.lum<- OriginFrame' in owners
          and 'OriginFrame.lum<- Frame' not in owners
          and not skipped and not unparsed
          and any(r['reach'] == 'pixels' for r in table),
          'rows=%d | OffsetFrame=%s | OriginFrame=%s | pixel-reaching members left out=%s | '
          'bodies that failed to parse=%s | pixel-reach rows=%d | lum rows=%s' % (
              n_rows, ','.join(names_of('OffsetFrame')), ','.join(names_of('OriginFrame')),
              skipped or 'none', unparsed or 'none',
              sum(1 for r in table if r['reach'] == 'pixels'),
              ','.join(sorted(o for o in owners if '.lum' in o))))

    # ---- leg 2: the pixel-level accessors on OffsetFrame --------------------------
    # B8 measured both rows as honouring dx/dy but not mode, and B10 lands the fix, so this
    # leg flipped sign with it. The before-side is read out of the landed table at B8's own
    # commit rather than quoted from prose: the finding that queued the item stays asserted
    # after the code that produced it is gone.
    try:
        b8_doc = landed_table(B8_SHA)
        b8_err = ''
    except Exception as exc:                        # a missing history leg is a failed leg
        b8_doc, b8_err = '', str(exc)
    b8_lum, _g = cols_of(row_line(b8_doc, 'OffsetFrame.lum()'))
    b8_rgb, _g = cols_of(row_line(b8_doc, 'OffsetFrame.rgb()'))
    predict('2 offset-pixel-accessors',
            'B8\'s landed table at %s reads `NO (wraps)` on mode for both `OffsetFrame.lum()` '
            'and `OffsetFrame.rgb()` (%s / %s); they index with `%% h` / `%% w` with no '
            '`drops()` branch, so under clamp they return the opposite edge. B10 puts the gate '
            'on both, so the fresh measurement must read yes on dx, dy AND mode for the pair -- '
            'while `wrap` cannot move at all, which is leg 7 of B9\'s gate' % (B8_SHA, b8_lum,
                                                                               b8_rgb))
    lum_mode, rgb_mode = cell('OffsetFrame', 'lum', 'mode'), cell('OffsetFrame', 'rgb', 'mode')
    lum_dx, rgb_dx = cell('OffsetFrame', 'lum', 'dx'), cell('OffsetFrame', 'rgb', 'dx')
    check('2 offset-pixel-accessors',
          not b8_err and b8_lum is not None and b8_rgb is not None
          and b8_lum[4].startswith('NO') and b8_rgb[4].startswith('NO')
          and lum_dx[0] == 'yes' and rgb_dx[0] == 'yes'
          and lum_mode[0] == 'yes' and rgb_mode[0] == 'yes',
          'at %s: lum mode=%s rgb mode=%s | measured now: lum dx=%s mode=%s (%s) | rgb dx=%s '
          'mode=%s (%s)%s' % (B8_SHA, (b8_lum or ['-'] * 5)[4], (b8_rgb or ['-'] * 5)[4],
                              lum_dx[0], lum_mode[0], lum_mode[1], rgb_dx[0], rgb_mode[0],
                              rgb_mode[1], (' | git error: %s' % b8_err) if b8_err else ''))

    # ---- leg 3: the row B8 found blind is measured here as honoured -------------
    # The before-side is not quoted from prose: it is read out of this audit's own landed
    # table at B8's commit, so a later edit of this file cannot soften what was found.
    predict('3 origin-lum-flipped',
            'B8 measured `OriginFrame.lum()` as NO (blind) on dx dy ko jo and NO (wraps) on mode, '
            'and B9 lands the one-line override that routes the pixel through `raw_cell()`; the '
            'fresh measurement must now read yes on all five, and this leg fails unless the landed '
            'table at %s still says the opposite -- so the RED stays asserted, just no longer by '
            'this tree\'s copy of the code' % B8_SHA)
    try:
        old_doc = b8_doc if not b8_err else landed_table(B8_SHA)
        old_cols, _old_gates = cols_of(row_line(old_doc, 'OriginFrame.lum()'))
        old_err = ''
    except Exception as exc:                       # a missing history leg is a failed leg
        old_cols, old_err = None, str(exc)
    olum = {d: cell('OriginFrame', 'lum', d) for d in ('dx', 'dy', 'ko', 'jo', 'mode')}
    ogrid = {d: cell('OriginFrame', 'grid', d) for d in ('dx', 'dy', 'ko', 'jo', 'mode')}
    check('3 origin-lum-flipped',
          not old_err and old_cols is not None
          and all(v.startswith('NO') for v in old_cols)
          and all(olum[d][0] == 'yes' for d in ('dx', 'dy', 'ko', 'jo', 'mode'))
          and ogrid['dx'][0] == 'yes' and ogrid['mode'][0] == 'yes',
          'at %s: %s | measured now: %s | OriginFrame.grid dx=%s mode=%s%s' % (
              B8_SHA,
              ' '.join('%s=%s' % (d, v) for d, v in
                       zip(('dx', 'dy', 'ko', 'jo', 'mode'), old_cols or [])) or 'unread',
              ' '.join('%s=%s' % (d, olum[d][0]) for d in ('dx', 'dy', 'ko', 'jo', 'mode')),
              ogrid['dx'][0], ogrid['mode'][0],
              (' | git error: %s' % old_err) if old_err else ''))

    # ---- leg 4: the row that was unreached is now reached, by a gate -------------
    predict('4 lum-row-exercised',
            'B8 found the only call site of `.lum(` in the ladder to be inside `Frame.grid`, and '
            '`grid` overridden on both classes, so the row was reachable and unreached. B9 puts a '
            'caller in a gate file, which is what made the fix testable at all: the leg now '
            'requires a gate to call `.lum(`, and carries its control the other way -- some other '
            'accessor must still show a gate site, because a filter that matched everything would '
            'make this true of a row nobody tests')
    lum_sites = [r['sites'] for r in table if r['class'] == 'OffsetFrame' and r['name'] == 'lum'][0]
    lum_gates = gate_files_for('lum', {'lum': lum_sites})
    grid_sites = [r['sites'] for r in table if r['class'] == 'OriginFrame'
                  and r['name'] == 'grid'][0]
    any_gates = [r['name'] for r in table if r['gates']]
    check('4 lum-row-exercised',
          any(os.path.basename(g) == 'run_bm801_lum_gate.py' for g in lum_gates) and any_gates,
          'lum call sites=%s in gate files=%s | grid call sites=%s | gate-reached names=%s' % (
              sorted({'%s:%d' % s for s in lum_sites}) or 'none',
              lum_gates or 'none',
              sorted({'%s:%d' % s for s in grid_sites}) or 'none',
              ','.join(sorted(set(any_gates))) or 'NONE (the filter is broken)'))

    # ---- leg 5: surface asymmetry -------------------------------------------------
    predict('5 origin-has-no-rgb',
            'getattr on an OriginFrame for `rgb` raises AttributeError, while the same lookup on an '
            'OffsetFrame returns a bound method: a caller written against one class cannot be '
            'pointed at the other, which is the shape of the hole B6 fell into from the other side')
    of = build('OffsetFrame', base, at(dx=PX, dy=PY))
    ov = build('OriginFrame', base, at(dx=PX, dy=PY, ko=PK, jo=PJ))
    try:
        got = getattr(ov, 'rgb', None)
        err = None
    except AttributeError as exc:
        got, err = None, str(exc)
    check('5 origin-has-no-rgb', callable(getattr(of, 'rgb', None)) and got is None,
          'OffsetFrame.rgb=%s | OriginFrame.rgb=%s %s' % (
              type(getattr(of, 'rgb', None)).__name__, got, err or ''))

    # ---- leg 6: cell accessors honour all five ------------------------------------
    predict('6 cell-accessors-honour-all',
            'after B6 and B7, `grid`, `raw_cell` and `plane` on both classes must read yes on all '
            'five columns; a `yes` here is the measurement, not the code reading')
    six = []
    for cls_name in ('OffsetFrame', 'OriginFrame'):
        for name in ('grid', 'raw_cell', 'plane'):
            six.append((cls_name, name, [cell(cls_name, name, d)[0]
                                         for d in ('dx', 'dy', 'ko', 'jo', 'mode')]))
    check('6 cell-accessors-honour-all',
          all(v == 'yes' or v == 'n/a' for _c, _n, cols in six for v in cols),
          ' | '.join('%s.%s=%s' % (c, n, ','.join(cols)) for c, n, cols in six))

    # ---- leg 7: ink_profile reaches pixels through the overridden grid ------------
    predict('7 profile-follows-the-carve',
            '`ink_profile` is defined once, on `vga.Frame`, and is NOT overridden on either class -- '
            'so its honour cells depend entirely on `self.grid` being the fixed one: all five '
            'columns must read yes on OffsetFrame and OriginFrame, and NO if the B7 override is '
            'ever reverted')
    p7 = []
    for cls_name in ('OffsetFrame', 'OriginFrame'):
        cols = {d: cell(cls_name, 'ink_profile', d) for d in ('dx', 'dy', 'ko', 'jo', 'mode')}
        p7.append((cls_name, cols))
    check('7 profile-follows-the-carve',
          all(cols[d][0] in ('yes', 'n/a') for _c, cols in p7 for d in cols),
          ' | '.join('%s: %s' % (c, ' '.join('%s=%s' % (d, cols[d][0])
                                              for d in ('dx', 'dy', 'ko', 'jo', 'mode')))
                     for c, cols in p7))

    # ---- leg 8: the geometry rows -------------------------------------------------
    predict('8 geometry-rows-are-mode-free',
            '`in_frame` and `drops` carry no pixels: `in_frame` honours the phase and the relabel '
            'but is mode-free by contract, `drops` is the mode gate itself, `physical` returns a '
            'coordinate that depends on ko/jo only, and `pitch_is_exact` must be invariant under '
            'every perturbation -- an accessor that changed with a view offset would be reporting '
            'the aligner opinion instead of the capture')
    inf = {d: cell('OriginFrame', 'in_frame', d)[0] for d in ('dx', 'dy', 'ko', 'jo', 'mode')}
    drp = {d: cell('OriginFrame', 'drops', d)[0] for d in ('dx', 'dy', 'ko', 'jo', 'mode')}
    phs = {d: cell('OriginFrame', 'physical', d)[0] for d in ('dx', 'dy', 'ko', 'jo', 'mode')}
    pie = {c: cell(c, 'pitch_is_exact', 'dx')[0] for c in ('OffsetFrame', 'OriginFrame')}
    check('8 geometry-rows-are-mode-free',
          inf['dx'] == 'yes' and inf['mode'] == 'n/a' and drp['mode'] == 'yes'
          and phs['ko'] == 'yes' and phs['dx'] == 'n/a'
          and all(v == 'n/a' for v in pie.values()),
          'in_frame=%s | drops=%s | physical=%s | pitch_is_exact=%s'
          % (inf, drp, phs, pie))

    # ---- leg 9: module-level direct pixel indexers --------------------------------
    # B10 adds a third file to this set, and the reason is worth stating: a gate that keeps a
    # superseded formula in evidence -- so the RED survives the fix -- has to reach the bytes
    # itself, because the class it is measuring no longer does. That is permitted narrowly,
    # only inside a function named `old_*`, and every such site is printed here. rung9 stays
    # forbidden outright, as B8 left it.
    predict('9 module-level-indexers',
            'the class census cannot see a function that indexes `view.pixels` itself, which is '
            'exactly how B6\'s hole was written; every `X.pixels[...]` in the ladder must '
            'therefore live in `bm801_vga.py` (the base Frame), in `bm801_align.py` (the accessors '
            'that got the `drops()` gate), or inside an `old_*` helper in a gate file (a '
            'superseded formula kept live); nothing under rung9/ may index a frame\'s pixels at all')
    idx = []
    for root, _dirs, files in os.walk(os.path.dirname(HERE)):
        for fn in sorted(files):
            if not fn.endswith('.py'):
                continue
            path = os.path.join(root, fn)
            try:
                tree = ast.parse(open(path).read())
            except Exception:
                continue
            owners = {}
            for node in ast.walk(tree):
                if isinstance(node, ast.FunctionDef):
                    for sub in ast.walk(node):
                        owners[id(sub)] = node.name     # innermost wins: methods are walked last
            for node in ast.walk(tree):
                if (isinstance(node, ast.Subscript) and isinstance(node.value, ast.Attribute)
                        and node.value.attr == 'pixels'):
                    idx.append((os.path.relpath(path, os.path.dirname(HERE)),
                                owners.get(id(node), '<module>')))
    by_file = {}
    for f, owner in idx:
        by_file[f] = by_file.get(f, 0) + 1
    outside = sorted({f for f, owner in idx if not owner.startswith('old_')
                      and f not in ('rung8/bm801_align.py', 'rung8/bm801_vga.py')})
    align_sites = sorted(owner for f, owner in idx if f == 'rung8/bm801_align.py')
    check('9 module-level-indexers',
          not outside and not any(f.startswith('rung9') for f, _o in idx)
          and sorted(by_file) == sorted(['rung8/bm801_align.py', 'rung8/bm801_vga.py',
                                         'rung8/run_bm801_rgb_gate.py'])
          and by_file['rung8/bm801_align.py'] == 1 and by_file['rung8/bm801_vga.py'] == 1
          and align_sites == ['rgb'],
          'files=%s | indexers outside the two modules and not in an `old_*` helper: %s | '
          'bm801_align.py owners: %s'
          % (sorted(by_file.items(), key=lambda kv: -kv[1]), outside or 'none', align_sites))

    # ---- leg 10: the worst rows, named by measurement ----------------------------
    # B10 (2026-09-26) fixed the last two NO rows this audit could find on live code, so a
    # leg that required a fresh NO would fail on the run that proves the fix worked. The
    # anti-vacuity claim is therefore taken from history: the landed table at B8's commit
    # must still show the rows, and the fresh table must now agree with itself about which
    # rows no gate reaches -- a column computed from an AST walk against one computed from
    # the probe results, which is the check that survives every future fix.
    blind_rows = [(r['class'], r['name'],
                   [d for d, v in r['cells'].items() if v[0].startswith('NO') or v[0] == 'MIXED'])
                  for r in table
                  if any(v[0].startswith('NO') or v[0] == 'MIXED' for v in r['cells'].values())]
    b8_no_rows = [(lab, cols[4]) for lab in ('OffsetFrame.lum()', 'OffsetFrame.rgb()',
                                             'OriginFrame.lum()')
                  for cols in [cols_of(row_line(b8_doc, lab))[0]]
                  if cols and any(v.startswith('NO') or v == 'MIXED' for v in cols)]
    unexercised = [(r['class'], r['name']) for r in table
                   if r['reach'] == 'pixels' and not r['gates']]
    emitted_doc = render(table)
    nothing_in_table = [(r['class'], r['name']) for r in table
                        if r['reach'] == 'pixels'
                        and gate_cell(emitted_doc, '%s.%s()' % (r['class'], r['name']))
                        == 'nothing']
    predict('10 findings-are-a-ranked-list',
            'B8 published %d rows with a NO cell at %s (%s) and B10\'s fix leaves the fresh '
            'measurement with %d; the audit is still not vacuous, because %d pixel-reaching rows '
            'are called by no gate file and the generated table\'s own `nothing` column must name '
            'exactly that set -- two independent computations of the same fact'
            % (len(b8_no_rows), B8_SHA,
               ' '.join('%s:%s' % (l, c[4]) for l, c in b8_no_rows) or 'none',
               len(blind_rows), len(unexercised)))
    check('10 findings-are-a-ranked-list',
          not b8_err and len(b8_no_rows) == 3 and not blind_rows
          and len(unexercised) >= 1 and sorted(unexercised) == sorted(nothing_in_table),
          'NO rows at %s=%s | fresh rows with a NO/MIXED cell=%d (%s) | pixel rows with no gate '
          'caller=%d (%s) | table says `nothing` for=%d'
          % (B8_SHA, ' '.join('%s' % l for l, _c in b8_no_rows) or 'NONE',
             len(blind_rows), '; '.join('%s.%s:%s' % (c, n, ','.join(ds))
                                        for c, n, ds in blind_rows) or 'none',
             len(unexercised), '; '.join('%s.%s' % (c, n) for c, n in unexercised) or 'none',
             len(nothing_in_table)))

    # ---- leg 11: the landed table is this table -----------------------------------
    predict('11 landed-table-matches-measurement',
            'AUDIT_BM801_SAMPLING_PATHS.md holds the block emitted here between its markers, so the '
            'prose cannot drift from the measurement -- if a cell disagrees the leg prints both')
    emitted = render(table)
    try:
        landed = open(AUDIT).read()
        inside = landed.split(TB, 1)[1].split(TE, 1)[0]
        want = emitted.split(TB, 1)[1].split(TE, 1)[0]
        match = inside.strip() == want.strip()
    except (IOError, IndexError) as exc:
        inside, want, match = '', 'unavailable', False
        print('    (read error: %s)' % exc)
    check('11 landed-table-matches-measurement', match,
          'audit file=%s | table rows=%d | generated block %s the landed block'
          % (os.path.relpath(AUDIT, HERE), len(table), '==' if match else '!='))

    # ---- leg 12: B7s gate still holds the override this audit leans on ------------
    if os.environ.get('BM8_SKIP_OLDER'):
        print('    SKIP 12 older-gates-regress (BM8_SKIP_OLDER=1)')
    else:
        predict('12 older-gates-regress',
                'B7s grid gate, run as a subprocess with its own nested gates skipped, still prints '
                'its full leg count at rc=0 -- the rows above marked yes on `grid` and `ink_profile` '
                'depend on that fix staying in place')
        env = dict(os.environ, BM7_SKIP_OLDER='1')
        p = subprocess.run([sys.executable, os.path.join(HERE, 'run_bm801_grid_gate.py')],
                           capture_output=True, text=True, env=env, cwd=HERE)
        tail = [l for l in p.stdout.splitlines() if l.startswith('RESULT')]
        check('12 older-gates-regress', p.returncode == 0 and bool(tail),
              'rc=%d | %s' % (p.returncode, tail[-1] if tail else p.stdout[-120:]))

    print('')
    print(render(table), end='')
    n = sum(1 for _x, ok in RESULTS if ok)
    print('RESULT %d/%d legs pass' % (n, len(RESULTS)))
    subprocess.run(['rm', '-rf', run])
    return 0 if n == len(RESULTS) else 1


if __name__ == '__main__':
    sys.exit(main())
